# Makefile

NAME = dhsHistory
SOURCES = arg.C config.C hisCa.C hisDbm.C hisDhs.C hisEvent.C hisFits.C hisLogWrite.C hisPutFile.C hisRecovery.C main.C msg.C
LIBS = -ldhs++ -ldhs -ldhsGen -ldhsSta -ldhs++ -lgen -ldb $(EPICS_LDLIBS)

include ../conf/cxx_bin.mk

