# Makefile

NAME = dhsData
SOURCES = arg.C cmd.C con.C config.C ctl.C dbm.C dtsDhs.C get.C list.C main.C msg.C put.C putFits.C putSds.C seq.C store.C
LIBS = -lsf -lfh -ldd -ldhs++ -ldhs -ldhsSta -ldhsGen -lad -lpress -lgen -ldb -lcrc $(TCLTK_LDLIBS)

include ../conf/cxx_bin.mk
