.\"/*+
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"*	Name			: mediaWrite/doc/mediaWrite.1
.\"*
.\"*	Date			: Dec 08, 1998
.\"*
.\"*	SCCS data		: @(#)
.\"*	    Module Name		: mediaWrite.1
.\"*	    Version Number	: 1.3
.\"*	    Release Number	: 1
.\"*	    Last Updated	: 04/14/99
.\"*
.\"*	Written by		: Shannon Jaeger
.\"*
.\"*	Modification History:
.\"*	    98/12/08 SDJ	: Coped from cdWrite.
.\"*        99/02/03 SDJ	: Added security and example section.
.\"*        99/03/08 NRH	: Documented rollback and -num_copies option.
.\"*        99/04/09 NRH	: Documented the -simulate option.
.\"*
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"************************************************************************
.\"-*/
.TH MEDIAWRITE 1 08/12/1998 "CADC"


.SH NAME
mediaWrite
\- Creates one or more copies of a single media (eg. one CD).

.SH SYNOPSIS
.B mediaWrite 
.B \-i 
.I mediaId
.B \-n
.I mediaName
[
.B \-l
.I logicalDeviceName
] [
.B \-num_copies
.I copies
] [
.B \-rollback
] [
.B \-simulate
] [
.B \-force
] [
.B \-V
] [
.B \-v
] 
 
.SH DESCRIPTION
.B mediaWrite
writes a `prepared' media to physical medium(s) using external software
such as
.B tar,
.B cdrecord,
and
.B dvdrecord.
.B mediaWrite
keeps a full log of its activities in the file:
 
.I mediaWrite.mediaId.mediaName.log

which is created in the current working directory.
The script also keeps a full log of its activities in the file

.I MW_mediaId.mediaName.log
 
which is created in the Media Data Stage Directory.

.B mediaWrite
creates the physical medium differently depending on the type
of media used.  It may use the contents of a directory 
or it may use a prepared image. Basically,
the write phase depends on what was done during the preparation phase.
The actions taken are as follows:
.PP
.RS 8
.PD 0
.ta 4c
.TP
.I media type	prepared image/directory
.ta 5c
.TP 4
   tape	   directory
.TP 4
   CD-ROM	prepared image
.TP 4
   DVD-R	       ???
.RE
.PD 1
.PP

The directory used will be in the 
.B Retrieval Data Stage 
and the prepared image will be in one of the 
.B Media Data Stage
subdirectories.  The location
of both of these are given in the 
.B am
library configuration file.  The subdirectory used was specified by 
.B mediaPrep's
.B \-d  
command-line argument, which prepared the media.
The image must be `prepared` before it can be written with
.B mediaWrite. 
.B mediaPrep
is an application 
which prepares media for writing.

.B mediaWrite
executes a script which actually does the writing (burning) of the
media.  The script and its configuration file are listed in the
.B am
library's
configuration file, with the 
.B scripts
keyword.
The script itself will use third party media authoring software.
.B mediaWrite
spawns an
.B xterm
for each device to be used when the script is executed.

Under normal operations the device(s) should be specified by the
.B \-l 
command-line option.  Specification of this option is not required in
order to maintain backwards compatibility, but its use is strongly 
recommended.  

Once all copies of the physical medium  have been written then the 
Media Data Stage
can be cleaned up, freed, and the files on the physical medium may be 
removed from the 
.BR Retrieval Data Stage.  
These operations are performed by
.B mediaCleanup.

.SH OPERATION
The parameters
.B \-i
.IR mediaId ,
and
.B \-n
.IR mediaName ,
must be specified on the command-line, or 
.B mediaWrite
will exit with an error.  
 
.SH OPTIONS
.TP
.B \-l \fIlogicalDeviceName\fR
Specifies a logical device name which corresponds to one or more devices.
The device(s) will each write one or more copies, whatever is required.
.TP
.B \-num_copies
Specify the number of copies to be written or rolled back in this invocation
of 
.BR mediaWrite .
.TP
.B \-rollback
Rollback the write operation, allowing media to be re-written.
.TP
.B \-simulate
Simulate the write operation. The 
.B -simulate 
option doesn't changed the behaviour of 
.BR mediaWrite ,
but the option is passed through to the write script(s).
When the
.B \-simulate
option is set, the script should do as much of its
normal processing as possible without actually writing anything to the
media.
.TP
.B \-force
Force booking of logical device.  If this option is specified then
the logical device, given with the
.B \-l
option, is booked and used for writing even if it is already in use.
.TP
.B \-v
Verbose.  Print all information and error messages to standard output,
.I stdout.
.TP
.B \-V
Version.  Print version numbers and quit.
.TP
.B \-? \-h \-help
Help.     Print command-line usage message and quit.
 
.SH USAGE
.B mediaWrite
may require operator input. Operators are prompted to remove written
media from the device(s) once they have been written and to put 
blanks into the device(s) as needed.

The third party media  authoring software may have its own operator prompts.
For example 
.B GEAR 
will ask for confirmation of the settings.  See the media authoring
software user manual for more details.

.SH EXAMPLES
.TP 3
.B 1.
The following  example specifies a logical device that will be
used to burn the CD-ROMs. In this case the logical device corresponds
to two CD-Writers which will write the CD-ROMs in parallel.
.RS 5
.sp 1
.ft
.nf
.BR "example% mediaWrite \-i " 3 " \-n " ARCHIVE3_001 " \-l " CDPair1
.IB "messages from " mediaWrite
.sp 1
.fi
.RE
.RS 3
The CD-ROM for the prepared media unit
.B ARCHIVE3_001
will be burned on the devices associated with
.BR CDPair1 .
.RE
.TP 3
.B 2.
The following example does not give a logical device name to be
used during the writing process. The first free device found will
be used to write the media.  This mode should 
.B not
be used normally.  The only place where this would be useful is
where there is only one device.
.RS 5 
.sp 1
.nf
.BR "example% mediaWrite \-i " 4 " \-n " USER2_002 " \-v"
.IB "messages from " mediaWrite
.sp 1
.fi
.RE
.RS 3
Media unit
.B USER2_002,
which belongs to media request
.B 4,
will be written by the first available device found by
.B mediaWrite.
Since the
.B \-v
option was specified the operator will be informed of all 
.B mediaWrite's
activities.
.RE
.TP 3
.B 3.
The following example writes to a tape device(s) rather than a
CD-writer, which was given in example 1.  The logical device name 
given in this example suggests that we are using 90 minute tapes.
.RS 5
.sp 1
.ft
.nf
.BR "example% mediaWrite \-i " 1 " \-n " ARCH0132 " \-l " TP90_1
.IB "messages from " mediaWrite
.sp 1
.fi
.RE
.RS 3
The 90 minute tape for the prepared media unit
.B ARCH0123
will be written on the device(s) associated with the logical device name
.BR TP90_1 .
.RE
.TP 3
.B 4.
The following  example specifies a logical device that will be
used to burn the CD-ROMs and uses the 
.B \-simulate 
option. 
In this case the logical device corresponds
to two CD-Writers which will write the CD-ROMs in parallel.
.RS 5
.sp 1
.ft
.nf
.BR "example% mediaWrite \-simulate \-i " 3 " \-n " ARCHIVE3_001 " \-l " CDPair1
.IB "messages from " mediaWrite
.sp 1
.fi
.RE
.RS 3
Writing of the CD-ROM for the prepared media unit
.B ARCHIVE3_001
will be simulated, and if the simulation succeeds, the database will be
updated to indicate that the media have been successfully written. Note
that since the script doing the writing may actually be sending data to
the writer, the writer should be considered to be busy when 
.B mediaWrite
is simulating a write operation.
.RE


.SH FILES
.SS ~/.dbrc
The
.I ~/.dbrc
file contains information about each database that a user may 
reference with executables such as 
.BR mediaWrite.
More specifically it contains information about SYBASE servers, 
databases, user names and associated passwords. 

A database reference must contain a server/database pair followed
by the user's name and password. Each line of the 
.I ~/.dbrc
file must contain a complete server/database reference for every 
database which may be accessed through this file. Each line of
this file must be arranged in the following order:
 
.I server database username password

Each item should be separated by whitespace (spaces and/or tabs).
If a required database is not included in the 
.I ~/.dbrc 
file, 
.B mediaWrite
will prompt for a user's name and password.
 
.SS libAm.config
.B mediaWrite
uses the CADC
.B Archive Media 
.RB ( am )
library which requires its own configuration file.  Refer
to the 
.B am
man page for more information on this file.
 
.SH SECURITY
In order to ensure a secure
.I ~/.dbrc
file,
.B mediaWrite
requires that the
file resides in the directory specified by the 
.B HOME 
environment variable, and the file protection must restrict read and write
access to the file owner. 

.SH TABLES
.B mediaWrite
gets the information necessary to prepare media units from the 
.B Archive Media
.RB ( am )
database tables.  The location of the 
.B am 
database, and the name of the
tables are specified in the configuration file for the 
.RB ( am )
library. These tables must exist for 
.B mediaWrite
to run correctly.

The following is a list of SYBASE tables that must be present for 
.B mediaWrite
to run correctly:
.TP
.B archiveMedia..media
.TP
.B archiveMedia..media_units
.TP
.B archiveMedia..media_stages
.TP
.B archiveMedia..devices
.TP
.B archiveMedia..book

.SH ENVIRONMENT VARIABLES
The environment variable 
.B LIBAM_CONFIG_DIR
may be set to the path of the directory where the 
.B am
library configuration file can be found. If
.B LIBAM_CONFIG_DIR
is not set, the environment variable
.B DEFAULT_CONFIG_DIR
should be set to the path where the file can be found.
 
The environment variable
.B DISPLAY
must be set.  This environment variable indicates which X
server should be used by the
.B xterm. 
In many cases this 
environment variable is set automatically by the login 
environment. However, there are some situations where it may be necessary 
to set the environment variable explicitly, such as remote logins.

The environment variable
.B HOME
must be set to the user's home directory.  If this environment variable
is not set correctly,
.B mediaWrite
may not find the correct
.I~/.dbrc
file containing database information.

The shell's path variable
should include the locations of the
.B xterm  
executable, the third party media authoring software
and the script indicated in the
.I libAm.config
configuration file with the 
.B scripts
keyword.

.SH DIAGNOSTICS
.B mediaWrite
returns a 0 to the calling environment upon successful completion.
Otherwise a non-zero number is returned. 


.SH SEE ALSO
.BR mediaPrep(1),
.BR mediaCleanup(1),
.BR cdWriteRunGear\-33(1),
.BR cdWriteRunCdrecord\-16(1),
.BR cdrecord(1),
.BR am(3),
and
.BR db(3).

.B GEAR for UNIX User's Manual, 
.B Elektroson USA 

 
.SH BUGS
On SunOS, possibly on other operating systems too, attempting to write
to two CD-Writers on the same SCSI bus will cause errors.  Depending on the
CD authoring software it may even crash your entire system.

DVD writers may behave similarly; they have not been tested to date.

.SH AUTHOR
Shannon Jaeger
.br
 
National Research Council of Canada
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre

