.\"/*+
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) <year>				(c) <year>
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-		ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME
.\" dhsQlServer.1
.\"
.\" PURPOSE:
.\" Describe the DHS Quick Look Server.
.\"
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
.\"
.\"
.\" Revision 1.1.1.1  1999/08/23 19:58:25  cvs-tuc
.\" Initial install into CVS of dhs-0.16
.\"
.\" Revision 1.6  1998/07/02 18:22:06  nhill
.\" Fixed typo.
.\"
.\" Revision 1.5  1998/07/02 18:03:05  nhill
.\" *** empty log message ***
.\"
.\" Revision 1.4  1998/07/02 17:33:52  nhill
.\" Updated.
.\"
.\" Revision 1.3  1997/11/18 23:16:00  nhill
.\" Changed the application name to dhsQls.
.\"
.\" Revision 1.2  1997/11/17 22:23:41  nhill
.\" *** empty log message ***
.\"
.\" Revision 1.1  1997/11/17 21:40:40  nhill
.\" Initial revision
.\"
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.\"
.                       \" Ty macro to start an indent for each type def.
.de Ty
.ie n .TP 14n
.el .TP 16n
..
./"
.TH dhsQlServer  1 27/11/97 "CADC"

.SH NAME

dhsQlServer
\- Server for distributing data to appropriate Quick Look Tools


.SH SYNOPSIS

.B dhsQlServer 
[
.B -debug NONE | MIN | FULL 
] [
.B -simulate
] [
.B -V
] [
.B -master
]


.SH DESCRIPTION

The DHS Quick Look Server (QLS)
is a traffic director for Gemini quick look data. It accepts data
from a data server, or another Quick Look Server, and forwards the data to 
Quick Look Tools (QLT), or to other Quick Look Servers on different
machines.
 
.SH OPERATION

As a minimum the DHS Status Server 
must be running prior to running the Quick Look Server.
Once the QLS is running, it
will remain idle until data is received from the DHS Data Server
in the form of a FITS file containing
all or part of the data for a dataset. When data is received, 
the QLS will create a header and data file for each frame contained in the 
dataset,
and write the FITS header and image data for each frame to a file. The QLS
will then notify the appropriate QLTs that the data for the frames has been
modified. The data originally received will also be forwarded to any slave
Quick Look Servers which require the data.

Only one Quick Look Server should be run on each computer system to be 
used to display Quick Look Data. This restriction is enforced by the program.

A complete description of the QLS operation can be found in 
"The Gemini Data Handling System User Manual"

.SH COMMANDS

The commands accepted by the QLS are documented in 
"ICD 3.2 - The DHS interface".

.SH OPTIONS

.TP
.B -debug NONE | MIN | FULL 
Debug mode.  Depending on the mode set, it will print various degrees of 
error messages to standard output.  
.TP
.B -simulate
Simulate mode.  If the QLS is in simulate mode, all data arriving will
be ignored. All other QLS functions are unaffected.
.TP
.B -V
Version.  Print version numbers and quit.
.TP
.B -master
Run the Quick Look Server as the master Quick Look Server, receiving data
directly from the DHS Data Server. If this option is not used, the Quick
Look Server will run as a slave Quick Look Server, and will attempt to 
connect to the master Quick Look Server named in the configuration file.


.SH FILES

.SS

.B dhsQls.config
The QLS requires a configuration file
to set some parameters necessary for its operation. 
The following is an example configuration file.
(Text followed by a '#' is treated as a comment and ignored by
the QLS. Blank lines are also ignored.):

.sp
.nf

#
#  Application identification. This keyword specifies the IMP 
#  name to use when running this program.
#
# Keyword       application 
#
# -------       -----------
#

identity        qlServer


#
#  Imp information. This keyword specifies the maximum number
#  of IMP connections to allow. This must be enough for the
#  connection to the DHS Status Server, the Connection to the
#  DHS Data Server, all connections to Slave Quick Look Servers,
#  and all connections to Quick Look Tools.
#
# keyword       Max connects
#
# --------      ------------
#

imp             20


#
#  Status server identification information. This is the IMP name
#  And address of the DHS Status Server to use for logging status 
#  and history.
#
# keyword       Identity      address
#
# -------       --------      -------
#

statusServer    statusServer  daxka


#
#  Master quick look server identification information. This is
#  the IMP name and address to use when a slave QLS looks for a
#  master QLS. This is ignored if the program is run with the
#  -master option.
#
# keyword       name         address
# -------       ----         -------
#

masterId        qlServer     daxka


#
#  Data server identification information. This is the DHS Data
#  Server used to search for datasets when a QLT user requests
#  that a specific dataset be displayed.
#
# keyword       name            address
# -------       ----            -------
#

dataServerId    dataServer1     daxka


#
#  Default quick look streams. This is a list of streams to 
#  display to the user when they want to select the list of
#  streams to subscribe to. If streams are not in this list,
#  the user will have to type the names of the streams in the
#  QLT interface.
#
# keyword       name
#
# -------       ----
#

qlStream        gmosFlat
qlStream        gmosBias
qlStream        gmosScience


#
#  Fits keyword information.  By default the QLS copies FITS 
#  keywords in the main FITS header into all of the frame FITS
#  files, and copies FITS keywords in extension headers into
#  only the associated frame FITS file. The fitsKeyword keywords 
#  enable special handling for certain FITS keywords. 
#
# keyword       keyword         main    copy from       copy from
#               name            header  first           next
# -------       -------         ------  ---------       ---------
#

fitsKeyword     ""              TRUE    false           false
fitsKeyword     ""              false   false           false
fitsKeyword     COMMENT         TRUE    false           false
fitsKeyword     COMMENT         false   false           false
fitsKeyword     HISTORY         TRUE    false           false
fitsKeyword     HISTORY         false   false           false
...
.fi

A QLS will create temporary files in directory 
.RI /tmp/dhsQlServer. user ,
where 
.I user 
is the name of the user that ran the QLS. (The addition of the user name
to the temporary directory name is a development feature to allow
more than one user to run a QLS.) Subdirectory "datasets" within this
temporary directory is created as a storage area for the frame FITS files.
Subdirectories are also created for each connected QLT. 
The QLT subdirectories 
contain hard links to the frame files in the "datasets" directory, 
allowing both
the QLS and QLTs to delete their links when they are done with a file,
without being concerned about other programs using the data.

The temporary directory and its contents are removed when the QLS exits, 
or when the QLS re-starts after an abnormal exit.

.SH ENVIRONMENT VARIABLES

Upon startup, a QLS
looks for its configuration file in the directory specified by the 
environment variable
.B DHSQLS_CONFIG_DIR.
If not defined, it looks in the directory in the 
.B DEFAULT_CONFIG_DIR 
environment variable, and finally will look in the current directory.

The IMP scratch directories used to communicate with other processes are
located in the directory specified with the IMP_SCRATCH environment variable.
The IMP_SCRATCH directory must be the same for all programs that the Quick
Look Server will communicate with.



.SH DIAGNOSTICS

Returns 0 upon successful completion, otherwise -1.


.SH SEE ALSO

.BR dhsQlTool (1).

.BR dhsData (1).

.BR dhsStatus (1).

.SH DOCUMENTS

.TP
.B The Gemini Data Handling System User Manual
.TP
.B ICD 3.2 - The DHS interface

.SH BUGS

Too many messages are being sent to notify a QLT that a frame has changed.
This is because it is assuming a frame has changed, even if a FITS keyword
was replaced with exactly the same value.

After a reset or init, QLT loses the subscription information from QLTs
and slave QLSs.

.SH AUTHORS
Norman Hill
.br

National Research Council
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
