.\"/*+
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"*	Name			: am/doc/am.3
.\"*
.\"*	Date			: Dec 16, 1998
.\"*
.\"*	SCCS data		: @(#)
.\"*	    Module Name		: am.3
.\"*	    Version Number	: 1.8
.\"*	    Release Number	: 1
.\"*	    Last Updated	: 04/29/99
.\"*
.\"*	Written by		: Shannon Jaeger
.\"*
.\"*	Modification History:
.\"*	    98/12/16 SDJ	: Copied from VLT tree and updated.
.\"	    99/02/01 SDJ	: Updated to match code changes.
.\"	    99/03/05 NRH	: Added amFileDelete, and some options
.\"				  to amFileGet.
.\"	    99/03/18 NRH	: Added function amNumOnUnit.
.\"*
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"************************************************************************
.\"-*/
.			\" Ty macro to start an indent for each type def.
.\"
.de Ty
.ft 1
.fi
.RE
.PP
.ie n .TP 12n
.el .TP 16n
..
.			\" Td macro to display the type definition.
.\"
.de Td
.PP
.RS
.ft 3
.nf
.ie n .in 10n 53n
.ta 25n 60n
..
.			\" Ss macro to start a structure definition.
.\"
.de Ss
.PP
.RS
.nf
.ft 3
.ie n .ta 12n 26n 55n
.el .ta 16n 40n 70n
..
.			\" Es macro to end a structure definition.
.\"
.de Es
.ft 1
.fi
.RE
.PP
..
.\"
.TH AM 3 02/04/99 "CADC"
 
.SH NAME
am \- Archive media access routines.
.sp 1
.ta 5c 11c 11c 2c
.nf
amActionAdd	amActionDelete	amAmountOnUnit
amAmountQueueable	amAmountRetrievable	amCleanedUp
amClose	amDataStageGet	amDbInfoGet
amDeviceBook	amDeviceClear	amDeviceGet
amDeviceLookup	amFileDelete	amFileGet
amFilePut	amFileUpdate	amGet
amIngestGet	amInit	amMSBook
amMSClear	amMSGet	amMediaIdGet
amMediaTypeGet	amNotifiable	amNumCleanupable
amNumCopiesWritten	amNumOnUnit	amNumPreparable
amNumWriteable	amPrecisionGet	amPrepared
amPut	amScript	amStatusStr
amUnitDelete	amUnitGet	amUnitPut
amUnitUpdate
.fi

.SH SYNOPSIS
.LP
.nf
#include "sybfront.h"
#include "sybdb.h"

#include "gen_types.h"
#include "gen_str.h"
#include "gen_msg.h"
#include "db.h"
#include "am.h"
.ft
.fi
.LP
.\".nf
.\".ta 0.8i

.TP 7n 
int
amActionAdd( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
char * \fImediaUnitName\fR, char * \fIaction\fR )
.TP 7n 
int
amActionDelete( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
char * \fImediaUnitName\fR )
.TP 7n 
int
amAmountOnUnit( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
char * \fImediaUnitName\fR, int * \fIreturnValue\fR )
.TP 7n  
int
amAmountQueueable( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
float * \fIreturnValue\fR )
.TP 7n
int
amAmountRetrievable( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
float * \fIreturnValue\fR )
.TP 7n
int
amCleanedUp( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
boolean * \fIreturnValue\fR )
.TP 7n
void 
amClose( void )
.TP 7n
int
amDataStageGet( char ** \fIamArchDStage\fR, char ** \fIamUserDStage\fR,
char ** \fIamMediaDStage\fR )
.TP 7n
int
amDbInfoGet( char ** \fIdatabaseServer\fR, char ** \fImediaDatabase\fR, 
char ** \fImediaTable\fR, char ** \fImediaUnitTable\fR, 
char ** \fImediaFilesTable\fR )
.TP 7n
int
amDeviceBook( char * \fIlogicalDeviceName\fR, boolean \fIforce\fR, 
struct dbprocess * \fIdbproc\fR, struct amDevice * \fIdevice\fR )
.TP 7n 
int
amDeviceClear( AM_DC_ALL, struct dbprocess * \fIdbproc\fR )
.TP 7n 
int
amDeviceClear( AM_DC_DEVICE, struct dbprocess * \fIdbproc\fR, 
struct amDevice * \fIdevice\fR )
.TP 7n 
int
amDeviceClear( AM_DC_LOGICAL, struct dbprocess * \fIdbproc\fR, 
char \fIamLogicalDeviceName\fR )
.TP 7n
int
amDeviceGet( AM_DG_ALL, struct amDevice * \fIdevice\fR,
struct dbprocess * \fIdbproc\fR  )
.TP 7n
int
amDeviceGet( AM_DG_NAME, struct amDevice * \fIdevice\fR,
struct dbprocess * \fIdbproc\fR, char * \fIdeviceName\fR )
.TP 7n
int
amDeviceGet( AM_DG_NAME_TYPE, struct amDevice * \fIdevice\fR,
struct dbprocess * \fIdbproc\fR, char * \fIdeviceName\fR,
char * \fImediaType\fR )
.TP 7n
int
amDeviceGet( AM_DG_TYPE, struct amDevice * \fIdevice\fR,
struct dbprocess * \fIdbproc\fR, char * \fImediaType\fR )
.TP 7n
int
amDeviceLookup( char * \fIlogicalDeviceName\fR,
struct dbprocess * \fIdbprocess\fR, char * \fImediaType\fR,
struct eptr ** \fIDeviceList\fR )
.TP 7n
int
amFileDelete( amFile * \fImediaFile\fR, struct dbprocess * \fIdbproc\fR )
.TP 7n
int
amFileGet( AM_FG_FILE_ID, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, char * \fIfileId\fR )
.TP 7n
int
amFileGet( AM_FG_FNAME, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, char * \fIfileName\fR )
.TP 7n
int
amFileGet( AM_FG_MEDIA_FILE, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR,
char * \fIfileId\fR )
.TP 7n
int
amFileGet( AM_FG_MEDIA_ID_FNAME, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR,
char * \fIfileName\fR )
.TP 7n
int
amFileGet( AM_FG_MEDIA_REQUEST_ID | AM_FG_QUEUEABLE | AM_FG_RETRIEVABLE |
AM_FG_UNWRITTEN, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR )
.TP 7n
int
amFileGet( AM_FG_MEDIA_UNIT, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, struct amUnit * \fImediaUnit\fR )
.TP 7n
int
amFileGet( AM_FG_MEDIA_UNIT_ID, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
char *\fImediaUnitName\fR )
.TP 7n
int
amFileGet( AM_FG_NEXT, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR )
.TP 7n
int
amFileGet( AM_FG_SOURCE_ID, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, char * \fIsourceId\fR )
.TP 7n
int
amFileGet( AM_FG_STATUS, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, char \fIstatus\fR )
.TP 7n
int
amFileGet( AM_FG_UNIT_FNAME, struct amFile * \fImediaFile\fR, 
struct dbprocess * \fIdbproc\fR, struct amUnit * \fImediaUnit\fR,
char * \fIfileName\fR )
.TP 7n
int
amFilePut( struct amFile * \fImediaFile\fR, struct dbprocess * \fIdbproc\fR )
.TP 7n
int
amFileUpdate( AM_FU_COMPLETE_ARCH, struct dbprocess * \fIdbproc\fR, 
int \fImediaRequestId\fR, char * \fImediaUnitName\fR, char * \fIsourceId\fR )
.TP 7n
int
amFileUpdate( AM_FU_COMPLETE_USER,
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR )
int
amFileUpdate( AM_FU_MEDIA_Q_ROLLBACK,
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR,
char * \fImediaUnitName\fR )
.TP 7n
int
amGet( AM_MG_ALL | AM_MG_NEXT | AM_MG_NOTIFIABLE, 
struct amMedia * \fImedia\fR, 
struct dbprocess * \fIdbproc\fR  )
.TP 7n
int
amGet( AM_MG_MEDIA_REQUEST_ID, struct amMedia * \fImedia\fR, 
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR  )
.TP 7n
int
amGet( AM_MG_MEDIA_REQUEST_NAME, struct amMedia * \fImedia\fR, 
struct dbprocess * \fIdbproc\fR, char * \fImediaRequestName\fR )
.TP 7n
int
amGet( AM_MG_SOURCE_ID, struct amMedia * \fImedia\fR, 
struct dbprocess * \fIdbproc\fR, char * \fIsourceId\fR )
.TP 7n
int
amGet( AM_MG_STATUS, struct amMedia * \fImedia\fR, 
struct dbprocess * \fIdbproc\fR, char \fIstatus\fR )
.TP 7n
int
amIngestGet( char ** \fImediaIngestScript\fR )
.TP 7n
int
amInit( void )
.TP 7n
int
amMediaIdGet( int * \fImediaRequestId\fR, struct dbprocess * \fIdbproc\fR)
.TP 7n
int
amMediaTypeGet( AM_TG_ALL | AM_TG_NEXT,
struct amMediaType * \fImediaType\fR, struct dbprocess * \fIdbproc\fR )
.TP 7n
int
amMediaTypeGet( AM_TG_TYPE, struct amMediaType * \fImediaType\fR, 
struct dbprocess * \fIdbproc\fR, char * \fImediaType\fR )
.TP 7n
int
amMSBook( struct amMedStage * \fImediaStage\fR, 
struct dbprocess *  \fIdbproc\fR)
.TP 7n
int
amMSClear( struct amMedStage * \fImediaStage\fR, 
struct dbprocess *  \fIdbproc\fR)
.TP 7n
int
amMSGet( AM_SG_NEXT | AM_SG_ALL, struct amMedStage * \fImediaStage\fR, 
struct dbprocess *  \fIdbproc\fR )
.TP 7n
int
amMSGet( AM_SG_DIRECTORY, struct amMedStage * \fImediaStage\fR, 
struct dbprocess *  \fIdbproc\fR, char * \fstagingDirectory\fR)
.TP 7n
int
amMSGet( AM_SG_REQUEST_ID_NAME, struct amMedStage * \fImediaStage\fR, 
struct dbprocess *  \fIdbproc\fR, int \fImediaRequestId\fR,
char * \fImediaUnitName\fR)
.TP 7n
int
amNotifiable( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
char * \fImediaRequestType\fR, boolean * \fIreturnValue\fR )
.TP 7n
int
amNumCleanupable( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
int * \fRreturnValue\fR )
.TP 7n
int
amNumCopiesWritten( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
char * \fImediaUnitName\fR, int * \fIreturnValue\fR )
.TP 7n 
int
amNumOnUnit( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
char * \fImediaUnitName\fR, int * \fIreturnValue\fR )
.TP 7n
int
amNumPreparable( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
int * \fIreturnValue\fR )
.TP 7n
int
amNumWriteable( struct dbprocess * \fIdbproc\fR, in \fImediaRequestId\fRt, 
int * \fIreturnValue\fR )
.TP 7n
int
amPrecisionGet( int * \fIreturnValue\fR )
.TP 7n
int
amPrepared( struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
char * \fImediaUnitName\fR, boolean * \fRreturnValue\fR )
.TP 7n
int
amPut( AM_MEDIA * \fImedia\fR, struct dbprocess * \fIdbproc\fR )
.TP 7n
int
amScript( char * \fImediaType\fR, AM_SCRIPT_TYPE \fIselectType\fR, 
char ** \fIscriptName\fR, char ** \fIconfigFile\fR )
.TP 7n
int
amStatusStr( struct dbprocess * \fIdbproc\fR, char *\fIreturnString\fR , 
char * \fItableName\fR, char \fIstatusValue\fR )
.TP 7n
int
amUnitDelete( AM_UNIT * \fImediaUnit\fR, struct dbprocess * \fIdbproc\fR )
.TP 7n
int
amUnitGet( AM_UG_MEDIA_REQUEST_ID, struct amUnit* \fImediaUnit\fR, 
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR )
.TP 7n
int
amUnitGet( AM_UG_MEDIA_REQUEST_ID_LAST, struct amUnit* \fImediaUnit\fR, 
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR,
char * \fImediaUnitNameRoot\fR )
.TP 7n
int
amUnitGet( AM_UG_MEDIA_REQUEST_ID_NAME, struct amUnit* \fImediaUnit\fR, 
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR,
char * \fImediaUnitName\fR )
.TP 7n
int
amUnitGet( AM_UG_MEDIA_UNIT_NAME, struct amUnit* \fImediaUnit\fR, 
struct dbprocess * \fIdbproc\fR, char * \fImediaUnitName\fR )
.TP 7n
int
amUnitGet( AM_UG_NEXT, struct amUnit* \fImediaUnit\fR, 
struct dbprocess * \fIdbproc\fR )
.TP 7n
int
amUnitGet( AM_UG_NOTIFIABLE, struct amUnit* \fImediaUnit\fR, 
struct dbprocess * \fIdbproc\fR, struct media * \fImedia\fR )
.TP 7n
int
amUnitGet( AM_UG_STATUS, struct amUnit* \fImediaUnit\fR, 
struct dbprocess * \fIdbproc\fR, char \fIstatus\fR )
.TP 7n
int
amUnitGet( AM_UG_STATUS_AFTER_NAME, struct amUnit* \fImediaUnit\fR, 
struct dbprocess * \fIdbproc\fR, int \fImediaRequestId\fR, 
char \fIstatus\fR, char * \fIpattern\fR, char * \fImediaUnitNameRoot\fR )
.TP 7n
int
amUnitPut( AM_UNIT * \fImediaUnit\fR, struct dbprocess * \fIdbproc\fR )
.TP 7n
int
amUnitUpdate( AM_UU_COMPLETE_USER, struct dbprocess * \fIdbproc\fR, 
int \fImediaRequestId\fR )


.SH TYPE DEFINITIONS
The following simple, enumerated, and structure data types are defined 
in the 
.B am.h 
header file.
.PP
.ti 2
.BR SIMPLE
.Ty
AMF_DONE 
Media file state which indicates that 1 file has been fully processed.
.Ty
AMF_ERROR
Media file state which indicates that there is something wrong with a
file.
.Ty
AMF_RETRIEVED
Media file state which indicates that a file has been retrieved, and is
ready for processing.
.Ty
AMF_UNAVAILABLE
Media file state which indicates that a file is no longer available.
.Ty
AMF_UNPROCESSED
Media file state which indicates that no processing has begun on a
file.
.Ty
AMM_CREATING
Media state which indicates that a media request is being created.
.Ty
AMM_DONE
Media state which indicates that a media request have been fully
processed.
.Ty
AMM_ERROR
Media state which indicates that a media request has encountered
an error during processing.
.Ty
AMM_IN_PROG
Media state which indicates that a media request is currently 
being processed.
.Ty
AMU_CLEANED_UP
Media unit state which indicates that the unit has been cleaned up.
.Ty
AMU_DONE
Media unit state which indicates that the unit has been fully processed.
.Ty
AMU_PREPARED
Media unit state which indicates that the unit has been prepared.
.Ty
AMU_QUEUED
Media unit state which indicates that the unit has been queued.
.Ty
AMU_QUEUEING
Media unit state which indicates that the unit is being queued.
.Ty
AMU_WRITTEN
Media unit state which indicates that all copies of the unit have been 
written.
.Ty
AM_DEVICE_NAME_LEN
This is the maximum length of a device character string.
.Ty
AM_DRIVER_NAME_LEN
This is the maximum length of a device driver request name character string.
.Ty
AM_DEV_INFO_LEN
This is the maximum length of a device information character string.
.Ty
AM_FILE_ID_LEN
This is the maximum length of a file identifier character string.
.Ty
AM_FILE_NAME_LEN
This is the maximum length of a file name character string.
.Ty
AM_LOGICAL_DEV_NAME_LEN
This is the maximum length of a logical device name character string.
.Ty
AM_MEDIA_REQUEST_NAME_LEN
This is the maximum length of a media request name character string.
.Ty
AM_MEDIA_REQUEST_TYPE_LEN
This is the maximum length of a media request type character string.
.Ty
AM_MEDIA_TYPE_LEN
This is the maximum length of a media type character string.
.Ty
AM_MEDIA_UNIT_NAME_LEN
This is the maximum length of a media unit name character string.
.Ty
AM_MSTAGE_DIR_LEN
This is the maximum length of a staging directory character string.
.Ty
AM_PROC_NAME_LEN
This is the maximum length of a procedure name character string.
.Ty
AM_RT_ARCHIVE
Defines the media request archive type.
.Ty
AM_RT_USER
Defines the media request user type.
.Ty
AM_SOURCE_ID_LEN
This is the maximum length of a source identifier character string.
.Ty
AM_STATUS_SHORT_LEN
This is the maximum length of a short status message.
.Ty
AM_UNIT_NAME_ROOT_LEN
This is the maximum length of a media unit name root character string.

.PP
.ti 2
.BR ENUMERATED
.Ty
AM_DEVICE_CLEAR
An enumerated type used to indicate whether a device, a logical device,
or all devices should be cleared; made available.
The members of this type are:
.Td
AM_DC_ALL	/\(** All devices.	\(**/
AM_DC_LOGICAL	/\(** Matching a logical device name.	\(**/
AM_DC_DEVICE	/\(** Matching a given device name.	\(**/
.Ty
AM_DEVICE_GET
An enumerated type used to indicate the type of search that is to
be performed on the database for devices.  The members of this type 
are:
.Td/\(**
AM_DG_ALL	/\(** All devices.	\(**/
AM_DG_NAME	/\(** Match given device name.	\(**/
AM_DG_NAME_TYPE	/\(** Match given device name and	\(**/ 
	/\(** media type.	\(**/
AM_DG_NEXT	/\(** Next device, if  more than one.	\(**/
AM_DG_TYPE	/\(** Match given media type.	\(**/
.Ty
AM_FILE_GET 
An enumerated type to indicate which type of 'get' query to submit on the 
database's media_files table.  The members of this type are:
.Td
AM_FG_FILE_ID	/\(** Match given file ID.	\(**/
AM_FG_MEDIA_ID_FNAME	/\(** Match given file name.	\(**/
AM_FG_FNAME	/\(** Match given file name.	\(**/
AM_FG_MEDIA_FILE	/\(** Match given media request	\(**/
	/\(** and file IDs. \(**/
AM_FG_MEDIA_REQUEST_ID	
	/\(** Match given media request ID.	\(**/
AM_FG_MEDIA_UNIT	/\(** Match given media unit name	\(**/
	/\(** and media request ID.	\(**/
AM_FG_MEDIA_UNIT	/\(** Match given media unit.	\(**/
AM_FG_MEDIA_UNIT_ID	/\(** Match given media unit name and	\(**/
	/\(** and media request ID.	\(**/
AM_FG_NEXT	/\(** Next file, if more than one.	\(**/
AM_FG_QUEUEABLE	/\(** All files ready for queuing and	\(**/
	/\(** matching a request ID.	\(**/
AM_FG_RETRIEVABLE	/\(** All files need retrieving and	\(**/
	/\(** matching a request ID.	\(**/
AM_FG_SOURCE_ID	/\(** Match given source ID.	\(**/
AM_FG_STATUS	/\(** Match given status value.	\(**/
AM_FG_UNIT_FNAME	/\(** Match given media unit name, 	\(**/
	/\(** request ID, and file name.	\(**/
AM_FG_UNWRITTEN	/\(** Match a given request ID and 	\(**/
	/\(** have not been written.	\(**/
.Ty
AM_FILE_UPDATE 
An enumerated type to indicate which type of 'update' query to submit on the 
database's media_files table.  The members of this type are:
.Td
AM_FU_COMPLETE_ARCH	
	/\(** Set archive request to `done'.	\(**/
AM_FU_COMPLETE_USER	
	/\(** Set user request to `done'.	\(**/
AM_FU_MEDIA_Q_ROLLBACK	
	/\(** Dequeue a file from media unit.	\(**/
AM_FU_WRITTEN	/\(** Mark file as written
.Ty
AM_MEDIA_GET 
An enumerated type to indicate which type of 'get' query to submit on the 
database's media table. The members of this type are:
.Td
AM_MG_ALL	/\(** All media.	\(**/
AM_MG_MEDIA_REQUEST_ID	
	/\(** Match given request ID.	\(**/
AM_MG_MEDIA_REQUEST_NAME	
	/\(** Match given request name.	\(**/
AM_MG_NOTIFIABLE	/\(** All `notifiable' media.	\(**/
AM_MG_NEXT	/\(** Next media, if more than one.	\(**/
AM_MG_SOURCE_ID	/\(** Media with given source.	\(**/
AM_MG_STATUS	/\(** Media with given status.	\(**/
.Ty 
AM_SCRIPT_TYPE
An enumerated type used to indicate whether the script information for
preparing or writing is desired.  The members of this type are:
.Td
AM_ST_PREP	/\(** Get script details for prep script.	\(**/
AM_ST_WRITE	/\(** Get script details for write script.	\(**/
.Ty
AM_STAGE_GET
An enumerated type which is used to indicate what information is used to
query the database when `getting' information on media staging 
directories.  The members of this type are:
.Td
AM_SG_ALL	/\(** All staging directories.	\(**/
AM_SG_DIRECTORY	/\(** Match given staging directory.	\(**/
AM_SG_NEXT	/\(** Next staging directory.	\(**/
AM_SG_REQUEST_ID_NAME	
	/\(** Match given media request ID	\(**/
	/\(** and unit name.	\(**/
.Ty
AM_TYPE_GET
An enumerated type which is used to indicate/specify the type of database
query performed when `getting' media type information. The members of this
type are:
.Td
AM_TG_ALL	/\(** All media types
AM_TG_NEXT	/\(** Next media type, if more than one
AM_TG_TYPE	/\(** Match a given media type
.Ty
AM_UNIT_GET 
An enumerated type to indicate which type of 'get' query to submit on the 
database's media_units table.  The members of this type are:
.Td
AM_UG_MEDIA_REQUEST_ID	
	/\(** Match given media request ID.	\(**/
AM_UG_MEDIA_REQUEST_ID_LAST	
	/\(** Last media unit that matches	\(**/
	/\(** given request ID.	\(**/
AM_UG_MEDIA_REQUEST_ID_NAME
	/\(** Match given media request ID	\(**/
	/\(** and unit name.	\(**/
AM_UG_MEDIA_UNIT_NAME	/\(** Match given media unit name	\(**/
AM_UG_NEXT	/\(** Next unit, if more than one.	\(**/
AM_UG_NOTIFIABLE 	/\(** Determine if unit is cleaned up.	\(**/
AM_UG_STATUS	/\(** Match a given status value.	\(**/
AM_UG_STATUS_AFTER_NAME	
	/\(** Units after a given media unit	\(**/
	/\(** that match  given media ID and.	\(**/
	/\(** status value.	\(**/
.Ty
AM_UNIT_UPDATE 
An enumerated type to indicate which type of 'update' query to submit on the 
database's media_units table.  The members of this type are:
.Td
AM_UU_COMPLETE_USER	/\(** Set user media request as complete.	\(**/
.PP
.ti 2
.BR STRUCTURE
.Ty
AM_DEVICE
A structure containing information which describes a device which may
be used to create physical medium.  The information includes
whether or not the device is busy.  The members of the structure are:
.Ss
char	amdDeviceName[AM_DEVICE_NAME_LEN];
		/\(** Device name.	\(*\(**/
char	amdDeviceDriver[AM_DRIVER_NAME_LEN];
		/\(/\(** Device driver.	\(*\(**/
char	amdDeviceInfo[AM_DEV_INFO_LEN];
		/\(** Device information.	\(*\(**/
char	amdType[AM_MEDIA_TYPE_LEN];
		/\(** Type of device.	\(*\(**/
int	amdRSpeed;	/\(** Read speed.	\(*\(**/
int	amdWSpeed;	/\(** Write speed.	\(*\(**/
boolean	amdOnline;	/\(** TRUE if device is on-line.	\(*\(**/
boolean	amdInUse;	/\(** TRUE means in use.	\(*\(**/
pid_t	amdProcessId;	/\(** Process ID using device.	\(*\(**/
char	amdProcessName[AM_PROC_NAME_LEN];
		/\(** Name of process using dev.	\(*\(**/
int	amdMediaRequestId;
		/\(** Media request ID.	\(*\(**/
char	amdMediaUnitName[AM_MEDIA_UNIT_NAME_LEN];
		/\(** Media unit name.	\(*\(**/
 time_t	amdTimeStamp;	/\(** Time when booked.	\(*\(**/
.Ty
AM_FILE
A structure containing information pertinent to a file in
the Media Archive database tables for the purposes of being written 
to physical medium. The members of the structure are:
.Ss
boolean	amfCompressionFlag;	
		/\(** Compression flag.	\(**/
time_t	amfDateNotified;
		/\(** Date notified.	\(**/
char	amfFileId[AM_FILE_ID_LEN];	
		/\(** File id.	\(**/
int	amfFileSize;	/\(** File size (Actual).	\(**/
char	amfFilename[AM_FILE_NAME_LEN];	
		/\(** File name.	\(**/
int	amfMediaRequestId;	
		/\(** Media request id.	\(**/
char	amfMediaUnitName[AM_MEDIA_UNIT_NAME_LEN];	
		/\(** Media unit name.	\(**/
char	amfSourceId[AM_SOURCE_ID_LEN];	
		/\(** Source id.	\(**/
char	amfStatus;	/\(** Status.	\(**/
int	amfUncompFileSize;	
		/\(** Uncompressed file size.	\(**/
.Ty
AM_MEDIA
A structure containing information which describes either a user or
archive media request. The members of the structure are:
.Ss
time_t	ammDateCompleted;	
		/\(** Date completed.	\(*\(**/
time_t	ammDateRequested;
		/\(** Date requested.	\(*\(**/
int	ammMediaRequestId;
		/\(** Media request ID.	\(*\(**/
char	ammMediaRequestName[AM_MEDIA_REQUEST_NAME_LEN];
		/\(** Media request name.	\(*\(**/
char	ammMediaRequestType[AM_MEDIA_REQUEST_TYPE_LEN];
		/\(** Type of request.	\(*\(**/
char	mmMediaType[AM_MEDIA_TYPE_LEN];
		/\(** Type of media.	\(*\(**/
int	ammNumCopies;	/\(** # of copies to make.	\(*\(**/
char	ammUnitNameRoot[AM_UNIT_NAME_ROOT_LEN];
		/\(** Root of unit names.	\(*\(**/
int	ammUnitNamePrecision;
		/\(** # of digits appended to the	\(*\(**/
		/\(** Unit Name Root.	\(*\(**/
char	ammSourceId[AM_SOURCE_ID_LEN];	
		/\(** ID of source of request.	\(*\(**/
char	ammStatus;	/\(** Status in media table.	\(*\(**/
.Ty
AM_MED_SCRIPT
A structure containing information pertinent to the scripts which are
used to prepare and write physical mediums. The members of the structure
are:
.Ss
char	*amsPrepScript;	
		/\(** Preparation script name.	\(**/
char	*amsPrepFile;	/\(** Preparation file name.	\(**/
char	*amsWriteScript;
		/\(** Write script name.	\(**/
char	*amsWriteFile;
		/\(** Write file name.	\(**/
char	amsTypeName[AM_MEDIA_TYPE_LEN];
		/\(** Name of Media Type.	\(**/
.Ty
AM_MED_TYPE
A structure containing information pertinent to a physical medium type
such as CD\-ROM or Tape.
The members of the structure are:
.Ss
int	amtBlockSize;	/\(** Min. block size of Med. Type.	\(**/
int	amtDirOverh;	/\(** Directory overhead.	\(**/
int	amtFileOverh;	/\(** File overhead.	\(**/
int	amtMaxSize;	/\(** Maximum Size of Media Type.	\(**/
int	amtSplitSize;	/\(** Min. split size.	\(**/
float	amtThreshold;	/\(** Full Threshold of Media Type.	\(**/
char	amtTypeName[AM_MEDIA_TYPE_LEN];
		/\(** Name of Media Type.	\(**/
.Ty
AM_MSTAGE
A structure containing information which is pertinent to media staging
directories.  The media staging directories are the locations on magnetic
disk where media is prepared before it is written to a physical medium.
The members of the structure are:
.Ss
char	amsDirectory[AM_MSTAGE_DIR_LEN];
		/\(** Media stage dir name.	\(**/
int	amsMediaRequestId;	
		/\(** Media request id.	\(**/
char	amsMediaUnitName[AM_MEDIA_UNIT_NAME_LEN];
		/\(** Media unit name.	\(**/
.Ty
AM_UNIT
A structure containing information pertinent to a media unit - a group of
files which will be put onto one instance of physical medium. For example,
a group of files to be placed onto a single CD-ROM is called a media unit. 
The members of the structure are:
.Ss
int	amuCopiesWritten;
		/\(** Num copies written.	\(**/
time_t	amuDateCompleted;
		/\(** Date completed.	\(**/
int	amuMediaRequestId;
		/\(** Media request id.	\(**/
char	amuMediaUnitName[AM_MEDIA_UNIT_NAME_LEN];
		/\(** Media unit name.	\(**/
char	amuStatus;	/\(** Status.	\(**/
int	amuTotalSize;	/\(** Total size.	\(**/
int	amuUncompSize;
		/\(** Uncompressed size.	\(**/

.SH DESCRIPTION
The am library provides an interface to the Archive Media database 
and configurable parameters. The intended use for the Archive Media 
database and library (AM) is to aid in the creation of physical media.

The library has its own configuration file,
.I libam.config,
which contains all required configuration information.

The various library functions are briefly described below:
.Ty
amActionAdd()
This function adds an action to the 
.B media_actions
table. The action should
be one of: AM_MA_INGEST, AM_MA_UNINGEST, AM_MA_QUEUE, AM_MA_UNQUEUE, 
AM_MA_PREPARE, AM_MA_UNPREPARE, AM_MA_WRITE, AM_MA_UNWRITE, AM_MA_CLEANUP,
or AM_MA_UNCLEANUP. The media unit name may be null.
.Ty
amActionDelete()
This function removes all actions associated with the media request id and
media unit name from the 
.B media_actions 
table. The media unit name may be null.
.Ty
amAmountOnUnit()
Determine the number of kilobytes of data on a given media unit.
.Ty
amAmountQueueable()
Determine the number of kilobytes of data that is ready for queuing
for a particular media request.
.Ty
amAmountRetrievable()
Determine the number of kilobytes of data that is ready for retrieval 
for a particular media request.
.Ty
amCleanedUp()
Determine if a media unit has been cleaned up.
.Ty
amClose()
Free up local 
.B am 
structures and close the library.
.Ty
amDataStageGet()
Fetch the configured paths to the 
.B am 
data stage directories; user data stage, archive data stage,
and media data stage.
.Ty
amDbInfoGet()
Fetch information about the databases that 
.B am 
is using. 
.Ty
amDeviceBook()
Book a device, mark the device as busy, in the bookDevice table.
.Ty
amDeviceClear()
Free a device, mark the device as not busy, in the bookDevice table.
.Ty
amDeviceGet()
Fetch information describing a device(s). The information is composed
from the devices and bookDevice tables.
.Ty
amDeviceLookup()
Fetch all devices that are associated with a given logical device name.
The information is composed
from the devices and bookDevice tables.
.Ty
amFileDelete() 
Delete a file from the database's media_files table.
.Ty
amFileGet() 
Fetch information from the database's media_files table. 
.Ty
amFilePut()
Add information to the database's media_files table.
.Ty
amFileUpdate()
Update one or more tuples in the database's media_files table.
.Ty
amGet()
Fetch information from the database's media table. 
.Ty
amIngestGet()
Fetch the script name, from
.B am's
configuration file, which is to be used by
.B mediaIngest
for computing uncompressed file sizes.
.Ty
amInit()
Initialize the am library. Configuration and local structure allocation 
takes place in this routine. 
.Ty
amMediaIdGet()
Fetch a new media ID from the database's keys table. 
.Ty
amMedTypeGet()
Fetch information from the 
.B am's 
mediaTypes table which describes the various physical medium to 
be used.
.Ty
amMSBook()
Book a media staging area for the preparation of a physical media.  This
function alters the media stages table.
.Ty
amMSClear()
Release a media staging area which was used to prepare and write a physical 
media.  This function alters the media stages table.
.Ty
amMSGet()
Fetch information from the database's media_stages table. 
.Ty
amNotifiable()
Determine if a given media request is ready to notify its source that the
request has been completed.  An archive request is `notifiable' when there
is one or more media units which have been written and cleaned up.  An
user request is `notifiable' when all files have been written to a physical
media and all media units are cleaned up. 
.Ty
amNumCleanupable()
Determine the number of media units for a given media request that can be 
cleaned up, or those that have been written.
.Ty
amNumCopiesWritten()
Determine the number of copies of a given media unit that have been written
onto a physical medium.
.Ty
amNumOnUnit()
Determine the number files on a given media unit.
.Ty
amNumPreparable()
Determine the number of media units for a given media request that are ready
for preparation.
.Ty
amNumWriteable()
Determine the number of media units that are ready for writing.
.Ty
amPrecisionGet()
Fetch the default unit name precision value from
.B am's
configuration file.
.Ty
amPrepared()
Determine whether or not a given media unit has been prepared.
.Ty
amPut()
Add information to the database's media table.
.Ty
amScript()
Fetch the name of the write or prepare  script and configuration 
file to be used from 
.B am's
configuration file.
.Ty
amStatusStr()
Return a string which describes a valid am status. 
.Ty
amUnitDelete()
Remove information from the datbase's media_units table. 
.Ty
amUnitGet()
Fetch information from the database's media_units table. 
.Ty
amUnitPut()
Add information to the database's media_units table. 


.SH FILES
.SS libAm.config
The 
.B am 
library requires a configuration file which contains information 
about the Archive Media tables used by the library, and regarding data staging
areas on disk, and physical medium types.  The file should be named
.I libAm.config
and located in a directory specified by a 
.B CONFIG_DIR 
environment variable ( see the
.B ENVIRONMENT VARIABLES
section )  The configuration file format is as follows:

.nf
.na
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 80n 88n 96n 104n 112n 120n

#
#   Data Stage Paths.
#
# Keyword	User			Archive			Media
# --------	----			-------			-----
#

dataStage	/staging/storage/user	/staging/storage/archive /staging/media


#
#  Request database parameters
#
#  Keywd  database  database	media	media_files	media_units	media_stages	status	media_actions
#	  server    table	table		table	  	table		table
#  -----  --------  --------	-----	-----------	-----------	------------	------	-------------
#

amDb	  SYBASE	am	media	media_files	media_units	media_stages	status	media_actions




#
#  Request device table parameters
#
#  Keywd	device		booking		logicalDevice	mediaTypes
#		table		table		table		table
#  -----	-----------	--------	-------------	----------
#

deviceTables	devices		bookDevice	logicalDevices	mediaTypes



#
#   Media scripts.
#
# Keyword  Media Type	Prep Script		Prep Config. File    Write Script	    Write Config. File
#--------  -----------	------------		-----------------    ------------	    ------------------
#

scripts	  TP		none		     	none		    tpWrite		     none
scripts	  CD            cdPrepRunMkisofs-111	mkisofs-111.config  cdWriteRunCdrecord-16    none
scripts	  VD		dvdPrepRunMkisofs-111	mkisofs-111.config  dvdWriteRunCdrecord-16   none



#
#   mediaIngest script name (This line is optional in the config file.
#   It is the script name for determining the uncompressed size of a file)
#
# Keyword  	Script Name
#--------  	-----------
#

ingestScript	mi_size	


#
#   media unit names have a numerical value appended to the unit name root.
#   This number is padded with 0's; the number of 0's depends on the 
#   precision value.  The precision value is normally obtained from the
#   media table, however, in order to provide backwards compatibility the
#   default, defined here, is used if no value is given.
#
# Keyword  		precision
#--------  		-----------
#

defaultPrecision	4


.ad
.fi

.SH TABLES
The following is a list of SYBASE tables that must be present for the
.B am
library to run correctly:
.TP
.B archiveMedia..bookDevice
.TP
.B archiveMedia..devices
.TP
.B archiveMedia..keys
.TP
.B archiveMedia..logicalDevices
.TP
.B archiveMedia..media
.TP
.B archiveMedia..mediaTypes
.TP
.B archiveMedia..media_files
.TP
.B archiveMedia..media_stages
.TP
.B archiveMedia..media_units
.TP
.B archiveMedia..status
.TP
.B archiveMedia..media_actions


.SH ENVIRONMENT VARIABLES
Environment variable 
.B LIBAM_CONFIG_DIR
can be set to the path of a directory containing the configuration file.  If 
.B LIBAM_CONFIG_DIR
is not set, the environment variable 
.B DEFAULT_CONFIG_DIR
should be set to a path where the configuration file can be found.

.SH BUGS
None known.

.SH AUTHORS
Steve Cockayne
.br 
Jennifer Dunn
.br
Shannon Jaeger
.br
Marc LeBlanc
.br


National Research Council of Canada 
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre

