#!/usr/bin/tcsh -f
#/*+
#************************************************************************
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#*
#* (c) 1998.				(c) 1998.
#* National Research Council		Conseil national de recherches
#* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
#* All rights reserved			Tous droits reserves
#* 					
#* NRC disclaims any warranties,	Le CNRC denie toute garantie
#* expressed, implied, or statu-	enoncee, implicite ou legale,
#* tory, of any kind with respect	de quelque nature que se soit,
#* to the software, including		concernant le logiciel, y com-
#* without limitation any war-		pris sans restriction toute
#* ranty of merchantability or		garantie de valeur marchande
#* fitness for a particular pur-	ou de pertinence pour un usage
#* pose.  NRC shall not be liable	particulier.  Le CNRC ne
#* in any event for any damages,	pourra en aucun cas etre tenu
#* whether direct or indirect,		responsable de tout dommage,
#* special or general, consequen-	direct ou indirect, particul-
#* tial or incidental, arising		ier ou general, accessoire ou
#* from the use of the software.	fortuit, resultant de l'utili-
#* 					sation du logiciel.
#*
#************************************************************************
#*
#*   Script Name:	cdPrep/scripts/runGear
#*
#*   Purpose:
#*	Whatever
#*
#*   Date		: Feb 19, 1998
#*
#*   SCCS data		: @(#)
#*	Module Name	: prepRunGear-33
#*	Version Number	: 1.3
#*	Release Number	: 1
#*	Last Updated	: 05/05/98
#*
#*   Programmer		: Shannon Jaeger
#*
#*   Modification History:
#*	98/02/19 SDJ  :	Copied from runGear-33 script in cdMake (vlt project)
#*	98/02/19 SDJ  :	Made modification so script works with cdPrep
#*			and cdWrite
#*	98/04/30 SEC  :	Removed selvol command from command batch file.
#*	98/05/05 SEC  :	Script now removes two physical volume files if
#*			they exist.
#*	98/05/13 SEC  :	Script now handles directory trees.
#*	98/06/17 SEC  :	Script now handles spaces in filepaths. 
#*	98/12/15 SDJ  : Cosmetic changes and moved removal of old files
#*			to first item done.
#*	99/02/24 SDJ  : Data directory now expected to be prepared
#*			instead of preparing it.  Consequently logic
#*			and command line args changed.
#*	99/03/14 SDJ  :	Added more informative error messages.
#*	99/03/25 SDJ  : Use find instead of ls to determine the number of
#*			files in the data directory.
#*	99/04/07 SDJ  : Added support for relative paths.
#*			Added more useful error reporting.
#*	99/04/15 SDJ  : Added -x flag to csh
#*	99/04/29 SDJ	: Fixed relative path code.
#*
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#************************************************************************
#-*/

umask 002

set exec_name = $0
set exec_name = $exec_name:t
echo "cdPrepRunGear-33"
sleep 5

#
# Parse command line.
#

if ( $#argv != 5 ) then
    goto usage
endif

set volume_name = $1
set gearrc_dot_file_path = $2
set log_file_path = $3
set gear_work_path = $4
set retrieval_link_path = $5

set batch_file = command.bat
set gearrc_file = .gearrc

set noglob

#
# Check for relative paths
#

set current_dir = `pwd`
set result = `echo $gearrc_dot_file_path | grep "^/.*"`
if ( "$result" == "" ) then
    set gearrcs_dot_file_path = "$current_dir/$gearrc_dot_file_path"
endif

set result = `echo $log_file_path | grep "^/.*"` 
if ( "$result" == "" ) then
    set log_file_path = "$current_dir/$log_file_path"
endif

set result = `echo $retrieval_link_path | grep "^/.*"`
if ( "$result"  == "" ) then
    set retrieval_link_path = "$current_dir/$retrieval_link_path"
endif



#
#  Go to the gear work path.
#
 
cd $gear_work_path
if ( $status ) then
    echo Error: Unable to change to directory \'$gear_work_path\' 
    sleep 10
    exit 1
endif

#
#  Remove any gearrc, batch and log files, and physical volume files 
#  if present.
#
 
if ( -e $log_file_path ) then
    rm -f $log_file_path
    if ( $status ) then
	echo Error: Unable to remove \'$log_file_path\' 
	sleep 10
        exit 1
    endif
endif

if ( -e $gearrc_file ) then
    rm -f $gearrc_file
    if ( $status ) then
	echo Error: Unable to remove .gearrc file >> $log_file_path 
        exit 1
    endif
endif
 
if ( -e $batch_file ) then
    rm -f $batch_file
    if ( $status ) then
	echo Error: Unable to remove \`$batch_file\' file >> $log_file_path 
        exit 1
    endif
endif
 
#
#  Create the new gearrc and batch files
#

if ( $gearrc_dot_file_path != "none" ) then
    cp $gearrc_dot_file_path $gearrc_file
    if ( $status ) then
	echo "Error: Unable to copy .gearrc file" >> $log_file_path
        exit 1
    endif
endif


cat > $batch_file << _EOF_
log $log_file_path
_EOF_
if ( $status ) then
    echo Error: Unable to create batch file \'$batch_file\' >> $log_file_path
    exit 1
endif

if ( -e $volume_name.vol ) then
cat >> $batch_file << _EOF_
delvol $volume_name
_EOF_
    if ( $status ) then
	echo Error: Unable to create batch file \'$batch_file\' >> $log_file_path
	exit 1
    endif
endif



cat >> $batch_file << _EOF_
newvol $volume_name 74 ISO
cp -r $retrieval_link_path
physvol
exit
_EOF_
if ( $status ) then
    echo Error: Unable to create batch file \'$batch_file\' >> $log_file_path
    exit 1
endif

 
#
#  Disable interrupts.
#
 
#onintr -

#
#  Run gear.
#

which gear >> $log_file_path
if ( $status ) then
    echo "Error: Unable to find gear." >> $log_file_path
endif

echo "***     Creating physical volume with gear     ***"
gear $batch_file

 
#
#  Parse the log file and add to it the number of copies, number of 
#  of errors, number of files copied..
#

echo "***            Checking for errors             ***"
/usr/bin/echo "\007"
sleep 10
if ( -e $log_file_path ) then
    set num_images = `grep ';Physical volume image(s) created\.' $log_file_path | wc -l`
    set num_errors = `grep '^;ERROR:' $log_file_path | wc -l`
    set num_files_copied = `grep '^;Successfully loaded as' $log_file_path | wc -l`
else
    set num_images = 0
    set num_errors = 0
    set num_files_copied = 0
endif
set num_files = `find $retrieval_link_path -type f | wc -l`
if ( $status ) then
    echo "Error: Unable to determine number of files to used." >> $log_file_path
    exit 1
endif


echo "$exec_name - Number of images:            $num_images" >> $log_file_path
echo "$exec_name - Number of errors:            $num_errors" >> $log_file_path
echo "$exec_name - Number of files found:       $num_files" >> $log_file_path
echo "$exec_name - Number of files prepared:    $num_files_copied" >> $log_file_path


#
#  If no problems thus far, remove link directory structure. 
#

if ( $num_images > 0 && $num_errors == 0 && $num_files == $num_files_copied ) then 
    echo ""
    echo "***  Completed preparing GEAR physical volume  ***"
    echo "cdPrepRunGear-33 done"
    echo " "
    exit 0
else
    echo "***    Did NOT create GEAR physical volume     ***"
    echo "cdPrepRunGear-33 done"
    echo " "
    exit 1
endif    


#
# Display usage Information.
#

usage:
    echo "USAGE: cdPrepRunGear-33 <volume_name> <gear_dot_file> <log_file_path> <gear_work_path> <data_path>" 
    echo ""	
    echo "              volume name:      Name of disk in upper-case"
    echo "              gear_dot_path:    Fully specified path and name of the"
    echo "                                .gearrc file"
    echo "              log_file_path:    Fully specified path and name of log file"
    echo "              gear_work_path:   Fully specified path to the work directory"
    echo "              data_path:        Fully specified path to the directory that will"
    echo "                                containing the data."
 exit 1
