#!/bin/csh -f
#/*+
#************************************************************************
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#*
#* (c) 1998.				(c) 1998.
#* National Research Council		Conseil national de recherches
#* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
#* All rights reserved			Tous droits reserves
#* 					
#* NRC disclaims any warranties,	Le CNRC denie toute garantie
#* expressed, implied, or statu-	enoncee, implicite ou legale,
#* tory, of any kind with respect	de quelque nature que se soit,
#* to the software, including		concernant le logiciel, y com-
#* without limitation any war-		pris sans restriction toute
#* ranty of merchantability or		garantie de valeur marchande
#* fitness for a particular pur-	ou de pertinence pour un usage
#* pose.  NRC shall not be liable	particulier.  Le CNRC ne
#* in any event for any damages,	pourra en aucun cas etre tenu
#* whether direct or indirect,		responsable de tout dommage,
#* special or general, consequen-	direct ou indirect, particul-
#* tial or incidental, arising		ier ou general, accessoire ou
#* from the use of the software.	fortuit, resultant de l'utili-
#* 					sation du logiciel.
#*
#************************************************************************
#*
#*   Script Name:	cd/scripts/writeRunGear-33
#*
#*   Purpose:
#*	Whatever
#*
#*   Date		: Feb 19, 1998
#*
#*   SCCS data		: @(#)
#*	Module Name	: cdWriteRunGear-33
#*	Version Number	: 1.11
#*	Release Number	: 1
#*	Last Updated	: 05/04/99
#*
#*   Programmer		: Shannon Jaeger
#*
#*   Modification History:
#*	98/02/19 SDJ  :	Copied from runGear-33 script in cdMake (vlt project)
#*	98/02/20 SDJ  :	Made modification so script works with cdPrep
#*			and cdWrite
#*	98/04/30 SEC  :	Removed selvol command from command batch file.
#*	98/06/17 SEC  :	Added umask 002.
#*	98/12/14 SDJ  : Added device information to script and
#*			looping until all copies are made.
#*  	99/02/24 SDJ  : Script now expects the location of the data directory
#*			even though it isn't used, however, it will be used 
#*			by other write media scripts. Also changed logic.
#*			Multiple copies are handled inside of GEAR instead
#*			of the script.
#*	99/03/17 SDJ  : Added num-files argument.  Also fixed script, so
#*			multiple instances of this script can work on the
#*			same volume in the same staging directory.
#*	99/04/08 SDJ  : Added optional command-line arg, "-simulate".
#*	99/04/29 SDJ	: Fixed relative path code.
#*
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#************************************************************************
#-*/

umask 002

set exec_name = $0
set exec_name = $exec_name:t


#
# Parse command line.
#

if ( $#argv != 8 && $#argv != 9 ) then
   goto USAGE
endif

if ( $#argv == 9 && "$9" != "-simulate" ) then
    goto USAGE
else if ( $#argv == 9 ) then
    set simulate = 1
else
    set simulate = 0
endif


#
# Parse the arguments.
#

set volume_name = $1
set gearrc_dot_file_path = $2
set log_file_path = $3
set gear_work_path = $4
set dev_info = $5
set num_copies = $6
set num_files = $7  # note: this arg. is not used by this script.
set data_path = $8  # This argument is not used by this script.

set batch_file = "command.bat.$$"
set gearrc_file = .gearrc
set gear_home = "$gear_work_path/.gearrc.$$"


#
# Check for relative paths
#

set current_dir = `pwd`
set result = `echo $gearrc_dot_file_path | grep "^/.*"`
if ( "$result" == "" ) then
    set gearrc_dot_file_path = "$current_dir/gearrc_dot_file_path"
endif

set result = `echo $log_file_path | grep "^/.*"` 
if ( "$result" == "" ) then
    set log_file_path = "$current_dir/$log_file_path"
endif


set noglob

#
#  Go to the gear work path.
#
 
cd $gear_work_path
if ( $status ) then
    echo Error: Unable to change to directory \'$gear_work_path\'
    sleep 10
    exit 1
endif


#
#  Remove any gearrc, batch and log files if present.
#
 
if ( -e $log_file_path ) then
    rm -f $log_file_path*
    if ( $status ) then
	echo Error: Unable to remove file \'$log_file_path\'
	sleep 10
        exit 1
    endif
endif

if ( -e $gearrc_file ) then
    rm -f $gearrc_file
    if ( $status ) then
	echo Error: Unable to remove file \`$gearrc_file\` >> $log_file_path
        exit 1
    endif
endif

if ( -e $gear_home/$gearrc_file ) then
    rm -f $gear_home/$gearrc_file
    if ( $status ) then
	echo Error: Unable to remove file \`$gear_home/$gearrc_file\` >> $log_file_path
        exit 1
    endif
endif

if ( -e $batch_file ) then
    rm -f $batch_file
    if ( $status ) then
	echo Error: Unable to remove file \`$batch_file\` >> $log_file_path
        exit 1
    endif
endif
 

#
# Parse the device information to get the SCSI bus and target, the
# read speed, and write speed.
#

set bus = `echo $dev_info | awk 'BEGIN { FS="," ; } { print $2 }'`
if ( $status ) then
    echo "Error: Unable to parse device information" >> $log_file_path
    exit 1
endif
set target = `echo $dev_info | awk 'BEGIN { FS="," ; } { print $3 }'`
if ( $status ) then
    echo "Error: Unable to parse device information" >> $log_file_path
    exit 1
endif
set read_speed = `echo $dev_info | awk 'BEGIN { FS="," ; } { print $5 }'`
if ( $status ) then
    echo "Error: Unable to parse device information" >> $log_file_path
    exit 1
endif
set write_speed = `echo $dev_info | awk 'BEGIN { FS="," ; } { print $6 }'`
if ( $status ) then
    echo "Error: Unable to parse device information" >> $log_file_path
    exit 1
endif


#
#  Create the new gearrc and batch files
#

echo "mkdir $gear_home" >> $log_file_path
mkdir $gear_home
if ( $status ) then
    echo Error: Unable to create directory \'$gear_home\' >> $log_file_path
    exit 1
endif

set old_home = `echo $home`
set home = $gear_home 
if ( $status ) then
    echo "Error: Unable to change HOME environment variable"
    exit 1
endif

if ( "$gearrc_dot_file_path" != "none" ) then
    #
    # Set the SCSI Bus Id in the .gearrc file
    #

    cp $gearrc_dot_file_path $gear_home/$gearrc_file.tmp
    if ( $status ) then
       echo "Error: Unable to copy .gearrc to current directory." >> $log_file_path
       exit 1
    endif
    cat $gear_home/$gearrc_file.tmp | sed -e 's/SCSIBusID=.*/SCSIBusID='$bus'/g' >! $gear_home/$gearrc_file 
    if ( $status ) then
	echo "Error: Unable to edit .gearrc." >> $log_file_path
	exit 1
    endif


    #
    # Set the SCSI Target in the .gearrc file
    #

    cp $gear_home/$gearrc_file $gear_home/$gearrc_file.tmp
    if ( $status ) then
	echo "Error: Unable to copy .gearrc." >> $log_file_path
	exit 1
    endif
    cat $gear_home/$gearrc_file.tmp | sed -e 's/TargetID=.*/TargetID='$target'/g' >! $gear_home/$gearrc_file 
    if ( $status ) then
	echo "Error: Unable to edit .gearrc." >> $log_file_path
	exit 1
    endif


    #
    # Set the reading speed of the cd-writer in the .gearrc file
    #

    cp $gear_home/$gearrc_file $gear_home/$gearrc_file.tmp
    if ( $status ) then
	echo "Error: Unable to copy .gearrc." >> $log_file_path
	exit 1
    endif
    cat $gear_home/$gearrc_file.tmp | sed -e 's/ReadSpeed=.*/ReadSpeed='$read_speed'/g' >! $gear_home/$gearrc_file 
    if ( $status ) then
	echo "Error: Unable to edit .gearrc." >> $log_file_path
	exit 1
    endif


    #
    # Set the writing speed of the cd-writer in the .gearrc file
    #

    cp $gear_home/$gearrc_file $gear_home/$gearrc_file.tmp
    if ( $status ) then
	echo "Error: Unable to copy .gearrc." >> $log_file_path
	exit 1
    endif
    cat $gear_home/$gearrc_file.tmp | sed -e 's/WriteSpeed=.*/WriteSpeed='$write_speed'/g' >! $gear_home/$gearrc_file 
    if ( $status ) then
	echo "Error: Unable to edit .gearrc." >> $log_file_path
	exit 1
    endif


    #
    # Set writing off of on.
    #

    cp $gear_home/$gearrc_file $gear_home/$gearrc_file.tmp
    if ( $status ) then
	echo "Error: Unable to copy .gearrc." >> $log_file_path
	exit 1
    endif
    if ( $simulate ) then
	cat $gear_home/$gearrc_file.tmp | sed -e 's/WriteEnable.*/WriteEnable=FALSE/g' >! $gear_home/$gearrc_file 
	if ( $status ) then
	    echo "Error: Unable to edit .gearrc." >> $log_file_path
	    exit 1
	endif
    else
	cat $gear_home/$gearrc_file.tmp | sed -e 's/WriteEnable.*/WriteEnable=TRUE/g' >! $gear_home/$gearrc_file 
	if ( $status ) then
	    echo "Error: Unable to edit .gearrc." >> $log_file_path
	    exit 1
	endif
    endif

    rm -f $gear_home/$gearrc_file.tmp
endif


#
# Create batch file.
#

cat > $batch_file << _EOF_
log $log_file_path
_EOF_
if ( $status ) then
    echo "Error: Unable to create batch file." >> $log_file_path
    exit 1
endif

set i = 0
set num
while ( $i < $num_copies )
    cat >> $batch_file << _EOF_
writecd $volume_name
_EOF_
    if ( $status ) then
	echo "Error: Unable to create batch file." >> $log_file_path
	exit 1
    endif
    @ i += 1
end

cat >> $batch_file << _EOF_
exit
_EOF_
if ( $status ) then
    echo "Error: Unable to create batch file." >> $log_file_path
    exit 1
endif


 
#
#  Disable interrupts.
#
 
onintr -


#
#  Run gear.
#

which gear >> $log_file_path
if ( $status ) then
    echo "Error: Unable to find gear." >> $log_file_path
endif

echo Starting "gear $batch_file" `date`. >> $log_file_path
gear $batch_file
set home = $old_home 
/usr/bin/rm -r -f $gear_home $batch_file

 
#
#  Parse the log file and add to it the number of copies, number of 
#  of errors, number of files copied..
#

DONE: 
if ( -e $log_file_path ) then
    if ( $simulate ) then
	set num_copies = `grep ';Write test completed\.' $log_file_path | wc -l`
    else
	set num_copies = `grep ';Recording completed\.' $log_file_path | wc -l`
    endif

    set num_errors = `grep '^;ERROR:' $log_file_path | wc -l`
    set num_verify = `grep '^;ERROR: Verify errors have been detected\!' $log_file_path | wc -l`
    @ num_copies -= $num_verify
else
    set num_copies = 0
    set num_errors = 0
    set num_verify = 0
endif

echo "$exec_name - Number of copies:    $num_copies" >> $log_file_path
echo "$exec_name - Number of errors:    $num_errors" >> $log_file_path
echo "$exec_name - Number of verify:    $num_verify" >> $log_file_path
 
echo "**            writeRunGear-33 done             ***"
sleep 2
exit 0


#
# Display usage Information.
#

usage:
    echo "USAGE: runGear <volume_name> <gear_dot_file> <log_file_path> <gear_work_path> <device_info> <num_compies> <num_files> <data_path> [-simulate]"
    echo ""	
    echo "              volume name      -Name of disk in upper-case"
    echo "              gear_dot_file    -Fully specified path and name of .gearrc file"
    echo "              log_file_path    -Fully specified path and name of log file"
    echo "              gear_work_path   -Fully specified path to the work directory"
    echo "              device_info      -SCSI Bus, Target, Logical Unit Number."    
    echo "              num_copies       -Number of copies to make"
    echo "              num_files        -Number of files to put on the CD-ROM."
    echo "              data_path        -Fully specified path to the directory which"
    echo "                                contains the data to be written."
    echo "              [-simulate]      -Run in siumlation mode."

 exit 1
