.\"/*+
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"*	Name			: cd/doc/cdWriteRunCdrecord.1
.\"*
.\"*	Date			: Dec 15, 1998
.\"*
.\"*	SCCS data		: @(#)
.\"*	    Module Name		: cdWriteRunCdrecord.1
.\"*	    Version Number	: 1.5
.\"*	    Release Number	: 1
.\"*	    Last Updated	: 04/15/99
.\"*
.\"*	Written by		: Shannon Jaeger
.\"*
.\"*	Modification History:
.\"*        98/12/15 SDJ	: Copied from cdWriteRunGear.1
.\"*	    99/03/17 SDJ	: Added num-files argument.
.\"*	    99/04/08 SDJ	: Added option command-line arg. -simulate
.\"*				  and an example of its usage.
.\"*
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"************************************************************************
.\"-*/
.TH CDWRITERUNCDRECORD 1 08/04/99 "CADC"
 
.SH NAME
cdWriteRunCdrecord\-16
\- Runs \fBcdrecord\fR (version 1.6) to write CD\-ROM(s) from an image of a CD\-ROM on magnetic
disk.
 
.SH SYNOPSIS
.B cdWriteRunCdRecord\-16
.I volume\-name cdrecord\-config\-file log\-file\-path
.I work\-path device\-information num\-copies 
.I num\-files data\-path
[
.I -simulate
]


.SH DESCRIPTION
.B cdWriteRunCdrecord\-16
is a C\-shell script that uses \fBcdrecord\fR  to write one or more
copies of a CD\-ROM from a physical image on magnetic disk. 
.B cdrecord
is a free software package which is used to record data Compact
Discs.
This script assumes that a single CD\-writer is to be
used and that no stacker is used, so the operator must manually place
CD\-ROMs into the CD\-writer.

Depending on system configuration
.B cdrecord
may need to run as root.  An application such as
.B sudo
can be used to allow specific users to run 
.B cdrecord
as root.  This script assumes that 
.B sudo
is to be used on Sun/Solaris systems only.

This script parses the device specific information provided
by the
.I device\-information
command\-line parameter.  The only information that is used includes:
.RS 4
.nf
SCSI bus,
SCSI target,
SCSI logical unit number,
driver, and
write speed.
.fi
.RE
Additional device information is expected to be passed to the script
but it is not used.  It is expected in order to maintain compatibility
with other media writing scripts and in order to match the output from
.B mediaWrite.  
The device information used is passed on to 
.B cdrecord
to ensure the specified device is used.

This script was written to work with an applications such as
.B mediaWrite
which interfaces with a SYBASE database.

.SH OPERATION
.B cdWriteRunCdrecord\-16 
requires eight command\-line parameters:
.TP
.I volume\-name:      
Name of disk in upper\-case.
.TP
.I cdrecord\-config\-file:
Fully specified path and name of the cdrecord configuration file.  This
command\-line parameter was kept even though 
.I cdrecord
does not have a configuration file in order to maintain compatibility
with other scripts which write media.
.TP
.I log\-file\-path:    
Fully specified path and name of log file.
.TP
.I work\-path:   
Fully specified path to the work directory.  This directory contains
the physical image of the CD\-ROM to be written.
.TP
.I device\-information:
The device information includes the following: 
.TP
.RS 6
.nf
1. \fBdevice name\fR or mount point of the CD writer,
2. \fBSCSI bus\fR the CD\-writer is located on,
3. \fBSCSI target\fR number of the device,
4. \fBSCSI logical unit number\fR of the device,
5. the \fBread speed\fR of the device,
6. the \fBwrite speed\fR of the device, and
7. the \fBdriver\fR to be used with the device.  
.fi
.RE
.RS 5
.sp 1
All of these values
are expected to be separated with commas in the order they have been 
listed.
.RE
.TP
.I num\-copies:       
Number of copies to make.
.TP 
.I num\-files 
The number of files to be written to the medium. This argument may not be used 
by the script, however, it is needed in order to  maintain compatibility 
with other media writing scripts. 
.TP
.I data\-path:
Fully specified path to the directory of data.  This directory contains
the data which will burned onto the CD\-ROM.  This argument is not used
by the script but exists to maintain compatibility with other media 
writing scripts.

.PP
If 
.B sudo
is used the user running the software must be added to the 
.B sudo
configuration file, \fI/etc/sudoers\fR,
enabling them to run
.B cdrcord
as the superuser (root).

.SH OPTIONS
.TP
.B \-simulate
Simulate mode.  When this flag is specified \fBcdWriteRunCdrecord\-16\fR 
operates 
in simulation mode.  In simulate data is sent to the CD\-writter but it is
not written.

 
.SH USAGE
.B cdWriteRunCdrecord\-16
will require some operator input.  The operator will be prompted
whenever a blank CD\-ROM needs to be placed into the CD\-writer.

If 
.B cdWriteRunCdrecord\-16
is being run in simulate mode then no data will be written to the
CD\-ROM.  This is achieved by using the \-dummy flag on \fBcdrecord\fR
All operations are
performed except the actual burning of data onto the CD\-ROM.

.SH EXAMPLES
.PP 
The following example demonstrates how to use \fBcdWriteRunCdrecord\-16\fR.
.nf
.TP
.B "example% cdWriteRunCdrecord\-16 USER1_002 none /logs/cdWrite \e"
.B "/staging/media/staging3 /dev/rdsk/c5t5d0s0,2,3,0,6,4,none \e"
.B "2 12346 /staging/user/staging3"
.fi
.PP
In this example copies of volume (unit) 
.B USER1_002,
which is located in
.I /staging/media/staging3
will be written. There is no configuration file, the log file is located
at
.I /logs/cdWrite.
The CD\-ROM will contain 12346 files after it is burned.
Finally, the device information tells us that there is no driver to
be used.  The device is located on SCSI Bus 2, target 3, and logical
unit number 0.  The device reads at 6x speed and writes at 4x speed.
.PP
The following example demonstrates how to use
.B cdWriteRunCdrecord\-33
in simulation mode.
.nf
.TP
.B "example% cdWriteRunCdrecord\-16 ARCHIVE2_2032 none /logs/cdWrite \e"
.B "/staging/media/staging0 /dev/rdsk/c5t2d0s0,2,3,0,24,4,none 2 \e"
.B "823 /staging/user/staging0 -simulate"
.fi
.PP
In this example copies of volume (unit) 
.B ARCHIVE2_2032
which is located in
.I /staging/media/staging0
will be written. There is no configuration file to be used
and the log file is located at
.I /logs/cdWrite.
The CD\-Write will simulate burning 823 file to the CD\-ROM.
Finally, the device information tells us that there is no driver to
be used.  The device is located on SCSI Bus 0, target 4, and logical
unit number 0.  The device reads at 24x speed and writes at 4x speed.
Note that no data will be burned onto the CD\-ROM in this example.
.RE


.SH ENVIRONMENT VARIABLES
The shell's path variable
should include the locations of the
.B cdrecord
executable, the third party CD\-ROM authoring software
and 
.B sudo
if running on SunOS.
 
.SH DIAGNOSTICS
.B cdWriteRunCdrecord\-16
returns a 0 to the calling environment upon successful completion.
Otherwise a non\-zero number is returned. 
 
.SH SEE ALSO
.BR mediaWrite (1),
.BR cdrecord (1),
.BR sudo (8)
 
.SH BUGS
None known.
 
.SH AUTHOR
Steve Cockayne
.br
Shannon Jaeger
.br


National Research Council of Canada 
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
