#!/bin/csh -f
#/*+
#************************************************************************
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#*
#* (c) 1999.				(c) 1999.
#* National Research Council		Conseil national de recherches
#* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
#* All rights reserved			Tous droits reserves
#* 					
#* NRC disclaims any warranties,	Le CNRC denie toute garantie
#* expressed, implied, or statu-	enoncee, implicite ou legale,
#* tory, of any kind with respect	de quelque nature que se soit,
#* to the software, including		concernant le logiciel, y com-
#* without limitation any war-		pris sans restriction toute
#* ranty of merchantability or		garantie de valeur marchande
#* fitness for a particular pur-	ou de pertinence pour un usage
#* pose.  NRC shall not be liable	particulier.  Le CNRC ne
#* in any event for any damages,	pourra en aucun cas etre tenu
#* whether direct or indirect,		responsable de tout dommage,
#* special or general, consequen-	direct ou indirect, particul-
#* tial or incidental, arising		ier ou general, accessoire ou
#* from the use of the software.	fortuit, resultant de l'utili-
#* 					sation du logiciel.
#*
#************************************************************************
#*
#*   Script Name:	deviceStatus
#*
#*   Purpose:
#*	Whatever
#*
#*   Date		: Feb 19, 1999
#*
#*   SCCS data		: @(#)
#*	Module Name	: deviceStatus
#*	Version Number	: 1.3
#*	Release Number	: 1
#*	Last Updated	: 04/27/99
#*
#*   Programmer		: Shannon Jaeger
#*
#*   Modification History:
#*	99/04/22 NRH :	Added extraction of database information from the
#*			am library configuration file. Changed online/offline
#*			to book/unbook.
#*			
#*
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#************************************************************************
#-*/

set error_flag = 0
set avail = 0
set book = 0
set unavail = 0
set unbook = 0
set help = 0


#
#  Get required information from the am library configuration file. 
#

set env_line = `printenv | grep LIBAM_CONFIG_DIR`
set config_dir_path1 = `echo $env_line |sed 's/LIBAM_CONFIG_DIR=//'`
set config_file_path = "$config_dir_path1/libAm.config"

if ( -e $config_file_path ) then
    echo "    Configuration file '$config_file_path' has been opened"
else
    set env_line = `printenv | grep DEFAULT_CONFIG_DIR`
    set config_dir_path2 = `echo $env_line |sed 's/DEFAULT_CONFIG_DIR=//'`
    set config_file_path = "$config_dir_path2/libAm.config"

    if ( -e $config_file_path ) then
	echo "    Configuration file '$config_file_path' has been opened"
    else
	set config_file_path = "./libAm.config"

	if (  -e $config_file_path ) then
	    echo "    Configuration file '$config_file_path' has been opened"
	else
	    echo -n "Error - am library config file not found in the "
	    echo "following directories : "
	    echo "        ., $config_dir_path1, $config_dir_path2"
	    goto EXECERR
	endif
    endif
endif

set line = `cat $config_file_path | grep amDb | grep -v \#`
set server = 		$line[2]
set database =		$line[3]
set media_table = 	$line[4]

set line = `cat $config_file_path | grep deviceTables | grep -v \#`
set devices_table =	$line[2]
set book_device_table =	$line[3]
set logical_dev_table =	$line[4]

set db_info = `dbrc_get $server $database`
set user = $db_info[1]
set passwd = $db_info[2]

set inputfile = "/tmp/deviceStatus.input.$$"
set outputfile = "/tmp/deviceStatus.output.$$"


#
#************************************************************************
# Parse the command line arguments.
#************************************************************************
#

if ( $#argv > 0 ) then
    set logicalDevice = ""
    set logicalDevice = `echo $1 | awk '$1 !~ /^-.*/ { print $1; }'`
    if ( $logicalDevice != "" ) then
	shift
    endif
else
    set error_flag = 1
endif

while ( "$1" != "" && $error_flag != 1 )
    switch ( "$1" )
	case "-avail":
	    if ( $avail || $unavail ) then
		set error_flag = 1
		break
  	    else
		set avail = 1
	    endif
	    breaksw
	case "-unavail"
	    if ( $avail || $unavail ) then
		set error_flag = 1
		break
  	    else
		set unavail = 1
	    endif
	    breaksw
	case "-book"
	    if ( $book || $unbook ) then
		set error_flag = 1
		break
  	    else
		set book = 1
	    endif
	    breaksw
	case "-unbook"
	    if ( $book || $unbook ) then
		set error_flag = 1
		break
  	    else
		set unbook = 1
	    endif
	    breaksw
	case "-help":
	case "-?":
	case "-h":
	    set help = 1
	    breaksw
	default:
	    set error_flag = 1
    endsw
    shift
end

#
#************************************************************************
# Display usage and/or help information.
#************************************************************************
#

if ( $help || $error_flag == 1 ) then 
    echo 'Usage: deviceStatus <deviceName> [ -avail|-unavail ] [ -book|-unbook]'

    if ( $help ) then
	echo "                 logicalDevice: Logical name of the device.      "
	echo "                                (eg. CD1 or CDPAIR1)             "
	echo "                 -avail       : Make device available.	       "
	echo "                 -unavail     : Make device unavailable.         "
	echo "                 -book        : Book a logical device.	       "
	echo "                 -unavail     : Unbook a logical device.         "
	exit( 0 )
    else
       exit( 1 )
    endif
endif


#
#************************************************************************
# Verify existence of tables.
#************************************************************************
#

cat > $inputfile << _EOF_
use $database
go

select objs.name, type, users.name
    from sysobjects objs, sysusers users 
    where users.name = '$user' or users.name='dbo'
    and objs.name='$book_device_table' and objs.uid = users.uid 
go

select objs.name, type, users.name
    from sysobjects objs, sysusers users 
    where users.name = '$user' or users.name='dbo'
    and objs.name='$devices_table' and objs.uid = users.uid
go


select objs.name, type, users.name
    from sysobjects objs, sysusers users 
    where users.name = '$user' or users.name='dbo'
    and objs.name='$logical_dev_table' and objs.uid = users.uid
go
_EOF_
if ( $status ) then
    echo "Error: Unable to create file $inputfile"
    exit 1
endif


isql -S $server -U $user -P $passwd -i $inputfile -o $outputfile
if ( $status ) then
    echo "Error: Unable to check for device table existence"
    goto ERROR
endif


set ok = 1
foreach table ( $book_device_table $devices_table $logical_dev_table )
   set result = `cat $outputfile | awk 'BEGIN { total=0; } NF==3 && $1 == t { total += 1; } END { print total }' t=$table`
    if ( $status ) then
	echo "Error: Unable to read file $outputfile"
	exit 1
    endif

    if ( $result < 1 ) then
	set ok = 0
	echo "Table $table NOT Found" >> $outputfile
    else
        echo "Table $table Found" >> $outputfile
    endif
end
if ( ! $ok ) then
    echo "Error: Not all of the AM tables exist."
    goto ERROR
endif


#
#************************************************************************
# Verify logicalDevice and get deviceName(s)
#************************************************************************
#

cat > $inputfile << _EOF_
use $database
go

select distinct logicalName, deviceName
from $logical_dev_table
where logicalName = '$logicalDevice'
go
_EOF_
if ( $status ) then
    echo "Error: Unable to create file $inputfile"
    exit 1
endif

isql -S $server -U $user -P $passwd -i $inputfile -o $outputfile
if ( $status ) then
    echo "Error: Unable to check for device table existence"
    goto ERROR
endif

set deviceNames = ""
set deviceNames = `cat $outputfile | awk '$1 == logical { print $2; }' logical=$logicalDevice`
echo "deviceNames: $deviceNames"
if ( $status ) then
    echo "Error: Unable to read file $outputfile"
    exit 1
endif

if ( "$deviceNames" == "" ) then
    echo "Error: logcial device $logicalDevice was not found in the database."
    goto ERROR
endif


#
#************************************************************************
# Make device available or unavailable
#************************************************************************
#

if ( $unavail == 0 && $avail == 0 ) then
    goto ON_OFF
endif

cat > $inputfile << _EOF_
use $database
go
_EOF_
if ( $status ) then
    echo "Error: Unable to create file $inputfile"
    exit 1
endif

if ( $avail ) then
    set flag = 'Y'
else
    set flag = 'N'
endif

foreach device ( $deviceNames )
    cat >> $inputfile << _EOF_
update $devices_table set available = '$flag'
where deviceName ='$device'
go
_EOF_
    if ( $status ) then
	echo "Error: Unable to create file $inputfile"
	exit 1
    endif
end

isql -S $server -U $user -P $passwd -i $inputfile -o $outputfile
if ( $status ) then
    echo "Error: Unable to update logicalDevice $logicalDevice"
    goto ERROR
endif

set numAvail = `cat $outputfile | grep "row affect" | sed -e 's/(//' | awk 'BEGIN { total=0; } $1 ~ /^[0-9]+$/ { total += $1; } END{ print total; }'`
if ( $status ) then
    echo "Error: Unable to read file $outputfile"
    exit 1
endif


#
#************************************************************************
# Book or unbook a logical device
#************************************************************************
#

ON_OFF:

if ( $book == 0 && $unbook == 0 ) then
    goto DONE
endif

cat > $inputfile << _EOF_
use $database
go
_EOF_
if ( $status ) then
    echo "Error: Unable to create file $inputfile"
    exit 1
endif

if ( $book ) then
    set flag = 'Y'
else
    set flag = 'N'
endif

foreach device ( $deviceNames )
    cat >> $inputfile << _EOF_
update $book_device_table set inUse = '$flag'
where deviceName = '$device'
go
_EOF_
    if ( $status ) then
	echo "Error: Unable to create file $inputfile"
	exit 1
    endif
end
cat $inputfile

isql -S $server -U $user -P $passwd -i $inputfile -o $outputfile
if ( $status ) then
    echo "Error: Unable to update logicalDevice $logicalDevice"
    goto ERROR
endif

set numBooked = `cat $outputfile | grep "row affect" | sed -e 's/(//' | awk 'BEGIN { total=0; } $1 ~ /^[0-9]+$/ { total += $1; } END{ print total; }'`
if ( $status ) then
    echo "Error: Unable to read file $outputfile"
    exit 1
endif


#
#************************************************************************
# Done
#************************************************************************
#

DONE:
    if ( $avail ) then
	echo "Number of devices made available:    $numAvail"
    else if ( $unavail ) then
	echo "Number of devices made unavailable:  $numAvail"
    endif
    if ( $book ) then
	echo "Number of devices booked  :    $numBooked"
    else if ( $unbook ) then
	echo "Number of devices unbooked:     $numBooked"
    endif
    echo " "
    /bin/rm -f $inputfile $outputfile
    echo "deviceStatus has successfully completed."
    echo " "
    exit 0



#
#************************************************************************
#   Error message
#************************************************************************
#

ERROR:
    echo " "
    cat $outputfile
    /bin/rm -f $inputfile $outputfile
    echo " "
    exit 2
