.\"/*+
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"*	Name			: dvd/doc/dvdWrite.1
.\"*
.\"*	Date			: Mar 09, 1999
.\"*
.\"*	SCCS data		: @(#)
.\"*	    Module Name		: dvdWrite.1
.\"*	    Version Number	: 1.5
.\"*	    Release Number	: 1
.\"*	    Last Updated	: 04/15/99
.\"*
.\"*	Written by		: Shannon Jaeger
.\"*
.\"*	Modification History:
.\"*        98/12/15 SDJ	: Copied from cdWriteRunCdrecord.1
.\"*	    99/03/17 SDJ	: Added num_file argument.
.\"*	    99/04/15 SDJ	: Added new optional command-line arg 
.\"*				  "-simulate". Fixed spelling.
.\"*
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"************************************************************************
.\"-*/
.TH DVDWRITE 1 15/04/99 "CADC"
 
.SH NAME
.B dvdWrite
\- Runs a yet to be determined third party software which will burn a
DVD either from an image on magnetic disk or a prepared directory filled
with one DVD worth of data.
 
.SH SYNOPSIS
.B dvdWrite
.I volume\-name config\-file log\-file\-path
.I work\-path device\-information num\-copies 
.I num\-files data\-path
[
.I \-simulate
]


.SH DESCRIPTION
.B dvdWrite
is a C\-shell script that uses some unknown third party software
to write one or more copies of a DVD from either a physical image on 
magnetic disk or a prepared data directory. 
This script assumes that a single DVD\-writer is to be
used and that no stacker is used, so the operator must manually place
DVDs into the DVD\-writer.

This script parses the device specific information provided
by the
.I device\-information
command\-line parameter.  The information that is used includes:
.RS 4
.nf
not determined yet.
.fi
.RE

This script was written to work with an application such as
.B mediaWrite
which interfaces with a SYBASE server and tables.

.SH OPERATION
.B dvdWrite 
requires eight command\-line parameters:
.TP
.I volume\-name:      
Name of DVD in upper\-case.
.TP
.I config\-file:
Fully specified path and name of the script's configuration file.  This
command\-line parameter was kept even though it probably will not be 
needed.  This parameter exists 
in order to maintain compatibility with other scripts which write media.
.TP
.I log\-file\-path:    
Fully specified path and name of log file.
.TP
.I work\-path:   
Fully specified path to the work directory.  This directory contains
the physical image of the DVD to be written, if one is needed.
.TP
.I device\-information:
The device information includes the following: 
.TP
.RS 6
.nf
1. \fBdevice name\fR or mount point of the DVD writer,
2. \fBDdevice info\fR - to be determined what this includes,
3. the \fBread speed\fR of the device,
4. the \fBwrite speed\fR of the device, and
5. the \fBdriver\fR to be used with the device.  
.fi
.RE
.RS 5
.sp 1
These values
are expected to be separated with commas in the order they have been 
listed.
.RE
.TP
.I num\-copies:       
Number of copies to make.
.TP
.I num\-files
The number of files to be written to the medium. This argument may not be used
by the script, however, it is needed in order to  maintain compatibility
with other media writing scripts.
.TP
.I data\-path:
Fully specified path to the directory of data.  This directory contains
the data which will be burned onto the DVD.  This argument may not be used
by the script, however, it is needed in order to  maintain compatibility
with other media writing scripts.

.SH OPTIONS
.TP
.B \-simulate
Simulate mode.  When this flag is specified \fBdvdWrite\fR operates 
in simulation mode.  In simulate mode data is sent to the DVD\-writer but no 
data it is not written.
 
.SH USAGE
.B dvdWrite
may require some operator input.  It is likely the operator will be prompted
whenever a blank DVD needs to be placed into the DVD\-writer.

If 
.B dvdWrite
is being run in simulate mode then no data will be written to the
DVD. All operations are
performed except the actual burning of data onto the DVD.

.SH EXAMPLES
.PP 
The following example demonstrates how to use \fBdvdWrite\fR.
.nf
.TP
.B "example% dvdWrite USER1_002 none /logs/dvdWrite \e"
.B "/staging/media/staging3 /dev/rdsk/c5t5d0s0,2,3,0,6,4,none \e"
.B "2 23419 /staging/user/staging3"
.fi
.PP
In this example two copies of volume (unit) 
.B USER1_002,
which is located in
.I /staging/media/staging3
will be written. There is no configuration file, the log file is located
at
.I /logs/dvdWrite.
There are two DVDs to be written and each will contain 23419 files.
Finally, the device information tells us that there is no driver to
be used.  The device is located on SCSI Bus 2, target 3, and logical
unit number 0.  The device reads at 6x speed and writes at 4x speed.

.PP
The following example demonstrates how to use
.B dvdWrite
in simulation mode.
.nf
.TP
.B "example% dvdWrite ARCHIVE2_2032 none /logs/dvdWrite \e"
.B "/staging/media/staging0 /dev/rdsk/c5t2d0s0,2,3,0,24,4,none 2 \e"
.B "823 /staging/user/staging0 -simulate"
.fi
.PP
In this example copies of volume (unit) 
.B ARCHIVE2_2032
which is located in
.I /staging/media/staging0
will be written. There is no configuration file
.I /dot_files/gearrc
and the log file is located at
.I /logs/cdWrite.
The DVD\-writer will simulate burning 823 files onto the DVD.
Finally, the device information tells us that there is no driver to
be used.  The device is located on SCSI Bus 0, target 4, and logical
unit number 0.  The device reads at 24x speed and writes at 4x speed.
Note that no data will be burned onto the CD\-ROM in this example.
.RE

.SH ENVIRONMENT VARIABLES
The shell's path variable
should include the locations of the
the third party DVD authoring software.

 
.SH DIAGNOSTICS
.B dvdWrite
returns a 0 to the calling environment upon successful completion.
Otherwise a non\-zero number is returned. 
 
.SH SEE ALSO
.BR dvdPrep (1),
.BR mediaPrep (1),
and
.BR mediaWrite (1),

 
.SH BUGS
None known.
 
.SH AUTHOR
Shannon Jaeger
.br


National Research Council of Canada 
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
