#!/bin/tcsh -f
#/*+
#************************************************************************
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#*
#* (c) 1998.				(c) 1998.
#* National Research Council		Conseil national de recherches
#* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
#* All rights reserved			Tous droits reserves
#* 					
#* NRC disclaims any warranties,	Le CNRC denie toute garantie
#* expressed, implied, or statu-	enoncee, implicite ou legale,
#* tory, of any kind with respect	de quelque nature que se soit,
#* to the software, including		concernant le logiciel, y com-
#* without limitation any war-		pris sans restriction toute
#* ranty of merchantability or		garantie de valeur marchande
#* fitness for a particular pur-	ou de pertinence pour un usage
#* pose.  NRC shall not be liable	particulier.  Le CNRC ne
#* in any event for any damages,	pourra en aucun cas etre tenu
#* whether direct or indirect,		responsable de tout dommage,
#* special or general, consequen-	direct ou indirect, particul-
#* tial or incidental, arising		ier ou general, accessoire ou
#* from the use of the software.	fortuit, resultant de l'utili-
#* 					sation du logiciel.
#*
#************************************************************************
#*
#*   Script Name:	updateMedia
#*
#*   Purpose:
#*	To update the indexes on the various media tables by running
#*	update statistics on them.  This will make database transactions
#*	faster. 
#*
#*   Date		: Aug 26, 1998
#*
#*   SCCS data		: @(#)
#*	Module Name	: updateMediaIndexes
#*	Version Number	: 1.2
#*	Release Number	: 1
#*	Last Updated	: 03/19/99
#*
#*   Programmer		: Shannon Jaeger
#*
#*   Modification History:
#*	99/03/19 NRH  : Changed to take db names from libAm Configuration
#*			file. Changed to update all indexes instead of a
#*			given list.
#*
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#************************************************************************
#-*/

#
# Initialization
# Note that the staging directory is the DHS Storage Servers retrival
# area and the mediHost is the name of the machine containing this
# directory.
#

if ( $?LIBAM_CONFIG_DIR ) then
    if ( -f $LIBAM_CONFIG_DIR/libAm.config ) then
	set libAmConfigFile = $LIBAM_CONFIG_DIR/libAm.config
    endif
endif
if ( ! $?libAmConfigFile && $?DEFAULT_CONFIG_DIR ) then
    if ( -f $DEFAULT_CONFIG_DIR/libAm.config ) then
	set libAmConfigFile = $DEFAULT_CONFIG_DIR/libAm.config
    endif
endif
if ( ! $?libAmConfigFile && -f libAm.config ) then
    set libAmConfigFile = ./libAm.config
endif

if ( ! $?libAmConfigFile ) then
    echo "Error: Could not find the AM library configuration file."
    exit 2
endif


set sybase_server = `awk '$1 == "amDb" { print $2 }' $libAmConfigFile`
set sybase_database = `awk '$1 == "amDb" { print $3 }' $libAmConfigFile`
set amMedia = `awk '$1 == "amDb" { print $4 }' $libAmConfigFile`
set amMediaFiles = `awk '$1 == "amDb" { print $5 }' $libAmConfigFile`
set amMediaUnits = `awk '$1 == "amDb" { print $6 }' $libAmConfigFile`
set amMediaStages = `awk '$1 == "amDb" { print $7 }' $libAmConfigFile`
set amStatus = `awk '$1 == "amDb" { print $8 }' $libAmConfigFile`
set amDevice = `awk '$1 == "deviceTables" { print $2 }' $libAmConfigFile`
set amBookDevice = `awk '$1 == "deviceTables" { print $3 }' $libAmConfigFile`
set amLogicalDevices = `awk '$1 == "deviceTables" { print $4 }' $libAmConfigFile`
set amMediaTypes = `awk '$1 == "devicesTables" { print $4 }' $libAmConfigFile`

set output_file = "/tmp/updateMediaIndexes.output.$$"
set input_file = "/tmp/updateMediaIndexes.input.$$"


#
#************************************************************************
# Get Command line args and determine there correctness.
#************************************************************************
#

if ( $#argv != 0 ) then
    echo "updateMediaIndexes"
    exit 1
endif

onintr -

set sybase_info = `dbrc_get $sybase_server $sybase_database`


#
#************************************************************************
# Run update statistics on devices tables to make database more efficient.
#************************************************************************
#

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
update statistics $amBookDevice \
go\
update statistics $amDevice \
go\
update statistics $amLogicalDevices \
go\
update statistics $amMediaTypes \
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo 'Error: Unable to run update statistics on "bookDevice", "devices",'
    echo '       "logicalDevices", or "mediaTypes" table.'
    goto SYBERR
endif


#
#************************************************************************
# Run update statistics on media  tables to make database more efficient.
#************************************************************************
#

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
update statistics $amMedia \
go\
update statistics $amMediaFiles \
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo 'Error: Unable to run update statistics on "media" or '
    echo '       "media_files" table.'
    goto SYBERR
endif


set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
update statistics $amMediaUnits \
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo 'Error: Unable to run update statistics on "media_units" table.'
    goto SYBERR
endif

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
update statistics $amMediaStages \
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo 'Error: Unable to run update statistics on "media_stages" table.'
    goto SYBERR
endif

#
#************************************************************************
# Run update statistics on status table to make database more efficient.
#************************************************************************
#

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
update statistics $amStatus \
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo 'Error: Unable to run update statistics on "status" table.'
    goto SYBERR
endif

echo "Update statistics has been run on all Archive Media tables."
echo "updateMediaIndexes had completed without any errors."
echo " "
rm -f $output_file 
exit 0

SYBERR:
   echo ""
   echo "Error: Not all Archive Media tables were updated."
   echo ""
   cat $output_file
   rm -f $output_file	
   exit 1


