# Makefile

# include configured paths
include conf/include.mk

# make subdirectories
SUBDIRS = \
	gen \
	db \
	ad \
	mfs \
	crc \
	cd \
	dvd \
	tp \
	press \
	am \
	gen++ \
	dhsGen \
	dhs++ \
	dhsSta \
	dd \
	sf \
	dhs \
	fh \
	arrayMath \
	qldp \
	fitsio \
	dhsCommand \
	dhsConsole \
	dhsData \
	dhsGet \
	dhsHistory \
	dhsPut \
	dhsQlServer \
	dhsQlTool \
	dhsStatus \
	dhsStorage \
	dhs++Client \
	dhs++Server \
	dhsClient \
	dhsCmdSender \
	dhsInstSim \
	dhsServer \
	dhsSim4Data \
	dhsTestCmdr \
	fits2sds \
	cdIngest \
	cdOnline \
	mediaCleanup \
	mediaPrep \
	mediaQueue \
	mediaWrite \
	testCmdr \
	tpIngest \



SCRIPTS = \
	scripts/dhsCleanup \
	scripts/GemBootStart \
	scripts/MakeClassicalMedia \
	scripts/MakePrImages \
	scripts/MakeUserMedia \
	scripts/newsyslog

RELEASE_DIRS = \
	release \
	release/bin \
	release/include \
	release/lib \
	release/scripts \
	release/sql \
	release/config \
	release/doc \
	release/man \
	release/man/man1 \
	release/man/man3 \
	release/man/mann


# compile
all: install_dirs
	for i in $(SUBDIRS); do (cd $$i; echo "$$i:"; $(MAKE) all install)  || exit 1 ; done

setup: 

# remove generated files
clean: FORCE
	for i in $(SUBDIRS); do (cd $$i; echo "$$i:"; $(MAKE) $@)  || exit 1 ; done

# also remove files generated by configure
distclean: clean
	rm -f config.status config.cache config.log confdefs.h include.mk
	rm -rf release */*.d

# create the installation directories, if needed
install_dirs: FORCE
	@for i in ${RELEASE_DIRS}; do test -d $$i || mkdir $$i; done

# install generated files in release dir
install: install_dirs
	cp */*.h release/include
	cp ${SCRIPTS} release/scripts
	cp */*.config release/config
	cp */html/*.html release/doc
	cp */*.sql release/sql
	cp */*.1 release/man/man1
	cp */*.3 release/man/man3
	cp */*.n release/man/mann
	for i in $(SUBDIRS); do (cd $$i; echo "$$i:"; $(MAKE) $@) done

FORCE:
