# Makefile

# include configured paths
include conf/include.mk

# make subdirectories
SUBDIRS = \
	db \
	ad \
	mfs \
	crc \
	cd \
	dvd \
	tp \
	press \
	am \
	gen++ \
	dhsGen \
	dhs++ \
	dhsSta \
	dd \
	sf \
	fh \
	arrayMath \
	qldp \
	dhsCommand \
	dhsConsole \
	dhsData \
	dhsGet \
	dhsHistory \
	dhsPut \
	dhsQlServer \
	dhsQlTool \
	dhsStatus \
	dhsStorage \
	dhs++Client \
	dhs++Server \
	dhsCmdSender \
	dhsInstSim \
	dhsSim4Data \
	dhsTestCmdr \
	fits2sds \
	cdIngest \
	cdOnline \
	mediaCleanup \
	mediaPrep \
	mediaQueue \
	mediaWrite \
	testCmdr \
	tpIngest \



SCRIPTS = \
	scripts/dhsCleanup \
	scripts/GemBootStart \
	scripts/MakeClassicalMedia \
	scripts/MakePrImages \
	scripts/MakeUserMedia \
	scripts/newsyslog \
	dhsQlTool/dhsQlTool

RELEASE_DIRS = \
	release \
	release/bin \
	release/include \
	release/lib \
	release/scripts \
	release/sql \
	release/images \
	release/tcl \
	release/config \
	release/html \
	release/man \
	release/man/man1 \
	release/man/man3 \
	release/man/mann


# compile
all: install_dirs
	for i in $(SUBDIRS); do (cd $$i; echo "$$i:"; $(MAKE) all install)  || exit 1 ; done

setup: 

# remove generated files
clean: FORCE
	for i in $(SUBDIRS); do (cd $$i; echo "$$i:"; $(MAKE) $@)  || exit 1 ; done

# also remove files generated by configure
distclean: clean
	rm -f config.status config.cache config.log confdefs.h include.mk

depend:
	rm -f */*.d

# create the installation directories, if needed
install_dirs: FORCE
	@for i in ${RELEASE_DIRS}; do test -d $$i || mkdir $$i; done

# install generated files in release dir
install: install_dirs
	-cp -f */*.h release/include
	-cp -uf ${SCRIPTS} release/scripts
	-cp -uf */*.config release/config
	-cp -f dhs*/html/*.html release/html
	-cp -uf */*.sql release/sql
	-cp -f */*.xbm release/images
	-cp -f */*.tcl release/tcl; (cd release/tcl; tclsh$(TCL_VERSION) ./mkIndex.tcl)
	-cp -f */*.1 release/man/man1
	-cp -f */*.3 release/man/man3
	-cp -f */*.n release/man/mann
	-for i in $(SUBDIRS); do (cd $$i; echo "$$i:"; $(MAKE) $@) done
	(cd release/bin; ln -sf ../scripts/dhsQlTool)

FORCE:

etags tags:
	etags \
	  `find . -name '*.[CchH]' -print` \
	  `find ../dhsClient -name '*.[CchH]' -print` \
	  `find ../cfitsio -name '*.[CchH]' -print` \
