#!/bin/tcsh -f
#/*+
#************************************************************************
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#*
#* (c) 1998.				(c) 1998.
#* National Research Council		Conseil national de recherches
#* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
#* All rights reserved			Tous droits reserves
#* 					
#* NRC disclaims any warranties,	Le CNRC denie toute garantie
#* expressed, implied, or statu-	enoncee, implicite ou legale,
#* tory, of any kind with respect	de quelque nature que se soit,
#* to the software, including		concernant le logiciel, y com-
#* without limitation any war-		pris sans restriction toute
#* ranty of merchantability or		garantie de valeur marchande
#* fitness for a particular pur-	ou de pertinence pour un usage
#* pose.  NRC shall not be liable	particulier.  Le CNRC ne
#* in any event for any damages,	pourra en aucun cas etre tenu
#* whether direct or indirect,		responsable de tout dommage,
#* special or general, consequen-	direct ou indirect, particul-
#* tial or incidental, arising		ier ou general, accessoire ou
#* from the use of the software.	fortuit, resultant de l'utili-
#* 					sation du logiciel.
#*
#************************************************************************
#*
#*   Script Name:	rmMedia
#*
#*   Purpose:
#*	To remove a User or Archive from the Storage Media tables.  
#*	Includes removing the user or archive directory in the data stage.
#*
#*   Date		: Aug 26, 1998
#*
#*   SCCS data		: @(#)
#*	Module Name	: rmMedia
#*	Version Number	: 1.2
#*	Release Number	: 1
#*	Last Updated	: 04/22/99
#*
#*   Programmer		: Shannon Jaeger
#*
#*   Modification History:
#*	99/04/22 NRH  : Added extraction of database information from the
#*			am library configuration file. Removed code to update
#*			the key value when the removed request is the last
#*			one. Fixed checking for incomplete units and files
#*			to allow for more than one digit.
#*
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#************************************************************************
#-*/

#
# Initialization
# Note that the staging directory is the DHS Storage Servers retrival
# area and the mediHost is the name of the machine containing this
# directory.
#

#
#  Get required information from the am library configuration file. 
#

set env_line = `printenv | grep LIBAM_CONFIG_DIR`
set config_dir_path1 = `echo $env_line |sed 's/LIBAM_CONFIG_DIR=//'`
set config_file_path = "$config_dir_path1/libAm.config"

if ( -e $config_file_path ) then
    echo "    Configuration file '$config_file_path' has been opened"
else
    set env_line = `printenv | grep DEFAULT_CONFIG_DIR`
    set config_dir_path2 = `echo $env_line |sed 's/DEFAULT_CONFIG_DIR=//'`
    set config_file_path = "$config_dir_path2/libAm.config"

    if ( -e $config_file_path ) then
	echo "    Configuration file '$config_file_path' has been opened"
    else
	set config_file_path = "./libAm.config"

	if (  -e $config_file_path ) then
	    echo "    Configuration file '$config_file_path' has been opened"
	else
	    echo -n "Error - am library config file not found in the "
	    echo "following directories : "
	    echo "        ., $config_dir_path1, $config_dir_path2"
	    goto EXECERR
	endif
    endif
endif


set line = `cat $config_file_path | grep dataStage | grep -v \#`
set user_data_stage = $line[2]
set arch_data_stage = $line[3]
set media_data_stage = $line[4]

set line = `cat $config_file_path | grep amDb | grep -v \#`
set sybase_server = 	$line[2]
set sybase_database =	$line[3]
set media_table = 	$line[4]
set files_table = 	$line[5]
set units_table =	$line[6]
set stage_table = 	$line[7]

set line = `cat $config_file_path | grep deviceTables | grep -v \#`
set book_device_table =	$line[3]

set output_file = "/tmp/rmMedia.output.$$"
set input_file = "/tmp/rmMedia.input.$$"
set sybase_info = `dbrc_get $sybase_server $sybase_database`


#
#************************************************************************
# Get Command line args and determine there correctness.
#************************************************************************
#

if ( $#argv != 1 ) then
    echo "rmMedia <identifier>"
    echo "    <identifier>      : Unique numerical media identifier."
    exit 1
endif

set request_id = $1
set nonNumerics = `echo $request_id | sed -e 's/[0-9]//g'`
if ( $nonNumerics != "" ) then
   echo "Error: The request identifier must be a numerical value."
   exit 1
endif


#
#************************************************************************
# Warn user of this scripts destructive nature.
#************************************************************************
#

echo "				 W A R N I N G"
echo " "
echo "This script will remove ALL information from the database pertaining"
echo "to media ID $request_id"
echo " "
echo "Inorder for this script to succeed the following conditions must exist:"
echo '     media has a "D"one status'
echo '     All units have a "D"one status'
echo '     All files have a "D"one status'
echo '     media is NOT using any staging directories'
echo '     media is NOT using any devices'
echo " "

echo -n "Continue (y/n): "

set answer = $<
if ( $answer != "y" ) then
    exit 0
endif


#
#************************************************************************
# Verify that it is safe to remove this media request, the following
# conditions exist.
#      It is a valid media request id.
#      All files have status: "D"one
#      All units have status: "D"one
#      Media has status: "D"one.
#      media request is not using any staging directories.
#      media request is not using any staging devices.
#************************************************************************
#

onintr -

echo "**** Checking if request $request_id can be removed ****"


#
# Make sure this one is in the database.
#

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
select * from $media_table where media_request_id=$request_id\
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo "Error: Unable to query database for request id."
    goto SYBERR
endif

set results = `grep '0 rows affected' $output_file`
if ( `expr "$results" : '(0 rows affected)'` == 17 ) then
    echo "Error: request id $request_id was not found in the database."
    goto EXIT
endif


#
# Make sure all files are "D"one.
# 

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
set nocount on\
go\
select status, count(*) from $files_table\
where media_request_id=$request_id\
   and status != "D"\
group by status\
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo "Error: Unable to get file status from database."
    goto SYBERR
endif

set numNotDone = `cat $output_file | awk 'BEGIN { total=0; } NF==2 && $2 ~ /^[0-9]+$/ { total += $2; } END { print total ; }'`

if ( $numNotDone > 0 ) then
   echo "Error: $numNotDone files have NOT been fully processed for request $request_id."
   goto SYBERR
endif


#
# Make sure all units are "D"one.
# 

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
set nocount on\
go\
select status, count(*) from $units_table\
where media_request_id=$request_id\
    and status != "D"\
group by status\
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo "Error: Unable to query database for request id."
    goto SYBERR
endif

set numNotDone = `cat $output_file | awk 'BEGIN { total=0; } NF==2 && $2 ~ /^[0-9]+$/ { total += $2; } END { print total ; }'`

if ( $numNotDone > 0 ) then
   echo "Error: $numNotDone units have NOT been fully processed for request $request_id."
    goto SYBERR
endif


#
# Make sure the media is "D"one.
# 

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
set nocount on\
go\
select status, count(*) from $media_table\
where media_request_id=$request_id\
   and status != "D"\
group by status\
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo "Error: Unable to query database for request id."
    goto SYBERR
endif

set numNotDone = `cat $output_file | awk 'BEGIN { total=0; } NF==2 && $2 ~ /^[0-9]+$/ { total += $2; } END { print total ; }'`

if ( $numNotDone > 0 ) then
    echo "Error: The media has not been fully processed for request $request_id."
    goto SYBERR
endif


#
# Make no staging directories contain the given request id.
# 

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
select medis_request_id, count(*)\
from $stage_table\
 where media_request_id=$request_id\
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo "Error: Unable to query database for request id."
    goto SYBERR
endif

set numStages = `cat $output_file | awk 'BEGIN { total=0; } NF==2 && $1==id { total += $2; } END { print total ; }' id=$request_id`

if ( $numStages > 0 ) then
    echo "Error: Request $request_id still has $numStages staging areas booked"
    goto SYBERR
endif


#
# Make no staging directories contain the given request id.
# 

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
select medis_request_id, count(*)\
from $book_device_table\
 where media_request_id=$request_id\
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo "Error: Unable to query $book_device_table table for request id."
    goto SYBERR
endif

set numDevices = `cat $output_file | awk 'BEGIN { total=0; } NF==2 && $1==id { total += $2; } END { print total ; }' id=$request_id`

if ( $numDevices > 0 ) then
    echo "Error: Request $request_id is still using $numDevices devices"
    goto SYBERR
endif


#
#************************************************************************
# Safe to remove media so get its information from the database
#************************************************************************
#

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
select media_request_id, media_request_type, media_request_name \
from $media_table \
where media_request_id=$request_id\
go\
_EOF_`


set exit_status = $status
if ( $exit_status < 0 ) then
    echo "Error: Unable to query database for request id."
    goto SYBERR
endif

set request_type = `cat $output_file | gawk 'BEGIN { OFS=" " ; } $1 == "'$request_id'" { output = $2 ; } END { print output ; }'`

set request_name = `cat $output_file | gawk 'BEGIN { OFS=" " ; } $1 == "'$request_id'" { output = $3 ; } END { print output ; }'`



#
#************************************************************************
# Remove all database information
#      Remove all files in media_files.
#      Remvoe all units in media_units.
#      Remove the Media from media.
#************************************************************************
#

echo "**** Removing request $request_id from the media database tables ****"

set output = `isql -S $sybase_server -U $sybase_info[1] -o $output_file << _EOF_ | grep GREP_TARGET\
$sybase_info[2]\
use $sybase_database\
go\
delete $units_table where media_request_id=$request_id\
go\
delete $files_table where media_request_id=$request_id\
go\
delete $media_table where media_request_id=$request_id\
go\
_EOF_`

set exit_status = $status
if ( $exit_status < 0 ) then
    echo "Error: Unable to query database for request id."
    goto SYBERR
endif


#
#************************************************************************
# Remove any files and the directory associated with this user.
#************************************************************************
#

echo "***** Media with identifier $request_id has been removed.  *****"
if ( $request_type == "USER" ) then
	set mediaDir = "$user_data_stage/$request_id.$request_name"
else
	set mediaDir = "$arch_data_stage/$request_id.$request_name"
endif
/bin/rm -f -r $mediaDir >& /dev/null
echo ""
echo "Request $request_id ($request_name) has been removed."
goto EXIT



SYBERR:
   echo ""
   echo "ERROR: $request_id NOT removed from database"
   echo ""
   cat $output_file
EXIT:
   rm -f $output_file	
   exit 1

