#!/bin/sh 
#/*+
#************************************************************************
#** D O M I N I O N  A S T R O P H Y S I C A L  O B S E R V A T O R Y  **
#*
#*   Script Name:	dbrc_get
#*
#*   Purpose:
#*	Given a server and database, display a username and password to
#*	the standard output which can be used to access the database.  
#*	Return status is 0 if no errors occured, otherwise it is non
#*	zero.
#*
#*	This is a shell script because it must prompt to standard error.
#*
#*   Date		: Oct 29, 1992
#*
#*   SCCS data		: @(#)
#*	Module Name	: dbrc_get
#*	Version Number	: 1.4
#*	Release Number	: 1
#*	Last Updated	: 06/24/97
#*
#*   Programmer		: Norman Hill
#*
#*   Modification History:
#*	97/06/24 rg	: port to HP/UX 
#*			  (replaced "awk -f -" with "awk -f <script>")
#*
#** D O M I N I O N  A S T R O P H Y S I C A L  O B S E R V A T O R Y  **
#************************************************************************
#-*/

#
# script variables
#

tmp_awkfile=/tmp/dbrc_get$$.awk

if test "$1" = "" -o "$2" = ""
then
    echo "(DR-1)  Usage: dbrc_get <server> <database>" >&2
    echo "                        <server>   - Server to be accessed." >&2
    echo "                        <database> - Database to be accessed." >&2
    exit 1
fi


server=$1
database=$2

#
#  Check that the $HOME/.dbrc file exists, and that it's protections are
#  correct.
#

answer=""
if ( test -f $HOME/.dbrc ) 
then
    if ( test "`ls -l $HOME/.dbrc | cut -c4-10`" != "-------" ) 
    then
	echo "(DR-2)  The protection mode of file $HOME/.dbrc must be '600'" >&2
	exit 2
    fi


    cat > $tmp_awkfile << _EOF_
	{
	    if ( \$1 == "$server" && \$2 == "$database" )
	    {
		print \$3, \$4;
		exit;
	    }
	}
_EOF_
    answer=`awk -f $tmp_awkfile $HOME/.dbrc`
    echo $answer
    \rm $tmp_awkfile 1>/dev/null 2>&1
fi


( if test "$answer" = "" 
then
    echo -n "Enter Sybase user name for database $database on server $server : "
    read username
    echo -n "Enter the Sybase password for user $username : "
    stty -echo
    read password 
    stty echo
    echo ""

    answer="$username $password"
    echo $answer >&3
fi ) 3>&1 0>&2

exit 0
