/*+
************************************************************************
****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
*
* (c) 1998.				(c) 1998.
* National Research Council		Conseil national de recherches
* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
* All rights reserved			Tous droits reserves
* 					
* NRC disclaims any warranties,		Le CNRC denie toute garantie
* expressed, implied, or statu-		enoncee, implicite ou legale,
* tory, of any kind with respect	de quelque nature que se soit,
* to the software, including		concernant le logiciel, y com-
* without limitation any war-		pris sans restriction toute
* ranty of merchantability or		garantie de valeur marchande
* fitness for a particular pur-		ou de pertinence pour un usage
* pose.  NRC shall not be liable	particulier.  Le CNRC ne
* in any event for any damages,		pourra en aucun cas etre tenu
* whether direct or indirect,		responsable de tout dommage,
* special or general, consequen-	direct ou indirect, particul-
* tial or incidental, arising		ier ou general, accessoire ou
* from the use of the software.		fortuit, resultant de l'utili-
* 					sation du logiciel.
*
************************************************************************
*
*   Module Name:	mediaWrite/src/write.c
*
*   Purpose:
*	Routines for handling message to log file, user's terminal.
*
*   Routines:
*	void	formatMessage	: Format a message.
*	void	printMessage	: Print a message.
*
*   Date		: Sep 09, 1998
*
*   SCCS data		: @(#)
*	Module Name	: msg.c
*	Version Number	: 1.7
*	Release Number	: 1
*	Last Updated	: 04/15/99
*
*   Programmer		: Shannon jaeger
*
*   Modification History:
*      	98/09/09 SDJ    : Copied from cdWrite
*	98/10/22 SDJ	: Added msgs for device handling.
*       98/10/21 SDJ  	: Added device handling and script info from AM.
*	99/03/08 NRH	: Added support for rollback.
*	99/03/18 NRH	: Added S_NO_COPIES, S_SCRIPT_LOG and 
*			  S_SCRIPT_LOG_DATA messages.
*	99/03/25 SDJ	: Added E_DEV_NOT_FOUND msg.
*	99/04/08 NRH	: Added -simulate to the usage message. Updated
*			  the E_FORK_N_EXEC message to take another argument.
*	99/04/15 SDJ	: Added S_SCRIPT_END, Edited S_SCRIPT_LOG.
*
****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
************************************************************************
-*/



/*
 ************************************************************************
 *  General unix include files.
 ************************************************************************
 */
 
#include <unistd.h>
#include <stdarg.h>
 

/*
 ************************************************************************
 *  SYBASE DB libarary include files.
 ************************************************************************
 */
 
#include <sybfront.h>
#include <sybdb.h>
 

/*
 ************************************************************************
 *  CADC library include files.
 ************************************************************************
 */
 
#include "gen_types.h"
#include "gen_str.h"
#include "gen_msg.h"
#include "gen_eptr.h"
#include "gen_config.h"
#include "am.h"
 
 
/*
 ************************************************************************
 *  Media Write include files.
 ************************************************************************
 */

#include "globals.h"


/*
 ************************************************************************
 * Constatns definitions
 ************************************************************************
 */

#define	PREFIX	"mw"


/*
 ************************************************************************
 *  data types 
 ************************************************************************
 */
 
/*
 * Create a place to store the sf messages.
 */

char	msg[MSG_MAX_LEN];


/*
 * Define the status messages.
 */

static MSG	msgs[] = {
    { S_BEGINNING,
      "Beginning writing of media unit:  %s." },
    { S_COMPLETE,
      "Completed writing media unit '%s' to media(s)." },
    { S_COPIES_WRITTEN,
      "The number of copies of unit '%s' written is now shown as %d." },
    { S_DEV_SELECTED,
      "Continuing with device '%s'." },
    { S_MW_SIGNAL,
      "mediaWrite handling signal, quitting write script if necessary." },
    { S_NO_COPIES,
      "There are no copies of unit '%s' to be written." },
    { S_QUIT,
      "Quit a user's request." },
    { S_ROLLBACK,
	"Rollback of unit `%s' in media request %d started." },
    { S_ROLLBACK_DONE,
	"Rollback of unit `%s' in media request %d complete." },
    { S_SCRIPT_END,
   	"*******************************************************************\n"
        "*                                                                 *\n"
        "* End of the log file generated by %2dth: %20s.    *\n"
        "*                                                                 *\n"
        "*******************************************************************" },
    { S_SCRIPT_ERR,
        "The write script's log file reports errors in writing.  Please\n"
        "investigate file: %s." },
    { S_SCRIPT_LOG,
        "*******************************************************************\n"
        "*                                                                 *\n"
        "* Following Log file generated by %2dth: %20s.     *\n"
        "*                                                                 *\n"
        "*******************************************************************" },
    { S_SCRIPT_LOG_DATA,
	"%s" },
    { S_SCRIPT_NUM_DONE,
        "The write script's log file(s) report that  %d copies"
        " were written." },
    { S_USAGE,
	"Usage: mediaWrite -i <media ID> -n <unit name> [options]           \n"
	"                 <media ID>   - A valid media ID integer.          \n"
	"                 <unit name>  - A valid media unit name.           \n"
        "                 [-l <device>]- One or more logical device names.  \n"
        "                 [-force]     - Force booking of logical device.   \n"
        "                 [-num_copies]- Num. of copies to copy or roll back.\n"
	"                 [-rollback]  - Rollback a previous write operation.\n"
	"                 [-simulate]  - Don't really write the media.      \n"
	"                 [-v]         - Verbose mode.                      \n"
	"                 [-V]         - Print version and exit." },
    { S_VERSION,
	"%s" },
    { E_AM,
	"Error: am library error." },
    { E_BAD_U_STATUS,
	"Error: mediaWrite cannot process unit with status '%s'." },
    { E_CONFIG,
      "Error: reading from configuration file." },
    { E_DATA_STAGE,
	"Error - Data stage for %d: %s." },
    { E_DEV_NOT_FOUND,
        "Error: Logical device `%s' is not in the AM library tables." },
    { E_DEVICE_BUSY,
        "Error: Unable to book device `%s' it is busy." },
    { E_DEVICE_TYPE,
	"Type of logical device `%s' does not match the request type `%s'" },
    { E_DB,
      	"Error: SYBASE DB library error." },
    { E_DB_LIB,
	"Error: in the cadc db library." },
    { E_DISPLAY,
        "Error: DISPLAY environment variable must be set." },
    { E_EXEC_ABNORMAL_EXIT,
	"Error: Write script's xterm returned abnormally." },
    { E_EXEC_NONZERO_EXIT,
	"Error: Write script's xterm returned nonzero status." },
    { E_FORK_N_EXEC,
	 "Error: fork() and exec() calls to start write script in an xterm."
        "\n%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s, %s" },
    { E_LOG_FMT,
        "Error: getting information from the write script's log file:"
        "\t%s" },
    { E_MEMORY,
	"Error: Memory allocation failure." },
    { E_NO_DEVICE,
      "Error: No matching devices for %s." },
    { E_NO_MEDIA,
	"Error: No db media entry for media ID : %d." },
    { E_NO_ROLLBACK,
	"There are no written media to rollback for media id %d, unit %s." },
    { E_NO_UNIT,
	"Error: No db unit entry for media ID : %d, unit: %s." },
    { E_NOT_COMPLETE,
        "Writing of media not complete.  A total of  %d  have been written.\n"
        "The media table expects  %d  to be written.  Please investigate \n"
        "and re-run mediaWrite. " },
    { E_NUM_COPIES,
        "Error:  Script %s reports %d copies have been written when\n"
        "        %d copies were expected." },
    { E_ONLY_ONE,
	"Error: mediaWrite already running.  Only one permitted per media unit." },
    { E_STAGE_DIR,
	"Error: Not a directory: '%s'." },
    { E_SYSTEM,
	"Error: System call failed : function %s()." },
    { E_UNITNAME_FMT,
	"Error: coding/decoding unit name : %s, for media ID : %d." },
    { E_UNIT_UNREG,
      "Error: finding unit name : %s, for medias id: %d in database." },
    { E_USAGE,
	"Command line usage error." },
};


/*
 * Determine the number of messages that can be stored.
 */

static int	numMsgs = sizeof( msgs ) / sizeof( MSG );

/*+
************************************************************************
*
*   Function:	formatMessage
*
*   Purpose:
*	Formats a message from the contents of the argument list.
*
*   Values Returned:
*	none
*
************************************************************************
-*/

void	formatMessage
(
    int		status,		/* (in)  Message status number.		*/
    ...				/* (in)  Message arguments.		*/
)
{
    va_list	args;

    va_start( args, status );
    msg_format( msg, PREFIX, numMsgs, msgs, status, args );
    va_end( args );
}

/*+
************************************************************************
*
*   Function:	printMessage
*
*   Purpose:
*	Prints the message in msg to stdout or stderr, depending on 
*	the type.
*
*   Values Returned:
*	none
*
************************************************************************
-*/

void	printMessage
(
    char	*msg,		/* (in)  The message to display.	*/
    int		type		/* (in)  The type of the message.	*/
)
{
    /*
     *  If the message type is MESS_ERROR, print to stderr and the logfile.
     *  If the message type is MESS_INFO, print to the log file, and if in
     *  verbose mode, to stderr.
     *  If the message type is MESS_DATA, print only to the log file.
     */

    if ( type & MESS_LOG )
    {
	if ( globals.gLogFp != NULL )
	{
	    (void) fputs( msg, globals.gLogFp );
	    if ( ! ( type & MESS_NOCR ) )
	    {
		(void) fputc( '\n', globals.gLogFp );
	    }
	}
    }

    if ( globals.gLogFp == NULL || type & MESS_CON || 
	    ( ( type & MESS_CON_VERB ) && globals.gVerbose ) )
    {
	(void) fputs( msg, stdout );
	if ( ! ( type & MESS_NOCR ) )
	{
	    (void) fputc( '\n', stdout );
	}

	(void) fflush( stdout );
    }

    msg_clear( msg );
}
