#!/bin/sh
# the next line restarts using wish \
exec tclsh "$0" "$@"

set __source $argv0

#
# Parse the args
# 	-location "N"orth or "S"outh
#	-site "S"ummit or "B"ase
#	[ -subsystem subsytemList ]
#	[ -file filename ]
#

set dhsFormatString "    %-20s\tDH%1.1s%1.1s:%-22s   \t0  comments"
set subsystemFormatString "    %-20s\tDH%1.1s%1.1s:%3.3s:%-22s\t0  comments"


#
# Initialize the values before parsing the command line args.
#
set longVersion \
"(   S_VERSION)                 mkCaConfig       0.01  (c) 1999 NRC/CNRC"
append longVersion [ format "%40s       %s\n" "" 			\
    "tcl [ clock format [ file mtime $__source ] -format %D(%R) ]" ]
append longVersion [ format "%21s      %s\n" "Tcl/Tk" "[ info patchlevel ]" ]

set validSubsystems "STA QLS HIS DTS CMD STO OLP SDP"

set filename "CA_CONFIG"
set minusFile 0

set subsystems $validSubsystems
set minusSubsystems 0

set location "S"
set minusLocation 0

set site "S"
set minusSite 0

set usageString \
"USAGE:  \[ -location N|S \] \[ -site S|B \] \[ -subsystems ?STA? ?QLS? ?HIS? ?DTS? ?CMD? ?STO? ?OLP? ?SDP? \] \[ -file filename \]"

#
# Find the cmd line args.
#

for { set idx 0 } { $idx < $argc } {} {
    #
    # Get the flag.
    #

    set flag [ lindex $argv $idx ]
    incr idx


    #
    # Get the value if there is one.
    #

    if { $idx < $argc && ! [ string match "-*" [ lindex $argv $idx ] ] } {
	set value [ lindex $argv $idx ]
	incr idx
    } else {
	set value ""
    }


    #
    # Verify correctness.
    #

    switch -exact -- "$flag" {
	"-file" {
	    if { $minusFile == 1 } {
		puts $usageString
		exit 1
	    }
	    set filename "$value"
	    set minusFile 1
	}

	"-help" -
	"?" {
	    puts "$usageString"
	    exit 1
	}

	"-location" {
	    if { ( "$value" != "B" && "$value" != "S" ) ||
		 $minusLocation == 1 } {
		puts $usageString
		exit 1
	    }
	    set location "$value"
	    set minusLocation 1
	}

	"-site" {
	    if { ( "$value" != "N" && "$value" != "S" ) ||
		 $minusSite == 1 } {
		puts $usageString
		exit 1
	    }
	    set site "$value"
	    set minusSite 1
	}

	"-subsystems" {
	    if { $minusSubsystems == 1 } {
		puts $usageString
		exit 1
	    }

	    foreach subsystem "$value" {
		if { [ lsearch $validSubsystems $subsystem ] == -1 } {
		    puts "$usageString"
		    exit 1
		}
	    }

	    set subsystems "$value"
	    set minusSubsystems 1
	}

	"-V" {
	    if { $value != "" } {
		puts "$usageString"
		exit 1
	    } 
	    puts "$longVersion"
	    exit 0
	}

	default {
	    puts "$usageString"
	    exit 1
	}
    }
}


#
# Introductory comments
#

set statusIntro "\#
\# This file was generanted by mkCaConfig
\#
\# Test CA configuration file
\#
\# Apply records need to come first since they are created when encountered
\# in the command entries.  The other sections/entires do not need to occur 
\# in any order.
\#
\# Apply section
\#   one line for each apply record in the form:
\#     apply ocs-name epics-name apply-car-epics-name description-to-end-of-line
\#

\# Status section
\#   first line describes the collection of status records
\#      status ocsName description-to-end-of-line
\#   Then one line for each entry in the status acceptor
\#      ocsName epicsName skipCount description-to-end-of-line
\#
\#   Skip count is the number of updates that will be thrown away before
\#   higher layers are notified.  This is useful for fast (10/second) TCS
\#   time updates. 
\n\n"

set cmdIntro "\# Command Section
\# Each Cad entry starts with an introduction
\#   command ocsName apply-ocsName description-to-end-of-line
\#
\#   Then one line for each entry in the command sender
\#     ocsName epicsName description-to-end-of-line
\#
\# Note: that a command entry can contain fields from many cad records
\#   allowing ocs level command senders that span many cad/systems.
\#\n"


#
# Set status record sizes
#

set numResources 	12
set numStoUnits		20
set numStoStages	10
set numStoActions	15
set numStoDevices	20
set numStoRequests	20
set numOlpJobs		10
set numSdpJobs		10




#
# Open the file that we will be write to.
#

if { [ catch "set fd [ open $filename w ]" errMsg ] } {
    puts "Unable to open file: $filename"
    exit 1
}


#
#  put the status introductory information
#    

puts $fd "$statusIntro"


#
# put the start of the DHS SAD description.
#

puts $fd "status dhsSAD description\n{\n"

#
# Create the DHS records
#

set outputStr "[ format $dhsFormatString dhsLog "$location" "$site" logMessage ]"	
puts $fd "$outputStr"
set outputStr "[ format $dhsFormatString dhsHealth "$location" "$site" health ]"	
puts $fd "$outputStr"
set outputStr "[ format $dhsFormatString dhsState "$location" "$site" "state" ]"	
puts $fd "$outputStr"
set outputStr "[ format $dhsFormatString dhsDebug "$location" "$site" "debug" ]"	
puts $fd "$outputStr"
set outputStr [ format $dhsFormatString dhsSim "$location" "$site" simulate ]
puts $fd "$outputStr"
puts $fd ""

foreach subsystem "$subsystems" {
    set recordList "health healthDesc state debug simulate"
    set aliasList "Health Desc State Debug Sim"
    for { set idx 0 } { $idx < 5 } { incr idx } {
	set record [ lindex $recordList $idx ]
	set alias [ lindex $aliasList $idx ]
	set alias "[string tolower $subsystem]$alias"
	set outputStr [ format $subsystemFormatString "$alias" "$location" "$site" "$subsystem" "$record" ]
	puts $fd "$outputStr"
    }
    puts $fd ""
}
puts $fd ""


#
# Miscellanesous subsystem records
#

if { [ lsearch $subsystems "DTS" ] != -1 } {
    set outputStr [ format $subsystemFormatString dtsInc "$location" "$site" DTS numIncomplete ]
    puts $fd "$outputStr"
}

if { [ lsearch $subsystems "STO" ] != -1 } {
    set outputStr [ format $subsystemFormatString stoAlert "$location" "$site" STO alert ]
    puts $fd "$outputStr"
    puts $fd ""
}



#
# Create the Resource records
#

set outputStr [ format $dhsFormatString resArraySize "$location" "$site" resourceArraySize ]
puts $fd "$outputStr"
puts $fd ""

for { set idx 0 } { $idx < $numResources } { incr idx } {
    foreach resRecord { fullname inUse max name type used units } {
	set upResRecord "[ string toupper [ string range $resRecord 0 0 ] ][ string range $resRecord 1 end ]"
	set alias "res${idx}${upResRecord}"
	set record "resource${idx}:${resRecord}"
	set outputStr [ format $dhsFormatString "$alias" "$location" "$site" "$record" ]
	puts $fd "$outputStr"
    }
    puts $fd ""
}
puts $fd ""


#
# Storage Server Requests
# 
if { [ lsearch $subsystems "STO" ] != -1 } {
    set outputStr [ format $subsystemFormatString stoReqOverflow "$location" "$site" STO reqOverflow ]
    puts $fd "$outputStr"
    
    set outputStr [ format $subsystemFormatString stoReqArraySize "$location" "$site" STO reqArraySize ]
    puts $fd "$outputStr"
    
    set outputStr [ format $subsystemFormatString stoNumReqs "$location" "$site" STO numReqs ]
    puts $fd "$outputStr"

    for { set idx 0 } { $idx < $numStoRequests } { incr idx } {
	foreach reqRecord { inUse reqId reqName reqType mediaType numCopies retrieveSize retrieveState queueState queueSize prepNum prepState writeNum writeState cleanupNum cleanupState notifyValue notifyState } {
	    
	    set upReqRecord "[ string toupper [ string range $reqRecord 0 0 ] ][ string range $reqRecord 1 end ]"
	    set alias "stoReq${idx}${upReqRecord}"
	    set record "req${idx}:${reqRecord}"
	    set outputStr [ format $subsystemFormatString "$alias" "$location" "$site" STO "$record" ]
	    puts $fd "$outputStr"
	}
	puts $fd ""
    }
    puts $fd ""


    #
    # Storage Server Devices
    # 
    
    set outputStr [ format $subsystemFormatString stoDeviceArraySize "$location" "$site" STO deviceArraySize ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString stoNumDevices "$location" "$site" STO numDevices ]
    puts $fd "$outputStr"

    for { set idx 0 } { $idx < $numStoDevices } { incr idx } {
	foreach devRecord { inUse logicalName type typeDesc capacity numDevices available deviceInUse reqId unitName } {

	    set upDevRecord "[ string toupper [ string range $devRecord 0 0 ] ][ string range $devRecord 1 end ]"
	    set alias "stoDevice${idx}${upDevRecord}"
	    set record "device${idx}:${devRecord}"
	    set outputStr [ format $subsystemFormatString "$alias" "$location" "$site" STO "$record" ]
	    puts $fd "$outputStr"
	}
	puts $fd ""
    }
    puts $fd ""


    #
    # Storage Server Stages
    # 

    set outputStr [ format $subsystemFormatString stoStageArraySize "$location" "$site" STO stageArraySize ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString stoNumStages "$location" "$site" STO numStages ]
    puts $fd "$outputStr"

    for { set idx 0 } { $idx < $numStoStages } { incr idx } {
	foreach stageRecord { inUse dirName reqId unitName } {
	    set upStageRecord "[ string toupper [ string range $stageRecord 0 0 ] ][ string range $stageRecord 1 end ]"
	    set alias "stoStage${idx}${upStageRecord}"
	    set record "stage${idx}:${stageRecord}"
	    set outputStr [ format $subsystemFormatString "$alias" "$location" "$site" STO "$record" ]
	    puts $fd "$outputStr"
	}
	puts $fd ""
    }
    puts $fd ""


    #
    # Storage Server Actions
    # 

    set outputStr [ format $subsystemFormatString stoActionOverflow "$location" "$site" STO actionOverflow ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString stoActionArraySize "$location" "$site" STO actionArraySize ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString stoNumActions "$location" "$site" STO numActions ]
    puts $fd "$outputStr"

    for { set idx 0 } { $idx < $numStoActions } { incr idx } {
	foreach actionRecord { inUse position active action reqId option } {
	    set upActionRecord "[ string toupper [ string range $actionRecord 0 0 ] ][ string range $actionRecord 1 end ]"
	    set alias "stoAction${idx}${upActionRecord}"
	    set record "action${idx}:${actionRecord}"
	    set outputStr [ format $subsystemFormatString "$alias" "$location" "$site" STO "$record" ]
	    puts $fd "$outputStr"
	}
	puts $fd ""
    }
    puts $fd ""


    #
    # Storage Server Units
    # 

    set outputStr [ format $subsystemFormatString stoUnitOverflow "$location" "$site" STO unitOverflow ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString stoUnitArraySize "$location" "$site" STO unitArraySize ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString stoNumUnits "$location" "$site" STO numUnits ]
    puts $fd "$outputStr"

    for { set idx 0 } { $idx < $numStoUnits } { incr idx } {
	foreach unitRecord { inUse reqId unitName unitSize prepValue writeNum cleanupValue } {
	    set upUnitRecord "[ string toupper [ string range $unitRecord 0 0 ] ][ string range $unitRecord 1 end ]"
	    set alias "stoUnit${idx}${upUnitRecord}"
	    set record "unit${idx}:${unitRecord}"
	    set outputStr [ format $subsystemFormatString "$alias" "$location" "$site" STO "$record" ]
	    puts $fd "$outputStr"
	}
	puts $fd ""
    }
}


#
# OLP status records
#

if { [ lsearch $subsystems "OLP" ] != -1 } {
    set outputStr [ format $subsystemFormatString olpJobArraySize "$location" "$site" OLP arraySize ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString olpNumActiveJobs "$location" "$site" OLP numActive ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString olpNumJobs "$location" "$site" OLP numJobs ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString olpJobOverflow "$location" "$site" OLP overflow ]
    puts $fd "$outputStr"

    for { set idx 0 } { $idx < $numOlpJobs } { incr idx } {
	foreach olpJobRecord { inUse client desc id name numQueued numRunning numInstances numNodes state } {

	    set upOlpJobRecord "[ string toupper [ string range $olpJobRecord 0 0 ] ][ string range $olpJobRecord 1 end ]"
	    set alias "olpJob${idx}${upOlpJobRecord}"
	    set record "job${idx}:${olpJobRecord}"
	    set outputStr [ format $subsystemFormatString "$alias" "$location" "$site" OLP "$record" ]
	    puts $fd "$outputStr"
	}
	puts $fd ""
    }
}


#
# SDP status records
#

if { [ lsearch $subsystems "SDP" ] != -1 } {
    set outputStr [ format $subsystemFormatString sdpJobArraySize "$location" "$site" SDP arraySize ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString sdpNumJobs "$location" "$site" SDP numJobs ]
    puts $fd "$outputStr"

    set outputStr [ format $subsystemFormatString sdpJobOverflow "$location" "$site" SDP overflow ]
    puts $fd "$outputStr"

    for { set idx 0 } { $idx < $numSdpJobs } { incr idx } {
	foreach sdpJobRecord { inUse client desc id name recipe start type } {

	    set upSdpJobRecord "[ string toupper [ string range $sdpJobRecord 0 0 ] ][ string range $sdpJobRecord 1 end ]"
	    set alias "sdpJob${idx}${upSdpJobRecord}"
	    set record "job${idx}:${sdpJobRecord}"
	    set outputStr [ format $subsystemFormatString "$alias" "$location" "$site" SDP "$record" ]
	    puts $fd "$outputStr"
	}
	puts $fd ""
    }
}


#
# put the end of the DHS SAD description.
#

puts $fd "}\n\n"


#
#  put the command introductory information
#    

puts $fd "$cmdIntro"


#
# Close the file
#

close $fd



exit 0