# Makefile

NAME = dhsStatus
SOURCES = arg.C config.C main.C merger.C msg.C staChannel.C staDhs.C staMonitor.C subscriber.C
LIBS =	-ldhs++ -ldhs -ldhsGen -ldhsSta -lgen -ldb  $(EPICS_LDLIBS)

include ../conf/cxx_bin.mk
