.\"/*+ $Id: dhsClient.1,v 1.1.1.1 2002-11-24 20:21:43 brighton Exp $
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) 1998				(c) 1998
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-	ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME:
.\" dhsClient/doc/dhsClient
.\"
.\" PURPOSE:
.\" Manaul page that describes the DHS  client simulator.
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/09/30 20:31:35  brighton
.\" Imported sources
.\"
.\" Revision 1.1.1.1  2002/02/21 20:23:33  tpaz
.\"
.\"
.\" Revision 1.1.1.1  1999/08/23 19:58:34  cvs-tuc
.\" Initial install into CVS of dhs-0.16
.\"
.\" Revision 1.1  1998/08/06 23:32:28  nhill
.\" Initial revision
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.\"
.TH	dhsClient 1 06/08/98 "NRC"

.SH NAME
dhsClient
\- A test program used to test the client portion of the DHS library.

.SH SYNOPSIS
\fBdhsClient\fR <\fBclientName\fR> <\fBserverAddress\fR> <\fBserverName\fR> 


.SH DESCRIPTION
This program sends test commands and bulk data to a
DHS Server program (usually \fBdhsServer\fR). 

.SH OPERATION
The client name, server address and server name must all be specified.

\fBdhsClient\fR will send a series of commands and bulk data requests
to the specified server, reporting any errors encountered.

If the server is on a different host, the IMP \fBmaster\fR task must
be run on both the client and server hosts before \fBdhsClient\fR is run.

.SH FILES
None

.SH EXAMPLES
.LP
An example which runs \fBdhsClient\fR with the IMP name c1, 
and tells it to use the server with the IMP name s1 on host daxka:
.IP
.B example> dhsClient c1 daxka s1


.SH  ENVIRONMENT VARIABLES
IMP_SCRATCH controls the directory in which the IMP scratch files are created. 
This must match the IMP_SCRATCH environment variable used when running the 
server if the server is on the same host, or when running the IMP \fBmaster\fR
task if the server is on a different host.


.SH SEE ALSO
dhs++Client (1)
.sp
dhsCmdSender (1)
.sp
dhsServer (1)
.sp
dhs++Server (1)


.SH BUGS

.SH AUTHORS
Shannon Jaeger
.br



National Research Council of Canada
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
