.\"/*+
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) <1998>				(c) <1998>
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-	ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME
.\" dhsGet.1
.\"
.\" PURPOSE:
.\" Describe dhsGet.
.\"
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
.\"
.\"
.\" Revision 1.1.1.1  1999/08/23 19:58:20  cvs-tuc
.\" Initial install into CVS of dhs-0.16
.\"
.\" Revision 1.4  1998/08/10 17:39:56  dunn
.\" *** empty log message ***
.\"
.\" Revision 1.3  1997/10/29 21:44:55  jaeger
.\" fixed minor typo's
.\"
.\" Revision 1.2  1997/10/17 18:29:12  dunn
.\" *** empty log message ***
.\"
.\" Revision 1.1  1997/09/26 16:50:22  dunn
.\" Initial revision
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.TH dhsGet  1 17/09/97 "CADC"

.SH NAME

.B dhsGet
\- Requests bulk data.


.SH SYNOPSIS

.B dhsGet
.B -d dataServerIdentityString
.B -ip dataServerIpAddress
[
.B -t RAW|FITS|HEADER
] [
.B -debug NONE|MIN|FULL
] [
.B -dest destinationPath
] [
.B -id dhsGetIdentityString
] [
.B  [-n datasetName] ...-n datasetName
] [
.B -V
]


.SH DESCRIPTION

.B dhsGet 
requests bulk data.  Options on how the data is requested are set in 
the command line.  The data is returned and stored locally.


.SH OPERATION

.B dhsGet
registers with IMP given the command line identity string
.B dhsGetIdentityString.
If no identity string is given then it registers with the 
identity string "dhsGet".
It will then connect to the Data Server 
.B dataServerIdentityString
at the IP address
.B dataServerIpAddress.

All 
.B datasetNames 
listed on the command line will sequentially be requested.
The data type (
.B -t
) can be set, or it will default to RAW.

When data is received it will be written in the current directory unless 
.B -dest
is used and then the data will be written in the directory given.

Any messages or attribute value lists from the Data Server are printed.


.SH OPTIONS

.TP
.B -d dataServerIdentityString
This is the IMP identity of the Data Server that 
.B dhsGet
will connect to.  This
server must already be running.
.TP
.B -d dataServerIpAddr
This is the IP Address of the Data Server that 
.B dhsGet
will connect to.  
.TP
.B -t RAW|FITS|HEADER
Data types.  These are the data types used in the bulk data call to the data
server.  If a data type of 
.B HEADER
is requested and the file requested is not
FITS, then the data will not be retrieved.  The default data type is 
.B RAW.
.TP
.B -debug NONE|MIN|FULL
Debug mode.  Depending on the mode set, it will print off various degrees of 
error messages.  The default mode is NONE.
.TP
.B -dest destinationPath
Destination path.  This is where the data that is retrieved from the Data
Server will be written.  The default is the current directory.
.TP
.B -id dhsGetIdentityString
This is the IMP identity string of this executable.  This is the identity 
string used by IMP to identify this executable.  The default is "dhsGet".
.TP
.B -n datasetName ...-n datasetName
This is the list of dataset names to request from the Data Server.
This list can contain more than one dataset name.  

.TP
.B -V
Version.  Print version number and quit.



.SH EXAMPLES

To request the dataset "m51" from the Data Server called "dataServer" at
daxka :
.IP
.B dhsGet -d dataServer -ip daxka -n m51
.LP
This command will request from the Data Server the dataset m51 as data type
RAW and store it in the current directory with the name m51.

To request datasets "m52", "m53", and "m54" from the same Data Server
all of type FITS to the /tmp directory :
.IP
.B dhsGet -d dataServer -ip 204.174.103.4 -t FITS -n m52 -n m53 -n m54 -dest /tmp
.LP
This command will request from the Data Server the datasets m52-m54 as
data type FITS and store them in /tmp.


To request datasets "m55", from the same Data Server all of type HEADER 
given an IMP identity of "dhsGetHeader" :
.IP
.B dhsGet -d dataServer -ip 204.174.103.4 -id dhsGetHeader -t HEADER -n m55 
.LP
This command will request from the Data Server the dataset m55 as
data type FITS HEADER and store it in the current directory.


.SH DIAGNOSTICS

Returns 0 upon successful completion, otherwise -1.
Prints the command status, any string returned and any attribute value
list from the Data Server.


.SH SEE ALSO

.BR dhsData (1).
.BR dhsPut (1).


.SH BUGS

None.

.SH AUTHORS
Jennifer Dunn

.br



National Research Council
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
