.\"/*+
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) <year>				(c) <year>
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-		ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME
.\" dhsHistory.1
.\"
.\" PURPOSE:
.\" This file servers as the man-page for the DHS History Server. 
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
.\"
.\"
.\" Revision 1.1.1.1  1999/08/23 19:58:22  cvs-tuc
.\" Initial install into CVS of dhs-0.16
.\"
.\" Revision 1.1  1998/07/31 20:57:06  cockayne
.\" Initial revision
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.\"
.\" Ty macro to start an indent for each type def.
.de Ty
.ie n .TP 14n
.el .TP 16n
..
./"
.TH dhsHistory 1 29/09/97 "CADC"


.SH NAME
.B dhsHistory
- Gemini DHS Server for capturing and storing Gemini Systems' history. 

.SH SYNOPSIS
.B dhsHistory
[
.B -debug NONE | MIN | FULL 
] [
.B -simulate
] [
.B -V
]

.SH DESCRIPTION
The History Server is the component of the DHS whose task is to collect the `history' of all Gemini Systems. It responds to a change in the value of a SIR record in the EPICS Status Alarm Database, storing the new value and the time of the value change. 

This history is stored in a raw history file until such time as the History Server receives a command to save the history log. To save the history log, the History Server creates a FITS file from the raw history file, saves it to the DHS Permanent Store, and ingests the raw history file into the DHS Database. The raw file is then purged of the saved history, freeing magnetic disk space.


.SH OPERATION
In its main mode of operation,
.B dhsHistory
runs as a background task, collecting history from the EPICS SAD as it runs. Under normal operations, the only interaction with the History Server is to periodically save the history log. The DHS Operator can cause the History Server to save the history log by using the Save History Log button on the DHS Console's History Subsystem window. This causes a command to be sent to the History Server, indicating that the history log should be saved. 

The History Server manages two database tables in order to store the history records and some summary information. These are described in the 
.B TABLES
section, below. The History Server also requires a runtime configuration file, 
.IR dhsHistory.config . 
The contents of this file are described in the
.B FILES
section, below.

.SH OPTIONS
.TP
.B -debug NONE | MIN | FULL 
Debug mode.  Set the start-up debug mode of the History Server. NONE is the
default. MIN and FULL print debug messages to standard-out.
.TP
.B -simulate
Simulate mode.  Set the start-up simulate mode of the History Server. When 
this flag is set, this History Server operates in simulate mode, responsing 
to commands without acting on them. 
.TP
.B -V
Version.  Print version numbers and quit.

.SH FILES
.SS ~/.dbrc
The
.I ~/.dbrc
file contains information about each database that a user may wish to
reference with programs such as
.B dhsHistory.
An entry in this file contains a server/database pair followed by a
database username and an account password, as such:

.I server database username password

Each item should be separated by whitespace (spaces or tabs.)
If a required database is not included in the
.I ~/.dbrc
file,
.B dhsHistory 
will terminate with an error.

.SS dhsHistory.config
.B dhsHistory
uses a configuration file to set runtime-configurable parameters necessary
to its operation. The following is an example configuration file. (Text 
following a '#' character is treated as a comment and ignored by 
.BR dhsHistory .)

.sp
.nf

#
# Application identification. This keyword specifies the IMP
# name to use when running this program.
#
# Identity      Application 
# Keyword       Identifier
# --------      -----------
#
 
identity        historyServerNS
 
 
#
# IMP information. This keyword specifies the maximum number
# of IMP connections to allow. This must be enough for the
# connection to the DHS Status Server, the Connection to the
# DHS Data Server, and any connections from the DHS Command 
# Server
#
# Imp           Maximum Number
# Keyword       of Connections
# --------      --------------
#
 
imp             4
 
 
#
# Status server identification information. This is the IMP name
# and address of the DHS Status Server to use for logging status 
# and history.
#
# Server        Server's IMP    Host
# Keyword       Identity        Address
# -------       ------------    -------
#
 
statusServer    statusServerNS  daxka
 
 
#
# Data server identification information. This is the DHS Data
# Server that the History Server will use to save the FITS 
# history file to the DHS Permanent Store. 
#
# Data Server   Server's IMP    Host
# Keyword       Identity        Address
# -----------   ------------    -------
#
 
dataServer      dataServerNS    daxka
 
 
#
# Database server and table names. This line indicates the database
# server, database, and tables used by the History Server. 
#
# Database      DB Server       History         History Events  History Labels 
# Keyword       Name            Database        Table           Table
# --------      ---------       --------        -------         -----
#
 
database        SUMMIT          dhs             historyEvents   historyLabels
 
 
#
# Working directory to use for history server's files.  
#
# Directory     Path to 
# Keyword       Directory
# ---------     ---------
#
 
directory       /staging/history
 
 
#
# EPICS Channel Access information - list of channels to monitor.
#
# Channel       Channel
# Keyword       Name
# -------       -------
#
 
 
channel         DHSB:logMessage
channel         GMOS:logMessage

.fi

.SH TABLES
.B dhsHistory
uses database tables to save the history records it saves. There are
two tables, one which maps a time slice to the DHS data label under
which the FITS file containing that time slice of history is saved, 
and one which contains the history event records themselves. 

The name of the Sybase Server on which the database resides, the name 
of the database and the names of the tables themselves are specified 
in the 
.B dhsHistory 
configuration file.

The names of the tables are configurable, but for discussion purposes are 
named below. The following is a minimum list of SYBASE tables that must 
be present for 
.B dhsHistory 
to run correctly:

.TP
.B dhs..historyLabels
.TP
.B dhs..historyEvents

.SH ENVIRONMENT VARIABLES
.B dhsHistory 
uses environment variables to find the configuration files it will 
use to initialize its runtime-configurable parameters. It will first
look in the directory specified by the 
.B DHSHISTORY_CONFIG_DIR 
environment variable. If that variable is not defined, or the configuration
file is not found in that directory, 
.B dhsHistory
will look in the directory specified by the 
.B DEFAULT_CONFIG_DIR
environment variable. If that variable is not defined, or the configuration
file is not found there, then 
.B dhsHistory 
will attempt to find the file in the current directory. If that fails, 
.B dhsHistory
will exit with an error. 

.SH DIAGNOSTICS
.B dhsHistory 
returns 0 upon successful completion, otherwise -1.


.SH SEE ALSO

.BR dhsData (1),
.BR dhsCmdSender (1).


.SH DOCUMENTS

.TP
.B DHS User Manual
.TP
.B ICD 1c - Baseline DHS Interface
.TP
.B ICD 3 - Bulk Data Transfer
.TP
.B ICD 3.2 - The DHS Command Interface
.TP
.B Interprocess Message Passing (IMP) System



.SH BUGS
None known

.SH AUTHORS
Steve Cockayne
.br

National Research Council
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre

