.\"/*+
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"*	Name			: mediaPrep/doc/mediaPrep.1
.\"*
.\"*	Date			: Dec 07, 1998
.\"*
.\"*	SCCS data		: @(#)
.\"*	    Module Name		: mediaPrep.1
.\"*	    Version Number	: 1.1
.\"*	    Release Number	: 1
.\"*	    Last Updated	: 02/10/99
.\"*
.\"*	Written by		: Shannon Jaeger
.\"*
.\"*	Modification History:
.\"*	    98/12/07 SDJ	: Copied from cdPrep.
.\"*	    99/02/03 SDJ	: Updated to reflect changes in AM library.
.\"*				  Also added security and example section.
.\"*
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"************************************************************************
.\"-*/
.TH MEDIAPREP 1 07/12/1998 "CADC"


.SH NAME
.B mediaPrep
\- Makes ready a media unit for writing.  This may involve anything from 
supplying a list of files on the media unit to preparing a physical image 
of the media on magnetic disk.

.SH SYNOPSIS
.B mediaPrep
.B \-i 
.I mediaId
.B \-n
.I mediaName
.B \-d
.I directory
[
.B \-V
] [
.B \-v
] 
 
.SH DESCRIPTION
.B mediaPrep
prepares, or makes ready, a unit of media for writing.  Two 
directories are used to prepare the data.  One directory is in the
.B Media Data stage 
and the other in the 
.B Retrieval Data stage.  The
.B \-d
command-line argument specifies the name of the two directories.
The location of the 
.B Media 
and 
.B Retrieval Data Stages
are given in the
.B am
library configuration file.

The directory in the 
.B Retrieval Data Stage 
will contain a number of UNIX
hard links to the actual data in the retrieval area.  The directory in
the
.B Media Data Stage 
may or may not contain a physical image of the media.  

The preparation phase is different for each type of media as follows:
.PP
.RS 8
.PD 0
.ta 4c 9c
.TP
.I		directory of
.TP
.I media type	physical image	   hard links
.ta 5c 10c
.TP 4
   tape	no	yes
.TP 4
   CD-ROM	yes	yes
.TP 4
   DVD-R	???	yes
.RE
.PD 1
.PP


.B mediaPrep 
calls a script which is responsible for creation of the
physical image, if one is required.  
The script and its configuration file are listed in the
.B am
library's
configuration file,
.I libam.config.
If no physical image then 
\fInone\fR must be given in the 
.B am
library's configuration file, no attempt's will be made to
call the script if this is the case.
This script itself may, in turn, use media authoring software such as
.B GEAR
or 
.B mkisofs
to create the physical image.
The script is executed within an
.B xterm
which is spawned by
.B mediaPrep.


.B mediaPrep
keeps a full log of its activities in the file:
 
.I mediaPrep.mediaId.mediaName.log

which is created in the current working directory.
The script also keeps a full log of its activities in the file

.I MP_mediaId.mediaName.log
 
which is created in the Media Data Stage Directory.

Before
.B mediaPrep
is run, the files must be grouped together into 'unit(s) of media'.
This grouping is performed by
.B mediaQueue.
Once the media has been fully prepared another application such as
.B mediaWrite
can be used to create  the media.

.B mediaPrep
performs some error checking on the files, and ensures they still
exist in the 
.B Retrieval Data Stage
before preparing the media.

.SH OPERATION
The parameters
.B \-i
.I mediaId,
.B \-n
.I mediaName,
and
.B \-d
.I directory
must all be specified on the command-line, or 
.B mediaPrep
will exit with an error.  
 
.SH OPTIONS
.TP
.B -v
Verbose.  Print all information and error messages to standard out,
.I stdout.
.TP
.B -V
Version.  Print version numbers and quit.
.TP
.B -? -h -help
Help.     Print command-line usage message and quit.
 
.SH USAGE
.B mediaPrep
may require operator input depending on the script and the media authoring
software used by the script.  However, 
.B mediaPrep
typically needs no operator input.

.SH EXAMPLES
.TP 3
.B 1.
The following example shows  how
.B mediaPrep 
will typically run.  A given
media unit is prepared in a given staging area.
.RS 5 
.sp 1n
.nf
.BR "example% mediaPrep \-i " 1 " \-d " staging0 " \-n " USER1_002
.IB "messages from " mediaPrep
.sp 1n
.fi
.RE
.RS 3
The data will be prepared for media unit
.B USER1_002,
which belongs to media request
.B 1.
The prepared data will be placed in the 
.B staging0
subdirectory which resides in the Media Data Stage.
.RE
.TP 3
.B 2.
The following  example is run in verbose mode.  This means 
all activities of 
.B mediaPrep
will be displayed on standard output for the operator to see.
.RS 5
.sp 1n
.ft
.nf
.BR "example% mediaPrep \-i " 3 " \-d " staging3 " \-n " ARCHIVE3\_001 " \-v"
.IB "messages from " mediaPrep
.sp 1n
.fi
.RE
.RS 3
The data will be prepared for media unit
.B ARCHIVE3_001,
which belongs to media request
.B 3.
The prepared data will be placed in the
.B staging3
subdirectory which resides in the Media Data Stage.
.RE

.SH FILES
.SS ~/.dbrc
The
.I ~/.dbrc
file contains information about each database that a user may 
reference with executables such as 
.BR mediaPrep .
More specifically it contains information about SYBASE servers, 
databases, user names and associated passwords. 

A database reference must contain a server/database pair followed
by the user's name and password. Each line of the 
.I ~/.dbrc
file must contain a complete server/database reference for every 
database which may be accessed through this file. Each line of
this file must be arranged in the following order:
 
.I server database username password

Each item should be separated by whitespace (spaces and/or tabs).
If a required database is not included in the 
.I ~/.dbrc 
file, 
.B mediaPrep
will prompt for a user's name and password.
 

.SS libAm.config
.B mediaPrep
uses the CADC
.B Archive Media 
.RB ( am )
library which requires its own configuration file.  Refer
to the 
.B am
man page for more information on this file.
 
.SH SECURITY
In order to ensure a secure
.I ~/.dbrc
file,
.B mediaPrep
requires that the
file resides in the directory specified by the 
.B HOME 
environment variable, and the file protection must restrict read and write 
access to the file owner. 

.SH TABLES
.B mediaPrep
uses the CADC 
.B Archive Media
.RB ( am )
database tables to verify it can perform the task
indicated by the command-line parameters, and
updates the 
.B am
database to indicate completeness of its task.
The location of the 
.am 
database and the names of the tables
are specified in the configuration file for the CADC 
.B am
library.  These tables must be present for
.B mediaPrep
to run correctly.


.SH TABLES
.B mediaPrep
gets the information necessary to prepare media units from the 
.B Archive Media
.RB ( am )
database tables.  The location of the 
.B am 
database, and the name of the
tables are specified in the configuration file for the 
.RB ( am )
library. These tables must exist for 
.B mediaPrep
to run correctly.

The following is a list of SYBASE tables that must be present for 
.B mediaPrep
to run correctly:
.TP
.B mediaArchive..media
.TP
.B mediaArchive..media_files
.TP
.B mediaArchive..media_units
.TP
.B mediaArchive..media_stages
.TP
.B mediaArchive..devices
.TP
.B mediaArchive..book
 
.SH ENVIRONMENT VARIABLES
The environment variable 
.B LIBAM_CONFIG_DIR
may be set to the path of the directory where the 
.B am
library configuration file can be found. If
.B LIBAM_CONFIG_DIR
is not set, the environment variable
.B DEFAULT_CONFIG_DIR
should be set to the path where the file can be found.
 
The environment variable
.B DISPLAY
must be set.  This environment variable indicates which X
server should be used by the
.B xterm. 
In many cases this 
environment variable is set automatically by the login 
environment. However, there are some situations where it may be necessary 
to set the environment variable explicitly, such as remote logins.

The environment variable
.B HOME
must be set to the user's home directory.  If this environment variable
is not set correctly,
.B mediaPrep
may not find the correct
.I~/.dbrc
file containing database information.


The shell path variable
should include the locations of the
.B xterm  
executable, the media authoring software
and the script indicated in the
.I libAm.config
configuration file with the 
.B scripts
keyword.  For more information see the shell's man page.

.SH DIAGNOSTICS
.B mediaPrep
returns a 0 to the calling environment upon successful completion.
Otherwise a non-zero number is returned. 
 
.SH SEE ALSO
.BR mediaQueue(1),
.BR mediaWrite(1),
.BR cdPrepRunGear\-33(1),
.BR cdPrepRunMkisofs\-111(1),
.BR mkisofs(8),
.BR am(3), 
and
.BR db(3).


.B User Manual for MEDIA authoring software. 
 
.SH BUGS
None known.

.SH AUTHOR
Shannon Jaeger
.br

 
National Research Council of Canada
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre

