/*+
************************************************************************
****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
*
* (c) 1998.				(c) 1998.
* National Research Council		Conseil national de recherches
* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
* All rights reserved			Tous droits reserves
* 					
* NRC disclaims any warranties,		Le CNRC denie toute garantie
* expressed, implied, or statu-		enoncee, implicite ou legale,
* tory, of any kind with respect	de quelque nature que se soit,
* to the software, including		concernant le logiciel, y com-
* without limitation any war-		pris sans restriction toute
* ranty of merchantability or		garantie de valeur marchande
* fitness for a particular pur-		ou de pertinence pour un usage
* pose.  NRC shall not be liable	particulier.  Le CNRC ne
* in any event for any damages,		pourra en aucun cas etre tenu
* whether direct or indirect,		responsable de tout dommage,
* special or general, consequen-	direct ou indirect, particul-
* tial or incidental, arising		ier ou general, accessoire ou
* from the use of the software.		fortuit, resultant de l'utili-
* 					sation du logiciel.
*
************************************************************************
*
*   Module Name:	mediaPrep/src/msg.c
*
*   Purpose:
*	Routines for handling message to log file, user's terminal.
*
*   Routines:
*	void	formatMessage	: Format a message.
*	void	printMessage	: Print a message.
*
*   Date		: Sep 09, 1998
*
*   SCCS data		: @(#)
*	Module Name	: msg.c
*	Version Number	: 1.9
*	Release Number	: 1
*	Last Updated	: 03/17/00
*
*   Programmer		: Shannon Jaeger
*
*   Modification History:
*	98/09/09 SDJ	: Copied from cdPrep
*       98/11/23 SDJ  	: Made messages more generic (no mention of gear)
*                         and all error messages consistent.
*       99/01/06 SDJ  	: Added S_SUCCESS, E_EMPTY_DIR, and E_LINK msgs.
*	99/03/08 NRH	: Added support for rollback.
*	99/03/18 NRH	: Added S_SCRIPT_LOG and S_SCRIPT_LOG_DATA.
*	99/04/06 NRH	: Fixed the arguments in the E_FORK_N_EXEC message.
*	99/04/15 SDJ	: Added S_SCRIPT_END.  Edited S_SCRIPT_LOG.
*	99/04/20 SDJ	: Added quotes around the arguments in E_FORK_N_EXEC
*			  to make it easy to paste them onto a command line.
*     2000/03/17 SDJ	: Re worded some of the messages.  Added
*			  S_EXEC_COMMAND.
*
****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
************************************************************************
-*/


/*
 ************************************************************************
 *  General unix include files.
 ************************************************************************
 */
 
#include <unistd.h>
#include <stdarg.h>
 

/*
 ************************************************************************
 *  SYBASE DB libarary include files.
 ************************************************************************
 */
 
#include <sybfront.h>
#include <sybdb.h>
 

/*
 ************************************************************************
 *  CADC library include files.
 ************************************************************************
 */
 
#include "gen_types.h"
#include "gen_str.h"
#include "gen_msg.h"
#include "gen_eptr.h"
#include "gen_config.h"
#include "am.h"
 
 
/*
 ************************************************************************
 *  Media Prep include files.
 ************************************************************************
 */

#include "globals.h"


/*
 ************************************************************************
 * Constatns definitions
 ************************************************************************
 */

#define	PREFIX	"mp"


/*
 ************************************************************************
 *  data types 
 ************************************************************************
 */
 
/*
 * Create a place to store the sf messages.
 */

char	msg[MSG_MAX_LEN];


/*
 * Define the status messages.
 */

static MSG	msgs[] = {
    { S_BEGINNING,
	"Beginning preparing of media unit:  %s." },
    { S_CANT_PREP,
        "Can't prepare media yet. Not all data is properly in Media Stage area." },
    { S_COMPLETE,
        "Completed preparing media unit '%s'." },
    { S_CONTINUING,
	"Continuing preparing of media unit: %s." },
    { S_EXEC_COMMAND,
      "Executing command: %s %s" },
    { S_MP_SIGNAL,
      "mediaPrep handling signal, quitting prep script if necessary." },
    { S_QUIT,
      "Quit a user's request." },
    { S_ROLLBACK,
	"Rollback of unit `%s' in media request %d started." },
    { S_ROLLBACK_DONE,
	"Rollback of unit `%s' in media request %d complete." },
    { S_SCRIPT_END,
    	"*******************************************************************\n"
        "*                                                                 *\n"
        "* End of the log file generated by: %20s.         *\n"
        "*                                                                 *\n"
      	"*******************************************************************" },
    { S_SCRIPT_ERR,
        "The prep script's log file reports errors in preparing.  Please investigate." },
    { S_SCRIPT_LOG,
    	"*******************************************************************\n"
        "*                                                                 *\n"
        "* Following is the log file generated by: %20s.   *\n"
        "*                                                                 *\n"
      	"*******************************************************************" },
    { S_SCRIPT_LOG_DATA,
	"%s" },
    { S_SCRIPT_PHYSVOLS,
        "The prep script's log file reports that %d media units were prepared." },
    { S_STATS,
	"Unit Files Summary: %s: \n"
	"                    %6d Total files               \n"
	"                    %6d Files in Retrieval Stage  \n"
	"                    %6d Files Queued		   \n"
	"                    %6d Files require re-retrieval\n"
	"                    %6d Files have an un-processable status" },
    { S_USAGE,
	"Usage: mediaPrep -i <media ID> -n <unit name> 			\n"
	"                     { -d <directory> | -rollaback } [options] \n"
	"                 <directory>   - A valid Media Data Stage directory.\n"
	"                 <media ID>    - A valid media ID integer.          \n"
	"                 <unit name>   - A valid media unit name.           \n"
	"                 [-help]       - Print this message.                \n"
	"                 [-v]          - Verbose mode.                      \n"
	"                 [-V]          - Print version and exit." },
    { S_VERSION,
	"%s" },
    { E_AM,
	"Error: am library reports an error." },
    { E_BAD_F_STATUS,
	"Error: file '%s' cannot be processed.  Status '%s'." },
    { E_BAD_U_STATUS,
	"Error: mediaPrep cannot process unit with status '%s'." },
    { E_CONFIG,
	"Error: reading from configuration file." },
    { E_DATA_STAGE,
	"Error: Data stage for %d: %s." },
    { E_DB,
      "Error: SYBASE db library reports errors." },
    { E_DB_LIB,
	"Error: CADC db library reports errors." },
    { E_DISPLAY,
        "Error: DISPLAY environment variable must be set." },
    { E_EMPTY_DIR,
        "Error: `%s' can not be emptied." },
    { E_EXEC_ABNORMAL_EXIT,
	"Error: Abnormal exit from exec() while executing %s." },
    { E_EXEC_NONZERO_EXIT,
	"Error: %s returned nonzero status, %d." },
    { E_FILESIZE,
	"Error: with the filesize, eh? %i %d %s" },
    { E_FORK_N_EXEC,
	"Error: fork() and exec() when attempting to execute: %s." },
    { E_LINK,
      "Error: Unable to create hard link to file `%s'." },
    { E_LOG_FMT,
        "Error: getting information from the Prep script's log file." },
    { E_MEMORY,
        "Error: Memory allocation failure." },
    { E_NO_DEVICE,
        "Error: No matching devices for %s." },
    { E_NO_FILES,
	"Error: No db file entries for media ID : %d, unit: %s." },
    { E_NO_MEDIA,
	"Error: No db device for media type : %s." },
    { E_NO_UNIT,
	"Error: No db unit entry for media ID : %d, unit: %s." },
    { E_NOT_COMPLETE,
        "Preparing of physical image not complete.  A total of %d files have\n"
        "been prepared. The media table expects %d files to be prepared.\n"
        "Please investigate and re-run mediaPrep. " },
    { E_ONLY_ONE,
	"Error: mediaPrep already running.  Only one permitted per media unit." },
    { E_OTHER_UNIT,
	"Error: Another unit is already using Media Data Stage dir : %s." },
    { E_STAGE_DIR,
	"Error: Not a directory: '%s'." },
    { E_SYSTEM,
	"Error: System call failed : function %s()." },
    { E_UNITNAME_FMT,
	"Error: coding/decoding unit name : %s, for media ID : %d." },
    { E_USAGE,
	"Command line usage error." },
    { E_WRONG_DIR,
	"Error: Unit already started in Media Data Stage directory: %s." },
};


/*
 * Determine the number of messages that can be stored.
 */

static int	numMsgs = sizeof( msgs ) / sizeof( MSG );

/*+
************************************************************************
*
*   Function:	formatMessage
*
*   Purpose:
*	Formats a message from the contents of the argument list.
*
*   Values Returned:
*	none
*
************************************************************************
-*/

void	formatMessage
(
    int		status,		/* (in)  Message status number.		*/
    ...				/* (in)  Message arguments.		*/
)
{
    va_list	args;

    va_start( args, status );
    msg_format( msg, PREFIX, numMsgs, msgs, status, args );
    va_end( args );
}

/*+
************************************************************************
*
*   Function:	printMessage
*
*   Purpose:
*	Prints the message in msg to stdout or stderr, depending on 
*	the type.
*
*   Values Returned:
*	none
*
************************************************************************
-*/

void	printMessage
(
    char	*msg,		/* (in)  The message to display.	*/
    int		type		/* (in)  The type of the message.	*/
)
{
    /*
     *  If the message type is MESS_ERROR, print to stderr and the logfile.
     *  If the message type is MESS_INFO, print to the log file, and if in
     *  verbose mode, to stderr.
     *  If the message type is MESS_DATA, print only to the log file.
     */

    if ( type & MESS_LOG )
    {
	if ( globals.gLogFp != NULL )
	{
	    (void) fputs( msg, globals.gLogFp );
	    if ( ! ( type & MESS_NOCR ) )
	    {
		(void) fputc( '\n', globals.gLogFp );
	    }
	}
    }

    if ( globals.gLogFp == NULL || type & MESS_CON || 
	    ( ( type & MESS_CON_VERB ) && globals.gVerbose ) )
    {
	(void) fputs( msg, stdout );
	if ( ! ( type & MESS_NOCR ) )
	{
	    (void) fputc( '\n', stdout );
	}

	(void) fflush( stdout );
    }

    msg_clear( msg );
}
