.\"/*+
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"*	Name:			: cd/doc/cdWriteRunGear.1
.\"*
.\"*	Purpose:
.\"*	    Manpage for cdWriteRunGear.
.\"*
.\"*	Date:			: Mar 1, 1998
.\"*
.\"*	SCCS data		: %Z%
.\"*	    Module Name		: %M%
.\"*	    Version Number	: %I%
.\"*	    Release Number	: %R%
.\"*	    Last Updated	: %G%
.\"*
.\"*	Written by		: Shannon Jaeger
.\"*
.\"*	Modification History:
.\"*	   98/03/01 SDJ		: Copied from cdMake (vlt project).
.\"*	   99/02/24 SDJ		: Changed command-line arguments to take
.\"*				  the data path.
.\"*
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"************************************************************************
.\"-*/
.TH CDWRITERUNGEAR\-33 1 17/12/98 "CADC"
 
.SH NAME
.B cdWriteRunGear\-33
\- runs Elektroson's GEAR software to write CD\-ROM(s).
 
.SH SYNOPSIS
.B cdWriteRunGear\-33
.I volume\-name gearrc\-file\-path log\-file\-path
.I gear\-work\-path device\-information num\-copies data\-path


.SH DESCRIPTION
.B cdWriteRunGear\-33
is a script that runs Elektroson's GEAR software to write one or more
CD\-ROM(s). This script assumes that a single CD\-writer is to be
used and that no stacker is used, so the operator must manually place
CD\-ROMs into the CD\-writer.

This script parses the device specific information provided 
by the
.I device\-information
command\-line parameter.  The information that is used includes:
.RS 4
.nf
SCSI bus,
target,
read speed, and
write.
.fi
.RE
These values are used to replace the appropriate values in the
.I .gearrc
file in order to ensure that the given device is used.

This script was written to work with an application such as
.B cdWrite
or 
.B mediaWrite
which interface with SYBASE.

.SH OPERATION
.B cdWriteRunGear\-33 
requires seven command\-line parameters:
.TP
.I volume\-name:      
Name of disk in upper\-case
.TP
.I gearrc\-file\-path: 
Fully specified path and name of gearrc file
.TP
.I log\-file\-path:    
Fully specified path and name of log file
.TP
.I gear\-work\-path:   
Fully specified path to the work directory. This directory contains
the physical image of the CD\-ROM to be written.
.TP
.I device\-information:
The device information includes the following: 
.RS 8
.nf
1. \fBSCSI bus\fR the CD\-writer is located on,
2. \fBtarget\fR number of the device,
3. \fBlogical unit number\fR of the device,
4. the \fBread speed\fR of the device,
5. the \fBwrite speed\fR of the device, and
6. the \fBdriver\fR to be used with the device.
.fi
.RE
.sp 1
.RS 5
All of these values
are expected to be separated with commas in the order they have been 
listed.
.RE
.TP
.I num\-copies:       
Number of copies to make
.TP
.I data\-path:
Fully specified path to the directory of data.  This directory contains
the data which will burned onto the CD\-ROM.  This argument is not used
by the script but exists to maintain compatibility with other media 
writing scripts.

.SH OPTIONS
There are no optional command\-line arguments for
.B cdWriteRunGear\-33
 
.SH USAGE
.B cdWriteRunGear\-33
will require some operator input.  The operator will be prompted
whenever a new CD\-ROM needs to be placed in the CD\-writer.
The GEAR software will also ask if the operator wishes to change
any of the settings before the CD\-ROM is burned.  GEAR may also prompt
for other information.

.SH EXAMPLES
.TP 3
The following example demonstrates how to use
.B cdWriteRunGear\-33
.RS 5
.sp 1n
.nf
.BR "example% cdWriteRunGear\-33 " USER1_002 " " /dot_file/gearrc " " /logs/cdWrite
.BR "        " /staging/media/staging3 " " 2,3,0,4,6,none " " 2
.BR "        " /staging/user/staging3
.sp 1n
.fi
.RE
.RS 3
In this example copies of volume (unit) 
.B USER1_002,
which is located in
.I /staging/media/staging3
will be written. The configuration file is located at
.I /dot_files/gearrc
and the log file is located
at
.I /logs/cdWrite.
Finally, the device information tells us that there is no driver to
be used.  The device is located on SCSI Bus 2, target 3, and logical
unit number 0.  The device reads at 6x speed and writes at 4x speed.
.RE

.SH ENVIRONMENT VARIABLES
The shell's path variable
should include the locations of the GEAR,
.B gear
executable, the Elektroson CD\-ROM authoring software.
 
.SH DIAGNOSTICS
.B cdWriteRunGear\-33
returns a 0 to the calling environment upon successful completion.
Otherwise a non\-zero number is returned. 
 
.SH SEE ALSO
.BR cdWrite (1),
.BR mediaWrite (1).
 
.B GEAR for UNIX User's Manual, Elektroson USA
 
.SH BUGS
None known.
 
.SH AUTHOR
Shannon Jaeger
.br

National Research Council of Canada 
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
