# Makefile

NAME = dhsQlServer
SOURCES = arg.C config.C main.C msg.C qlsBufIndex.C qlsDataset.C qlsDhs.C qlsDsCommands.C qlsFitsKeyword.C qlsFrame.C qlsMaster.C qlsQlt.C qlsSlave.C qlsStream.C sequenceCommands.C streamCommands.C
LIBS = -ldhs++ -ldhs -ldhsGen -ldhsSta -lgen $(TCLTK_LDLIBS)

include ../conf/cxx_bin.mk
