.\"/*+ $Id: dhsSim4Data.1,v 1.1.1.1 2002-11-24 20:30:13 brighton Exp $
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) 1998				(c) 1998
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-	ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME:
.\" dhsSim4Data/doc/dhsSim4Data.1
.\"
.\" PURPOSE:
.\" Manaul page that described the DHS simulator used by the
.\" Data Server.
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
.\"
.\"
.\" Revision 1.1.1.1  1999/08/23 19:58:37  cvs-tuc
.\" Initial install into CVS of dhs-0.16
.\"
.\" Revision 1.2  1998/08/10 18:04:42  dunn
.\" *** empty log message ***
.\"
.\" Revision 1.1  1998/08/10 03:48:17  dunn
.\" Initial revision
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.\"
.TH	dhsSim4Data 1 06/08/98 "NRC"

.SH NAME
dhsSim4Data
\- A DHS simulator of a Storage, Quick Look, and OLDP Server for the Data Server.

.SH SYNOPSIS
.B dhsSim4Data

[
.B -debug [NONE|MIN|FULL]
] [
.B -notify
] 

.SH DESCRIPTION
.B dhsSim4Data
simulates a Storage, Quick Look and OLDP Server. It will accept 
connections, 3 commands (fileAvail, stoArchiveFileAvailable, 
qlsDsStream), and FITS bulk data.
 

.SH OPERATION
.B dhsSim4Data
will accept the fileAvail command that an OLDP Server would receive from the
Data Server.  It expects an attribute value list with 
an attribute called "fileId".  The value is printed and a 
response is sent back.

.B dhsSim4Data 
will also accept the stoArchiveFileAvailable command that a Storage Server would 
receive.  It extracts 3 attributes from the attribute value list:
fileId, fileSize, and segregationDir.  The values are printed and a response
is returned.  If the server was started with the 
.B -notify
option, then 
.B dhsSim4Data 
will respond immediately to the Data Server that the file has been archived.

Acting as a Quick Look Server, 
.B dhsSim4Data
will accept a qlsDsStream command.  It will expect two attributes in the 
attribute value list: dataset and streams.  The values are printed and
a response is returned.

.B dhsSim4Data
will accept FITS bulk data.  A message will be printed to indicate
that data was received, but the data will not be saved.  A successful response
will be returned.

.SH OPTIONS

.TP
.B -debug NONE | MIN | FULL 
Debug mode.  Depending on the mode set, it will print off various degrees of 
error messages.  
.TP
.B -notify
Set the notification flag.  When 
a stoArchiveFileAvailable command is received and responded to, 
.B dhsSim4Data
will immediately send notification back to the Data Server that the file
has been archived.


.SH FILES

.TP
.B dhsSim4Data.config
dhsSim4Data
also requires a configuration file
to set some parameters necessary for its operation. 
The following is an example configuration file.
(Text followed by a '#' is treated as a comment and ignored by
.B dhsSim4Data
).

.sp
.nf

#
#  Application identity
#
# Keyword       application 
#               identity
# -------       -----------
#

identity        dhsSim4Data


#
#  Imp information
#
# keyword       Maximum #
#               of connections
# --------      --------------
#

imp                 13


#
#  Data Server information
#
# Keyword       dataServer      dataServer
#               identity        IP Address
# -------       ----------      ----------
#

dataServer      dataServer      daxka

.fi


.SH  ENVIRONMENT VARIABLES

Upon startup, dhsSim4Data
looks for its configuration file in the directory specified by the 
environment variable
.B DHSSIM4DATA_CONFIG_DIR.
If not defined, it looks for the 
.B DEFAULT_CONFIG_DIR 
and finally will look in the current directory.

.SH SEE ALSO
.BR dhsData (1).

.SH BUGS

.SH AUTHORS
Jennifer Dunn
Shannon Jaeger
.br



National Research Council of Canada
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
