#!/bin/bash

if [ $# != 1 ]; then
   echo "Usage: GemBootStart [start|stop|server]"
   exit 1
fi

case $1 in
   server)
      GemBootStart stop &>/dev/null
      rm -fr $DHS_STAGING/temp
      mkdir -p $DHS_STAGING/temp 
      [ -d $DHS_STAGING/perm ] || mkdir -p $DHS_STAGING/perm
      sleep 1
      if [ "`ps aux |grep master |grep -v grep`" = "" ]; then
            master &
            sleep 1
      else
            echo ""
            echo "IMP master was already started (presumably either by"
            echo "/etc/init.d/imp_startup or by seqexec.sh). Omitting it here,"
            echo "which should be okay."
            echo ""
      fi
      dhsSim4Data &
      sleep 1
      dhsStatus &
      sleep 1
      dhsData -debug FULL NO_DHS -noDb -temp $DHS_STAGING/temp -perm $DHS_STAGING/perm &
      sleep 1
      dhsQlServer -master&
      sleep 1
      dhsCommand &
      ;;
   start)
      GemBootStart stop &>/dev/null
      if [ "`ps aux |grep master |grep -v grep`" = "" ]; then
            master &
            sleep 1
      else
            echo ""
            echo "IMP master was already started (presumably either by"
            echo "/etc/init.d/imp_startup or by seqexec.sh). Omitting it here,"
            echo "which should be okay."
            echo ""
      fi
      dhsQlServer &
      ;;
   stop)
      ## fkraemer - don't execute cleanup here since IMP might still be in use
      ## by seqexec.sh or other dhs clients
      # cleanup
      find /tmp -type d -user $DHS_USER -name 'dhs*' -print -exec rm -fr '{}' \; >& /dev/null
      rm -fr $DHS_STAGING/temp
#     for i in dhsSim4Data dhsStatus dhsData dhsQlServer; do
#		killall $i
#     done
      ;;
   *)
      echo "Usage: GemBootStart [server|start|stop]"
      exit 1
      ;;
esac
