#!/bin/bash

if [ $# != 1 ]; then
   echo "Usage: GemBootStart [start|stop|server]"
   exit 1
fi

case $1 in
   server)
      GemBootStart stop &>/dev/null
      rm -fr $DHS_STAGING
      mkdir -p $DHS_STAGING/temp $DHS_STAGING/perm
      sleep 1
      master &
      sleep 1
      dhsSim4Data &
      sleep 1
      dhsStatus -simulate FULL&
      sleep 1
      #dhsData -debug FULL NO_DHS -noServers -noDb -temp $DHS_STAGING/temp -perm $DHS_STAGING/perm&
      # -noDb implied -noParse, no need to specify it
      # -noDb only works if -temp and -perm are given on the command line
      dhsData -debug FULL NO_DHS -noDb -temp $DHS_STAGING/temp -perm $DHS_STAGING/perm &
      sleep 1
      #dhsQlServer -master -debug NONE -simulate&
      dhsQlServer -master -debug NONE&
      ;;
   start)
      GemBootStart stop &>/dev/null
      master &
      ;;
   stop)
      cleanup
      find /tmp -type d -user $DHS_USER -name 'dhs*' -print -exec rm -fr '{}' \; >& /dev/null
      rm -fr $DHS_STAGING
#     for i in dhsSim4Data dhsStatus dhsData dhsQlServer; do
#		killall $i
#     done
      ;;
   *)
      echo "Usage: GemBootStart [server|start|stop]"
      exit 1
      ;;
esac
