#!/bin/bash

if [ $# != 1 ]; then
   echo "Usage: GemBootStart [start|stop|server]"
   exit 1
fi

dhs_start() {
        PROG=$1
        BASE=`basename $PROG`
        if [ $# -ge 2 ]
        then
                shift
                ARGS=" $*"
        else
                ARGS=""
        fi

        echo "dhs_start: Starting $PROG$ARGS"
        #$SU$PROG$ARGS >> $LOG 2>&1 < /dev/null &
        BASEPROG=`basename $PROG`
        $SU$PROG$ARGS < /dev/null 2>&1 | logger -p local0.debug -t $BASEPROG &
        sleep 1
}


case $1 in
   server)
      GemBootStart stop &>/dev/null
      rm -fr $DHS_STAGING/temp
      mkdir -p $DHS_STAGING/temp 
      [ -d $DHS_STAGING/perm ] || mkdir -p $DHS_STAGING/perm
      sleep 1
      if /etc/init.d/imp_master status | grep "is running" &>/dev/null ; then
            echo ""
            echo "IMP master was already started."
            echo ""
      else
         /etc/init.d/imp_master start
         sleep 1
      fi
      dhs_start dhsSim4Data
      sleep 1
      dhs_start dhsStatus
      sleep 1
      dhs_start dhsData -debug FULL NO_DHS -noDb -temp $DHS_STAGING/temp -perm $DHS_STAGING/perm
      sleep 1
      dhs_start dhsQlServer -master
      sleep 1
      dhs_start dhsCommand
      ;;
   start)
      GemBootStart stop &>/dev/null
      if [ "`ps aux |grep master |grep -v grep`" = "" ]; then
            master &
            sleep 1
      else
            echo ""
            echo "IMP master was already started (presumably either by"
            echo "/etc/init.d/imp_startup or by seqexec.sh). Omitting it here,"
            echo "which should be okay."
            echo ""
      fi
      dhsQlServer &
      ;;
   stop)
      ## fkraemer - don't execute cleanup here since IMP might still be in use
      ## by seqexec.sh or other dhs clients
      # cleanup
      find /tmp -type d -user $DHS_USER -name 'dhs*' -print -exec rm -fr '{}' \; >& /dev/null
      rm -fr $DHS_STAGING/temp
#     for i in dhsSim4Data dhsStatus dhsData dhsQlServer; do
#		killall $i
#     done
      ;;
   *)
      echo "Usage: GemBootStart [server|start|stop]"
      exit 1
      ;;
esac
