#!/bin/tcsh
if ( $#argv != 1 ) then
	echo "usage: MakePrImages <program>"
	exit
endif
set program = $1

#
# Copy the processed files.
#

  foreach file (/staging/data/PR_images/*)
	if ( -f $file ) then
		dhsStoPut -copies 2 -prefix ${program}- -user $program 		\
			-f $file PR_images/$file:t
	endif
end
