.\"/*+
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) <year>				(c) <year>
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-		ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME
.\" dhsCommand.1
.\"
.\" PURPOSE:
.\" Describe the DHS Command Server.
.\"
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/02/21 20:23:33  tpaz
.\"
.\"
.\" Revision 1.1.1.1  1999/08/23 19:58:08  cvs-tuc
.\" Initial install into CVS of dhs-0.16
.\"
.\" Revision 1.2  1998/07/02 19:58:43  nhill
.\" Fixed spelling
.\"
.\" Revision 1.1  1998/07/02 19:35:28  nhill
.\" Initial revision
.\"
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.\"
.                       \" Ty macro to start an indent for each type def.
.de Ty
.ie n .TP 14n
.el .TP 16n
..
./"
.TH dhsCommand  1 2/7/98 "CADC"

.SH NAME

dhsCommand
\- Server for commands to DHS subsystems


.SH SYNOPSIS

.B dhsCommand 
[
.B -debug NONE | MIN | FULL 
] [
.B -simulate
] [
.B -V
] 

.SH DESCRIPTION
The Command Server is the ICD 1c command interface to the DHS used by outside 
entities, including the DHS Console. The command server verifies that 
the command is known to the DHS system, that all required parameters 
are present and that no unknown parameters are present. The command is 
then passed on to the appropriate subsystems for execution.
The commands accepted by the DHS are described in ICD 3.2. 
Note that the command server does not handle bulk data, bulk data is sent 
directly to the DHS Data Server.

.SH OPERATION

The DHS Status Server, and all subsystems listed in the configuration file
must be running prior to running the Command Server.
Once the Command Server is running, it
will remain idle until it receives commands. The Command server then verifies
that the command parameters are correct and forwards it to appropriate
DHS subsystems. Any responses sent by the DHS subsystems are passed to the
system which initiated the command.

A complete description of the Command server operation can be found in 
"The Gemini Data Handling System User Manual".

A complete description of the ICD 1c interface can be found in
"ICD 1c - Baseline DHS Interface".

.SH COMMANDS

The commands accepted by the Command Server, and the DHS as a whole
are documented in "ICD 3.2 - The DHS interface".

.SH OPTIONS

.TP
.B -debug NONE | MIN | FULL 
Debug mode.  Depending on the mode set, it will print various degrees of 
error messages to standard output.  
.TP
.B -simulate
Simulate mode.  In simulate mode, only simulate, reset and init commands
are processed or passed to the DHS subsystems. All other commands are ignored.
.TP
.B -V
Version.  Print version numbers and quit.

.SH FILES

.SS

.B dhsCommand.config
The Command Server requires a configuration file
to set some parameters necessary for its operation. 
The following is an abbreviated, annotated sample configuration file.
(Text followed by a '#' is treated as a comment and ignored by
the Command Server. Blank lines are also ignored.):

.sp
.nf

#
#  Application identification. This keyword specifies the IMP 
#  name to use when running this program.
#
# Keyword       application 
#
# -------       -----------
#

identity        commandServer


#
#  Imp information. This keyword specifies the maixumum number
#  of IMP connections to allow. This must be enought for the
#  connections to each of the DHS subsystems, and connections
#  to the systems sending commands to the DHS.
#
# keyword       Max connects
#
# --------      ------------
#

imp             10


#
#  Subsystem list. This lists the DHS subsystems which are under
#  control of this command server. The subsystem id is used in
#  the command configuration keywords to specify which subsystems
#  should receive each command. The address values are the addresses
#  of the systems where the subsystem is running, and the identity
#  values are the IMP identities of each subsystem. The commandLine
#  values are currently not used.
#
# keyword  subSystem  address   identity         commandLine
# -------  ---------  -------   --------         -----------
#  

subsystem  CMD        salish    commandServer    dhsCmd
subsystem  DTS        salish    dataServer1      dhsData
subsystem  HIS        salish    historyServer    dhsHistory
subsystem  QLS        salish    qlServer         dhsQlServer
subsystem  STA        salish    statusServer     dhsStatus



#
#  Command list. These keywords identify the commands accepted by
#  the command server. Each keyword has a command name, a boolean
#  value indicating if the command is abortable, a boolean value
#  indicating if the command can have a "subsystem" parameter which
#  specifies the subsystem which should receive the command, and 
#  a list of subsystems which can accept the command. Boolean values
#  should be "yes" for true, or "no" for false. The target system
#  list can be empty if no systems accept the command (The command
#  will be accepted, but ignore.) The target system list can contain
#  "*" if all systems accept the command.
#
# keyword    command          abortable  subsystem  target
#            name                        list       systems
# --------   -------          ---------  ---------  -------
#

command      abort            yes        no
command      cmdAbort         no         no         CMD
command      cmdSystemExit    no         no         CMD
command      debugLevel       no         yes        *


#
# NOTE that these commands have a fully specified subsystem list.  
# This is because the order of execution is important for these 
# commands. In the case if "reset" and "init" the Status server 
# must be first and the "DTS" next to last.  In the case of exit 
# the status server needs to be next to last and the data server 
# one of the first systems.  The order the subsystems appear in 
# is the order they will be executed in, except the command server 
# always executes the command on itself last, so the Command server 
# is always last.
#

command      exit             no         yes        DTS QLS HIS STA CMD
command      exit             no         yes        DTS QLS HIS STA CMD
command      init             no         yes        STA QLS DTS HIS CMD
command      reset            no         yes        STA QLS DTS HIS CMD


#
#  Command attribute list. These keywords list the attributes 
#  available for each command. The first value is the name of
#  the command to which the attribute applies. The second value
#  is the attribute name. The third value is the data type of
#  the attribute (this must be one of the types given in ICD 1c.
#  The last value is a boolean flag indicating if the attribute
#  is optional or not. If the attribute name is "*", then the
#  command is assumed to accept an attribute with any name.
#
# keyword    command        attribute         type           optional
#            name           name
# --------   -------        ---------         ----           --------
#

attribute    cmdAbort       tag               DHS_DT_TAG     no
attribute    cmdSystemExit  disconnectTimeout DHS_DT_INT32   yes
attribute    debugLevel     level             DHS_DT_STRING  no
attribute    debugLevel     subsystem         DHS_DT_STRING  yes

.fi

.SH ENVIRONMENT VARIABLES

Upon startup, the Command Server
looks for its configuration file in the directory specified by the 
environment variable
.B DHSCOMMAND_CONFIG_DIR.
If the configuration file is not found, it looks in the directory in the 
.B DEFAULT_CONFIG_DIR 
environment variable, and finally will look in the current directory.

The IMP scratch directories used to communicate with other processes are
located in the directory specified with the IMP_SCRATCH environment variable.
The IMP_SCRATCH directory must be the same for all programs that the Command
Server will communicate with.

.SH DIAGNOSTICS

Returns 0 upon successful completion, otherwise -1.


.SH SEE ALSO

.BR dhsStatus (1).

.SH DOCUMENTS

.TP
.B The Gemini Data Handling System User Manual
.TP
.B ICD 3.2 - The DHS interface

.SH BUGS

The "*" wildcard option in the attribute names in the configuration
file isn't well tested. This will have to be done for the data processing
subsystem.

.SH AUTHORS
Norman Hill
.br

National Research Council
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
