#!/bin/csh -f
#***********************************************************************
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#
# (c) <year>				(c) <year>
# National Research Council		Conseil national de recherches
# Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
# All rights reserved			Tous droits reserves
# 					
# NRC disclaims any warranties,		Le CNRC denie toute garantie
# expressed, implied, or statu-		enoncee, implicite ou legale,
# tory, of any kind with respect	de quelque nature que se soit,
# to the software, including		concernant le logiciel, y com-
# without limitation any war-		pris sans restriction toute
# ranty of merchantability or		garantie de valeur marchande
# fitness for a particular pur-		ou de pertinence pour un usage
# pose.  NRC shall not be liable	particulier.  Le CNRC ne
# in any event for any damages,		pourra en aucun cas etre tenu
# whether direct or indirect,		responsable de tout dommage,
# special or general, consequen-	direct ou indirect, particul-
# tial or incidental, arising		ier ou general, accessoire ou
# from the use of the software.		fortuit, resultant de l'utili-
# 					sation du logiciel.
#
#***********************************************************************
#
# FILENAME
# dhsCommand/scripts/dhsStart
#
# PURPOSE:
# Script to allow easy start of the DHS.
#
#INDENT-OFF*
# $Log: not supported by cvs2svn $
# Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
#
#
# Revision 1.1.1.1  1999/08/23 19:58:08  cvs-tuc
# Initial install into CVS of dhs-0.16
#
#INDENT-ON*
#
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#***********************************************************************
#

#
# Parse Command Line.
#

if ( $#argv != 1 ) then
    goto USAGE_ERROR
endif

if ( $1 != "-summit" && $1 != "-base" ) then
    goto USAGE_ERROR
endif


#
# Get host name from shell environment. Set EPICS binaries path.
#

set hostname = `echo $HOST`
set epics_bin = "/opt/local/epics/epics/base/bin/solaris"


#
# Set Up List of Executables to Run. 
#

set executable_list = `printf "dummy dummy dummy dummy dummy dummy"`

set executable_list[1] = "dhsStatus"
set executable_list[2] = "dhsData"
set executable_list[3] = "dhsHistory"

if ( $1 == "-summit" ) then
    set executable_list[4] = "dhsQlServer -master"
else
    set executable_list[4] = "dhsStorage"
endif

set executable_list[5] = "dhsCommand"
set executable_list[6] = "dhsConsole"


#
# Start Imp Master Task.
#

echo " "
echo "        Starting IMP Master Task ..."
echo " "
master &


#
# Start EPICS Channel Access repeater task.
#

echo "        Starting EPICS Channel Access Repeater task ... "
echo " "
$epics_bin/startCArepeater


#
# Start the system.
#

set count = 1
while ( $count < 7 )

    sleep 1

    echo "Starting $executable_list[$count] on $hostname"

    impload $hostname $executable_list[$count] &

    @ count++
end


#
# Exit nicely.
#

echo " "

exit 0


#
# Usage Error Message Goto Target.
#

USAGE_ERROR:

echo "                                                                "
echo "Usage:  dhsStart { -summit | -base }                            "
echo "                                                                "
echo "                 -summit: Start Summit Configuration of DHS.    "
echo "                 -base:   Start Base Configuration of DHS.      "
echo "                                                                "

exit 1

