.\"/*+
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"* (c) 1999				(c) 1999.
.\"* National Research Council		Conseil national de recherches
.\"* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\"* All rights reserved		Tous droits reserves
.\"* 					
.\"* NRC disclaims any warranties,	Le CNRC denie toute garantie
.\"* expressed, implied, or statu-	enoncee, implicite ou legale,
.\"* tory, of any kind with respect	de quelque nature que se soit,
.\"* to the software, including		concernant le logiciel, y com-
.\"* without limitation any war-	pris sans restriction toute
.\"* ranty of merchantability or	garantie de valeur marchande
.\"* fitness for a particular pur-	ou de pertinence pour un usage
.\"* pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\"* in any event for any damages,	pourra en aucun cas etre tenu
.\"* whether direct or indirect,	responsable de tout dommage,
.\"* special or general, consequen-	direct ou indirect, particul-
.\"* tial or incidental, arising	ier ou general, accessoire ou
.\"* from the use of the software.	fortuit, resultant de l'utili-
.\"* 					sation du logiciel.
.\"*
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"*	Name			: mfsIngest/doc/mfsIngest.1
.\"*
.\"*	Date			: March 10, 1999
.\"*
.\"*
.\"*    SCCS data               : @(#)
.\"*        Module Name         : mfsIngest.1
.\"*        Version Number      : 1.3
.\"*        Release Number      : 1
.\"*        Last Updated        : 04/05/00
.\"*
.\"*	Written by		: Shannon Jaeger
.\"*
.\"*	Modification History:
.\"*		 99/03/10 SDJ	: Copied from cdIngest.
.\"*	       2000/04/05 SDJ	: Switched from dvdIngest to mfsIngest.
.\"*	       2000/04/05 SDJ	: Added examples.
.\"*
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"************************************************************************
.\"-*/
.TH MFSINGEST  1 03/10/99 "CADC"

.SH NAME
.B mfsIngest
\- Ingests a mountable file system into the archive tables.

.SH SYNOPSIS
.B mfsIngest
[
.B -a
.I archive
]
[
.B -t
.I volume type
]
[
.B -r
]
[
.B -v
] [
.B -V
]
[
[
.B -b
]
.I path ....
]

.SH DESCRIPTION
.B mfsIngest
is a utility which ingests a "volume" and the files on the volume into the 
archive tables in a database.  A volume can be any mountable file system,
which includes but not limited to CD-ROMs, DVD-ROMs and Magnetic disks.

.SH OPERATION
Once a mountable file system has been created then
.B mfsIngest
is run to insert the volume and the files contained on the volume into the
database.  By placing this information into the
database other applications can retrieve the data it needs.

If a volume is already in the database then the operator will be asked if
the information is to be re-ingested. 

If the -a option was not specified on the command-line then the default
archive, listed in the configuration file for the \fBad\fR library, 
will be used.

If no path was given then the operator will be prompted for a path on
a mountable file system.

If the -t option was not specified then the operator will be asked to
enter the volume type of the mountable file system.

.B Note
that in batch mode the operator will not be prompted.

Once all of the volume information has been ingested into the database
then \fBmfsOnline\fR should be executed if and only if the volume will
be permanently mounted.  If the volume is not permanently mounted than
no further operations should be performed on this volume.

.SH OPTIONS
.TP
.B -a \fIarchive\fR
Archive.	If this is a new disk, then this archive name will 
be entered into the database. If the 
.B -a
option is not present, the default archive taken from the 
.B ad
configuration file is used.
.TP
.B -b
Batch.	Run in batch mode (no prompting the operator for input). This also 
implies the paths must be specified on the command line.
.TP
.B -r
Noprompt.	Don't prompt on re-ingest.
.TP
.B -t \fIvolumeType\fR
Volume Type.	The type of mountable file system (volume) to be read, such 
as "CD", "DVD", or "MD".
.TP
.B -v
Verbose.	Print all information and error messages to user's console.
.TP
.B -V
Version.	Print version numbers and quit.
.TP
.B -? -h -help
Help.	Prints the usage message and quits.

.SH EXAMPLES
.TP 3
.B 1.
The following example ingests the volume at \fI/cds/archive1/volume001\fR.
The volume belongs to the archive \fIARCHIVE1\fR which is specified on
the command line.  Note that the operator is prompted for further information
in this example.
.RS 8n
.sp 1n
.nf
\fB example% mfsIngest \-a\fR ARCHIVE1 /cds/archive1/volume0001
.IB "messages from " mfsIngest
\fI (mfsi5)   Volume inserted has the volume id 'VOLUME0001'.\fR
\fI Continue (Y/N)?\fR y
\fI Enter the type of media to be ingested (CD, DVD, or MD) :\fR CD
.IB "more messages from " mfsIngest
.sp 1n
.fi
.RE
.TP 3
.B 2.
The following example re-ingests the volume at \fI/dvds/archive3/volume21\fR.
The volume belongs to the archive \fIARCHIVE3\fR and it resides on
a DVD.  The operator did not specify the \-r option so the operator is
asked if the volume should be re-ingested.
.RS 8n
.sp 1n
.nf
\fB example% mfsIngest \-a\fR ARCHIVE3 \fB\-t\fR DVD /dvds/archive3/volume21
.IB "messages from " mfsIngest
\fI (mfsi5)   Volume inserted has the volume id 'VOLUME21'.\fR
\fI Continue (Y/N)?\fR y
\fI Enter the type of media to be ingested (CD, DVD, or MD) :\fR CD
\fI Would you like to re-ingest this volume (Y/N)?\fR y
.IB "more messages from " mfsIngest
.sp 1n
.fi
.RE
.TP 3
.B 3.
The following example runs \fBmfsIngest\fR in batch mode.  There are
two DVD volumes (paths) to be added to the archived.  Since the operator
did not use the \-a option these volumes will be added to \fBad\fR
library's default archive.  Note the operator is not prompted at all
in this example.
.RS 8n
.sp 1n
.nf
\fB example% mfsIngest \-r \-t\fR DVD /dvds/myArch/vol1	\e
	/dvds/myArch/vol2
.IB "messages from " mfsIngest
.sp 1n
.fi
.RE

.SH FILES
.SS
.B ~/.dbrc
The
.I ~/.dbrc
file contains information about each database that a user may 
reference with executables such as 
.B mfsIngest
.  A database reference must contain a server/database pair followed
by the user's name and password. Each line of the 
.I ~/.dbrc
file must contain a complete server/database reference for every 
database which may be accessed through this file. Each line of
this file must be arranged in the following order:

.I server database username password

Each item should be separated by whitespace (spaces and/or tabs).
If a required database is not included in the 
.I ~/.dbrc 
file, 
.B mfsIngest
will prompt for a username and password.

.SH SECURITY
In order to ensure a secure
.I ~/.dbrc
file,
.B mfsIngest
requires that the
file resides in the directory specified by the 
.B HOME 
environment variable, and the file protection must restrict read and write 
access to the file owner.

.SH TABLES
.B mfsIngest
uses the Archive database to determine if the volume already exists.
.B mfsIngest
updates the archive tables.

The location of the Archive database and the name of the 
archive..mfsfiles and archive..mfs tables
are specified in the configuration file for the CADC 
.I ad 
library.

The following is a list of SYBASE tables that must be present for
.B mfsOnline
to run correctly:
.TP
.B archive..mfs
.TP
.B archive..mfsfiles

.SH ENVIRONMENT VARIABLES
The environment variable
.B LIBAD_CONFIG_DIR 
may be set to the path of the directory where the 
.B ad
configuration file can be found. If
.B LIBAD_CONFIG_DIR
is not set, the environment variable
.B DEFAULT_CONFIG_DIR 
should be set to the path of the directory where the file can be found. 

.SH DIAGNOSTICS
none.

.SH SEE ALSO
.BR mfsOnline (1),
and
.BR ad (3).

.SH BUGS
None known.

.SH AUTHORS
Shannon Jaeger
.br

National Research Council of Canada
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre

