.\"/*+
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"* (c) 1996                           (c) 1996.
.\"* National Research Council          Conseil national de recherches
.\"* Ottawa, Canada, K1A 0R6            Ottawa, Canada, K1A 0R6
.\"* All rights reserved                Tous droits reserves
.\"*                                    
.\"* NRC disclaims any warranties,      Le CNRC denie toute garantie
.\"* expressed, implied, or statu-      enoncee, implicite ou legale,
.\"* tory, of any kind with respect     de quelque nature que se soit,
.\"* to the software, including         concernant le logiciel, y com-
.\"* without limitation any war-        pris sans restriction toute
.\"* ranty of merchantability or        garantie de valeur marchande
.\"* fitness for a particular pur-      ou de pertinence pour un usage
.\"* pose.  NRC shall not be liable     particulier.  Le CNRC ne
.\"* in any event for any damages,      pourra en aucun cas etre tenu
.\"* whether direct or indirect,        responsable de tout dommage,
.\"* special or general, consequen-     direct ou indirect, particul-
.\"* tial or incidental, arising        ier ou general, accessoire ou
.\"* from the use of the software.      fortuit, resultant de l'utili-
.\"*                                    sation du logiciel.
.\"*
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"*	Name			: fits2sds
.\"*
.\"*	Date			: <Sep 04, 1997>
.\"*
.\"*	RCS data: 
.\"*	    $RCSfile: fits2sds.1,v $
.\"*	    $Revision: 1.1.1.1 $
.\"*	    $Date: 2002-11-24 20:33:00 $
.\"*
.\"*	Written by		: Shannon Jaeger
.\"*
.\"*	Modification History:
.\"*	    $Log: not supported by cvs2svn $
.\"*	    Revision 1.1.1.1  2002/02/21 20:23:35  tpaz
.\"*	
.\"*	
.\"*	    Revision 1.1.1.1  1999/08/23 19:58:39  cvs-tuc
.\"*	    Initial install into CVS of dhs-0.16
.\"*	
.\"*	    Revision 1.3  1998/07/03 17:36:58  jaeger
.\"*	    Updated.  Also added change where fits2sds exits after creating the
.\"*	    data dictionary, instead of continuing.
.\"*
.\"*	    Revision 1.2  1997/10/29 23:49:48  jaeger
.\"*	    Fixed typo's, added reference to dd man page, and made it more
.\"*	    consistent with other DHS man pages.
.\"*
.\"*	    Revision 1.1  1997/09/05 19:25:37  jaeger
.\"*	    Initial revision
.\"*
.\"*
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"************************************************************************
.\"-*/
.TH FITS2SDS 1 09/04/97 "NRC"

.SH NAME
fits2sds 
\- Convert a Flexible Image Transport System (FITS) file to 
Self Defining Structures (SDS).

.SH SYNOPSIS
.B fits2sds
[
.B \-array
] [
.B \-dd
] [
.B \-ddMake
] [
.B \-disk
][
.B \-help
] [
.B \-mem
] [
.B \-sds
] [
.B \-v
] [
.B \-V
] [
.B \-xc 
.IR xAxisChunks
] [
.B \-yc 
.IR yAxisChunks
]
.B \-i 
.IR inputFile

.SH DESCRIPTION
.B fits2sds
creates DHS simulation data.  The simulation data is expected to be
similar to the data generated by instruments used by one of
the 
.I Gemini
telescopes.  It creates both 
.B Flexible Image Transport System (FITS)
files for the 
.I Quick Look Server
and
.B Self Defining Structures (SDS)
for
.I Data Server.


.SH OPERATION

The
.I inputFile
must be specified on the command line.
.I inputFile
is the
.B FITS
file used to generate the simulation data.  By default 
.B NO
files are generated.  

The 
.B \-disk, \-mem, 
and
.B \-sds
flags specify which files are to be generated;
.B FITS
disk files, 
.B FITS
memory buffers, and
.B SDS
files respectively.  
If none of these options are specified
then no data is generated.

The two variations of 
.B FITS
files are used to test the
.B cfitsio 
library, which is used by DHS and fits2sds.  The 
.B cfitsio
library allows
.B FITS
files to be created either directly on disk or in a memory buffer.  The
.B \-disk
flag the
.B FITS
creates directly on disk.  Conversely the
.B \-mem
flag creates
.B FITS
files in a memory buffer. Once the FITS memory file is
fully constructed is 
written to disk.  The files created by these two methods 
should be identical. 

The
.I xAxisChunks
and
.I yAxisChunks
values are used to simulate data chunking.  Together they
specify the number of chunks, pieces, the original image data will
be broken into.  The image data comes from the
.I inputFile.
These flags expect positive integer values.  Their default value is "1".
The number of chunks created for each
FITS image extension found in the
.I inputFile
is the
.I xAxisChunks
value multiplied by the
.I yAxisChunks
value.  More specifically, the x-axis of the image will be
divided into
.I xAxisChunks
and the y-axis of the image will be divided into
.I yAxisChunks.

The various chunks that are created may be written in 
.B FITS 
disk files, 
.B FITS
memory buffers, and
.B SDS
memory buffers, depending on the flags specified.  These chunks 
will be in written to files with the
following, respective, names:
.TP
.B originalFitsFileName.chunkNumber.fits,
.TP
.B originalFitsFileName.chunkNumber.mem, and
.TP
.B originalFitsFileName.chunkNumber.sds
.PP
The 
.I chunkNumber
is generated by
.B fits2sds; the first file generated has a
.I chankNumber
of 0.

If the 
.B \-dd
flag is used then the information stored in the data dictionary,
.B libdd.config,
is used to create the
.B SDS
and
.B FITS
files.  Normally less errors will occur when this flag is used.

If the
.B \-ddMake
flag is used then a data dictionary,
.B libdd.config,
will be generated in the current directory.  The generated data
dictionary may have duplicate rows and will probably require some
editing, in particularly the
.I Null Value
field.  The file name of the
data dictionary will be:
.TP
.B originalFitsFileName.dd
.PP
Only one of the 
.B \-ddMake
and
.B \-dd
flags can be used.  Note that no data processing is done if the
.B\-ddMake
flag is specified.

If the
.B \-array
flag is used then multi-dimensional arrays are generated.  The
array's data type, number of dimensions, and size of each 
dimension is randomly generated.

The data that is generated is produced in the current directory,
i.e. the directory where the
.B fits2sds
command was executed.  Besides the files already mentioned there
are two more groups of files created: one group for the composition
of the chunks and one group for the 
.B SDS
structure containing the entire information from the original FITS
files.  The files which are created by composing all of the chunks
have file names:
.TP
.B originalFitsFileName.comp.fits, and
.TP
.B originalFitsFileName.comp.mem,
.PP
where the ".fits" is a 
.B FITS
disk file and ".mem" is a
.B FITS
memory buffer.

The files which are created from a single
.B SDS 
structure containing the entire original
.B FITS
file have filenames:
.TP
.B originalFitsFileName.full.fits,
.TP
.B originalFitsFileName.full.mem, and
.TP
.B originalFitsFileName.full.mem,
.PP
where the ".fits" file is a 
.B FITS
disk file, the ".mem" file is a
.B FITS
memory buffer and the ".sds" file is a
.B SDS
memory buffer.

Note that the composed and complete files should be identical.  This
is done to test separate features in the 
.B sf
library.

All files containing memory buffers are straight dumps of the contents
of a particular memory buffer.

.SH OPTIONS
.TP
.B \-array
Add multi-dimensional arrays to the output.  This option will add
randomly generated arrays of data to the output.  This data is the
contents of a block of memory and is not assigned any particular
values.
.TP
.B \-dd
Use the data dictionary when forming the
.B SDS
structure.  The 
.B -ddMake
option can not be used in conjunction with the
.B -dd 
option.
.TP
.B\-ddMake
Create a data dictionary, 
.B libdd.config.   The 
.B -dd
option can not be used in conjunction with the
.B -ddMake
option.
.TP
.B \-disk
Generate 
.B FITS 
files directly on disk.
.TP
.B \-help
Display a help message.
.TP
.B \-i \<pathname\>
The FITS input file to be used in the creation of the simulation data.
.TP
.B \-mem
Generate 
.B FITS 
memory buffers and write them on disk.
.TP
.B \-sds
Generate 
.B SDS 
files.
.TP
.B \-v
Use verbose mode.
.TP
.B \-V
Print the version number.
.TP
.B \-xc \<integer\>
Number of divisions, chunks,  along the x-axis.
.TP
.B \-yc \<integer\>
Number of divisions, chunks, along the y-axis.

.SH FILES
.TP
.B libdd.config
.B fits2sds
uses a configuration file called
.I libdd.config,
also referred to as the data dictionary.  The data dictionary is used
by the
.B sf
library to check the validity of 
data in the
.B SDS
structures, when converting to
.B FITS
files.  This file is also used to when creating the 
.B SDS
structures if the 
.B/-dd
flag was specified.  See the dd man page for more information.

.SH EXAMPLES
.LP
An example of a command line:
.IP
.B "example% fits2sds -i m51.fits -xc 2
.LP
This command will generate
.B FITS
and
.B SDS
simulation data where any of the image data is broken into two
pieces along the x-axis.

.LP
An example of a command line:
.IP
.B "example% fits2sds -dd -i m51.fits -xc 2 -yc 3
.LP
This command will generate
.B FITS
and
.B SDS
simulation data where any of the image data is broken into six
blocks, split once on the x-axis and twice along the y-axis.  
Also the data dictionary is used when the 
.B SDS
structures are created.



.SH ENVIRONMENT VARIABLES

The environment variable
.B LIBDD_CONFIG_DIR may be set to the path of the 
directory where the 
.B dd
configuration file can be found. If
.B LIBDD_CONFIG_DIR
is not set, the environment variable
.B DEFAULT_CONFIG_DIR 
should be set to the path of the directory where the file can be found. 

.SH DIAGNOSTICS
.B fits2sds
returns 0 to the calling environment upon successful completion.
Otherwise a non-zero number is returned.

.SH SEE ALSO
.BR dd (3)
.BR sf (3)

.SH BUGS
The generated data dictionary, 
.B -ddMake
option, may contain duplicate rows.  This means that the generated data
dictionary is not valid.

.SH AUTHOR
Shannon Jaeger
.br

National Research Council of Canada
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre

