.\"/*+ $Id: dhs++Server.1,v 1.1.1.1 2002-11-24 20:30:02 brighton Exp $
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) 1998				(c) 1998
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-	ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME:
.\" dhs++Server/doc/dhs++Server.1
.\"
.\" PURPOSE:
.\" Manaul page that described the DHS C++ Server simulator.
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/02/21 20:23:35  tpaz
.\"
.\"
.\" Revision 1.1.1.1  1999/08/23 19:58:33  cvs-tuc
.\" Initial install into CVS of dhs-0.16
.\"
.\" Revision 1.1  1998/08/06 23:32:35  nhill
.\" Initial revision
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.\"
.TH	dhs++Server 1 06/08/98 "NRC"

.SH NAME
dhs++Server
\- An object-oriented (C++) simulator for DHS servers.

.SH SYNOPSIS
.B dhs++Server
[
\-noStrict
] <
.B serverName
>

.SH DESCRIPTION
The 
.B dhs++Server
executable simulates a DHS server.  This server accepts commands
and bulk data requests from a DHS client and sends command responses back.  
All commands
and their attribute value list which are received by the 
\fBdhs++Server\fR are displayed on standard out.
.P
The commands which are known to the \fBdhs++Server\fR are:
.LP
.nf
.ta 4c 8c 12c
.ft B
\fBcmd2\fR	\fBquit\fR
.fi
.ft R

Bulk data put requests result in a done message being returned. If the data
sent is a dataset, the some of the data will be displayed.

Bulk data get requests result in an artificial data buffer being returned.


.SH OPERATION
The \fBserverName\fR must be be specified and is the name of the DHS Server
which is to be simulated.  
.P
If the \-noStrict command-line option is specified then strict
error checking is not done.  This means that error responses are
not returned for commands that are not recognized by the
\fBdhs++Server\fR

If the client is on a different host, the IMP \fBmaster\fR task must
be run on both the client and server host before \fBdhsClient\fR is run.


.SH FILES
None.

.SH EXAMPLES
.LP
An example of a command line with strict error checking:
.IP
.B example> dhs++Server commandServer

.LP
An example of a command lines without strict error checking:
.IP
.B  example> dhs++Server \-noStrict commandServer


.SH  ENVIRONMENT VARIABLES
IMP_SCRATCH controls the directory in which the IMP scratch files are created. 
This must match the IMP_SCRATCH environment variable used when running the 
client if the client is on the same host, or when running the IMP \fBmaster\fR
task if the client is on a different host.


.SH SEE ALSO
dhs++Client (1)
.sp
dhsServer (1)
.sp
dhsClient (1)


.SH BUGS

.SH AUTHORS
Shannon Jaeger
.br



National Research Council of Canada
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
