# Makefile

NAME = dhsSim4Data
SOURCES = arg.C config.C main.C msg.C sim.C simCmdDefault.C simCmdOldps.C simCmdQls.C simCmdSs.C simConnect.C simError.C simPutDefault.C simPutFits.C
LIBS = -ldhs++ -ldhs -lgen -ldhsGen $(TCLTK_LDLIBS)

include ../conf/cxx_bin.mk
