#!/usr/cadc/misc/bin/perl
#***********************************************************************
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#
# (c) 1999				(c) 1999
# National Research Council		Conseil national de recherches
# Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
# All rights reserved			Tous droits reserves
# 					
# NRC disclaims any warranties,		Le CNRC denie toute garantie
# expressed, implied, or statu-		enoncee, implicite ou legale,
# tory, of any kind with respect	de quelque nature que se soit,
# to the software, including		concernant le logiciel, y com-
# without limitation any war-		pris sans restriction toute
# ranty of merchantability or		garantie de valeur marchande
# fitness for a particular pur-		ou de pertinence pour un usage
# pose.  NRC shall not be liable	particulier.  Le CNRC ne
# in any event for any damages,		pourra en aucun cas etre tenu
# whether direct or indirect,		responsable de tout dommage,
# special or general, consequen-	direct ou indirect, particul-
# tial or incidental, arising		ier ou general, accessoire ou
# from the use of the software.		fortuit, resultant de l'utili-
# 					sation du logiciel.
#
#***********************************************************************
#
#   Module Name:	dhsDataset
#
#   Purpose:
#	To remove or move datasets under the management of the
#	DHS data server.
#
#   RCS data:
#	$RCSfile: dhsDataset,v $
#	$Revision: 1.1.1.1 $
#	$Date: 2002-11-24 20:27:39 $
#
#   Programmer		: Severin Gaudet
#
#   Modification History:
#	$Log: not supported by cvs2svn $
#	Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
#	
#	
#	Revision 1.1.1.1  1999/08/23 19:58:19  cvs-tuc
#	Initial install into CVS of dhs-0.16
#	
#
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#***********************************************************************
#-*/

unshift(@INC, "/usr/cadc/misc/lib/perl5/Sybase");
require "sybperl.pl";
use Getopt::Long;


#
#  Initialize global variables.  This should be tailored for instance of the
#  DHS database.
#

$appname = "dhsDataset";


#
#  Parse the command line.
#

cmdLineParse();



#
#  Read the configuration files.
#

configRead();


#
#  Connect to the database and check tables.
#

dbConnect();
dbCheck();


#
#  Process.
#

if ( $test )
{
    doTest();
}
elsif ( $move )
{
    datasetMove( $dataset );
}
else
{
    datasetRemove( $dataset );
}


#
#  Close the database connection.
#

&dbclose( $dbproc );


#
#+
########################################################################
#
#   Subroutine:	cmdLineParse
#
#   Purpose:
#	Parses and verifies the command line arguments and stores
#	values in global variables.
#
#   Arguments:
#	None.
#
#   Return values:
#	None.
#
########################################################################
#-

sub	cmdLineParse
{

    GetOptions( "mv" => \$move,
	    "rm" => \$remove,
	    "test" => \$test ) || printUsage();

    if ( $test )
    {
	if ( $#ARGV != -1 )
	{
	    printUsage();
	}
    }
    else
    {
	if ( ( $move eq "" && $remove eq "" )
		|| ( $move ne "" && $remove ne "" )
		|| $#ARGV != 0 )
	{
	    printUsage();
	}

	$dataset = $ARGV[0];
    }
}
#
#+
########################################################################
#
#   Subroutine:	configRead
#
#   Purpose:
#	Read the dhsData.config and libAd.config files.  It stores the
#	values read in global variables.
#
#   Arguments:
#	None.
#
#   Return values:
#	None.
#
########################################################################
#-

sub	configRead
{
    $fnameAd = "libAd.config";
    $fnameData = "dhsData.config";


    #
    #  Read the libAd.config file.
    #

    $configPath = $ENV{DEFAULT_CONFIG_DIR};
    if ( $configPath eq "" )
    {
    	print( STDERR "ERROR: Environment variable DEFAULT_CONFIG_DIR is undefined\n" );
	exit;
    }

    $filename = "$configPath/$fnameAd";
    if ( ! open( FH, $filename ) )
    {
	print( STDERR "ERROR: Cannot read $filename\n" );
	exit;
    }

    while ( <FH> )
    {
	if ( /^database/ )
	{
	    ( $void, $server, $database ) = split;
	}
	elsif ( /^medium(.*)MD/ )
	{
	    ( $void, $void, $void, $tblMdfiles, $tblMds ) = split;
	}
    	elsif ( /^remote/ )
	{
	    ( $void, $site, $tblRemoteFiles ) = split;
	}
    }

    close( FH );

    if ( $site eq "" || $server eq ""
	    || $database eq "" || $tblMdfiles eq ""
	    || $tblMds eq "" )
    {
    	print( STDERR "ERROR:  Missing configuration values in $filename\n" );
	exit;
    }
    

    #
    #  Read the dhsData.config file.
    #

    $filename = "$configPath/$fnameData";
    if ( ! open( FH, $filename ) )
    {
	print( STDERR "ERROR: Cannot read $filename\n" );
	exit;
    }

    while ( <FH> )
    {
	if ( /^database/ )
	{
	    ( $void, $s, $d, $tblUnique, $tblDataset, $tblProcess ) = split;
	    if ( $s ne $server || $d ne $database )
	    {
		print( STDERR "ERROR: keyword database is configured differently in:\n" );
		print( STDERR "           $configPath/$fnameData\n" );
		print( STDERR "           $configPath/$fnameAd\n" );
		exit;
	    }
	}
	elsif ( /^fitsTable/ )
	{
	    ( $void, $tblFitsHeader ) = split;
	}
	elsif ( /^identity/ )
	{
	    ( $void, $identity ) = split;
	}
    	elsif ( /^storage/ )
	{
	    ( $void, $tempDiskname, $permDiskname ) = split;
	}
    }

    close( FH );

    if ( $tblUnique eq "" || $tblDataset eq ""
	    || $tblProcess eq "" || $tblFitsHeader eq ""
	    || $identity eq "" || $tempDiskname eq ""
	    || $permDiskname eq "" )
    {
    	print( STDERR "ERROR:  Missing configuration values in $filename\n" );
	exit;
    }
}
#
#+
########################################################################
#
#   Subroutine:	datasetAdd
#
#   Purpose:
#	Adds dataset rows to tables and creates a zero length file for
#	testing.
#
#   Arguments:
#	dataset		: Name of dataset to create.
#
#   Return values:
#	None.
#
########################################################################
#-

sub	datasetAdd
{
    local( $dataset, $diskname, $flag, $mountPoint ) = @_;

    $filename = "$dataset.raw";
    system( "touch $mountPoint/$filename" );
    if ( ! -e "$mountPoint/$filename" )
    {
    	print( STDERR "ERROR: Cannot create $mountPoint/$filename" );
	exit;
    }

    doSql( "begin transaction" );
    doSql( "insert $database..$tblMdfiles
	    values( '$dataset', '$diskname', '$filename',
		    0, 'C', 0, ' ', 'R' )" );

    doSql( "insert $database..$tblRemoteFiles
	    values ( '$dataset', '$diskname', '$site', 'C', ' ', 'R' )" );

    doSql( "insert $database..$tblProcess
	    values ( '$dataset', '$dataset', getdate(),
		    ' ', '$flag', 'H', ' ', ' ', 'R', 'dhsPut' )" );

    doSql( "insert $database..$tblFitsHeader ( datasetName )
		    values( '$dataset' )" );

    doSql( "insert $database..$tblUnique values( '$dataset', getdate() )" );

    doSql( "commit transaction" );
}
#
#+
########################################################################
#
#   Subroutine:	datasetInfo
#
#   Purpose:
#	Returns the diskname, disk mount point and the filename for the
#	given dataset.  This function dies if:
#		1.  The dataset is not in the $tblMdfiles tables; or
#		2.  The dataset is in the dataset table.
#
#   Arguments:
#	dataset		: Name of dataset for queries.
#
#   Return values:
#	diskname	: Name of disk on which to find dataset.
#	mountPoint	: The mount point of the disk.
#	filename	: The dataset's file name on disk.
#
########################################################################
#-

sub	datasetInfo
{
    local( $dataset ) = @_;


    #
    #  Determine if the dataset is in the $tblDataset table.  If so
    #  the dataset is fully processed and cannot be changed.
    #

    doSql( "select datasetName = datasetName
	    from $tblDataset
	    where datasetName = '$dataset'" );

    %buffer = &dbnextrow( $dbproc, 1 );
    $datasetName = $buffer{ 'datasetName' };
    dbcanquery( $dbproc );
    
    if ( $datasetName ne "" )
    {
	print( STDERR "ERROR: dataset \"$dataset\" has been fully processed and cannot be changed\n" );
	exit;
    }


    #
    #  Determine if the where the dataset lives on disk and whether it
    #  is permDiskname or tempDiskname.
    #

    doSql( "select diskname = f.diskname,
		    mountPoint = d.mount_point,
		    fname = f.fname
	    from $tblMds d, $tblMdfiles f
	    where d.diskname = f.diskname 
		    and f.file_id = '$dataset'" );

    %buffer = &dbnextrow( $dbproc, 1 );
    $diskname = $buffer{ 'diskname' };
    $mountPoint = $buffer{ 'mountPoint' };
    $filename = $buffer{ 'fname' };
    dbcanquery( $dbproc );

    return( $diskname, $mountPoint, $filename );
}
#
#+
########################################################################
#
#   Subroutine:	datasetMove
#
#   Purpose:
#	Move a dataset from PERM to TEMP or vice versa.
#
#   Arguments:
#	dataset		: Name of dataset to move.
#
#   Return values:
#	None.
#
########################################################################
#-

sub	datasetMove
{
    local( $dataset ) = @_;


    ( $currentDiskname, $currentMountPoint, $filename ) =
	    datasetInfo( $dataset );


    #
    #  Test for existence on disk before proceeding.
    #

    if ( $currentDiskname eq "" )
    {
	print( STDERR
		"ERROR: dataset \"$dataset\" not in $tblMdfiles table\n" );
    	exit;
    }

    if ( ! -e "$currentMountPoint/$filename" )
    {
	print( STDERR "ERROR: $currentMountPoint/$filename: No such file\n" );
	exit;
    }


    #
    #  Set the new lifetime and location.
    #

    if ( $currentDiskname eq $permDiskname )
    {
    	$newDiskname = $tempDiskname;
	$newLifetime = "T";
    }
    else
    {
    	$newDiskname = $permDiskname;
	$newLifetime = "P";
    }


    #
    #  Get the new mount point.
    #

    doSql( "select mountPoint = mount_point
	    from $tblMds d
	    where diskname = '$newDiskname'" );

    %buffer = &dbnextrow( $dbproc, 1 );
    $newMountPoint = $buffer{ 'mountPoint' };
    dbcanquery( $dbproc );

    
    #
    #  Move the file.
    #

    if ( ! rename( "$currentMountPoint/$filename",
	    "$newMountPoint/$filename" ) )
    {
	print( STDERR "ERROR: Cannot move $filename from $currentMountPoint to $newMountPoint\n" );
	exit;
    }


    #
    #  Change type and location of the file in all the tables.
    #

    doSql( "begin transaction" );

    doSql( "update $tblRemoteFiles 
	    set media_id = '$newDiskname'
	    where file_id = '$dataset'
		    and media_id = '$currentDiskname'
		    and site_id = '$site'" );

    doSql( "update $tblProcess 
	    set lifetime = '$newLifetime',
		    ssNotify = ' '
	    where datasetName = '$dataset'" );

    doSql( "update $tblMdfiles
	    set diskname = '$newDiskname'
	    where file_id = '$dataset'
		    and diskname = '$currentDiskname'" );

    doSql( "commit" );
}
#
#+
########################################################################
#
#   Subroutine:	datasetRemove
#
#   Purpose:
#	Removes a dataset from either PERM or TEMP.
#
#   Arguments:
#	dataset		: Name of dataset to remove.
#
#   Return values:
#	None.
#
########################################################################
#-

sub	datasetRemove
{
    local( $dataset ) = @_;

    
    ( $diskname, $mountPoint, $filename ) = datasetInfo( $dataset );

    #
    #  If the file exists on disk, remove it.
    #

    if ( $mountPoint ne "" && -e "$mountPoint/$filename" )
    {
	if ( ! unlink( "$mountPoint/$filename" ) )
	{
	    print( STDERR "ERROR: Cannot remove $mountPoint/$filename\n" );
	    exit;
	}
    }


    #
    #  Remove the file from all the tables.
    #

    doSql( "begin transaction" );

    doSql( "delete $tblRemoteFiles 
	    where file_id = '$dataset' 
	    and site_id = '$site'" );

    doSql( "delete $tblProcess 
	    where datasetName = '$dataset'" );

    doSql( "delete $tblFitsHeader
	    where datasetName = '$dataset'" );

    doSql( "delete $tblUnique
    	    from $tblUnique u
	    where not exists (
	    	select *
		from $tblProcess p
		where p.uniqueName = u.uniqueName )" );

    doSql( "delete $tblMdfiles
	    where file_id = '$dataset'" );

    doSql( "commit" );
}
#
#+
########################################################################
#
#   Subroutine:	dbCheck
#
#   Purpose:
#	Checks that the database tables exist and that the Data Server
#	is not running.  Also extracts information about the disk mount
#	points.
#
#   Arguments:
#	None.
#
#   Return values:
#	None.
#
########################################################################
#-

sub	dbCheck
{
    doSql( "select num = count(*)
	    from master..sysprocesses
	    where program_name = '$identity'" );
    %buffer = &dbnextrow( $dbproc, 1 );
    $num = $buffer{ 'num' };
    dbcanquery( $dbproc );

    if ( $num > 1 )
    {
    	print( STDERR "ERROR: the DHS Data Server '$identity' must be shutdown\n" );
	print( STDERR "       before running this script\n" );
	exit
    }

    doSql( "select mount_point = mount_point
	    from $database..$tblMds
	    where diskname = '$permDiskname'" );
    %buffer = &dbnextrow( $dbproc, 1 );
    $permMountPoint = $buffer{ 'mount_point' };
    dbcanquery( $dbproc );

    if ( $permMountPoint eq "" )
    {
    	print( STDERR "ERROR: Cannot find the mount point in $database..$tblMds\n" );
	print( STDERR "       for the disk named '$permDiskname'\n" );
	exit;
    }

    doSql( "select mount_point = mount_point
	    from $database..$tblMds
	    where diskname = '$tempDiskname'" );
    %buffer = &dbnextrow( $dbproc, 1 );
    $tempMountPoint = $buffer{ 'mount_point' };
    dbcanquery( $dbproc );

    if ( $tempMountPoint eq "" )
    {
    	print( STDERR "ERROR: Cannot find the mount point in $database..$tblMds\n" );
	print( STDERR "       for the disk named '$tempDiskname'\n" );
	exit;
    }
}
#
#+
########################################################################
#
#   Subroutine:	dbConnect
#
#   Purpose:
#	Connects to the database, prompting user for missing login info.
#
#   Arguments:
#	None.
#
#   Return values:
#	None.
#
########################################################################
#-

sub	dbConnect
{

    $value = `dbrc_get $server $database` ||
	    die "ERROR: Cannot exec script 'dbrc_get'\n";

    ( $username, $password ) = split( /[ \t\n]+/, $value );


    #
    #  Login in with the same identity as the DHS Data Server.
    #  This will ensure that the Data Server cannot be run while
    #  this script is running.
    #

    $dbproc = dblogin( $username, $password, $server, $identity );
    if ( $dbproc == -1 )
    {
	print( STDERR "ERROR: Can't login into \"$server\"\n" );
	exit;
    }

    if ( ! dbuse( $database ) )
    {
	print( STDERR "ERROR: Can't use database \"$database\"\n" );
	exit;
    }
}
#
#+
########################################################################
#
#   Subroutine:	doSql
#
#   Purpose:
#	Executes an SQL query.
#
#   Arguments:
#	@_		: Query buffer
#
#   Return values:
#	None.
#
########################################################################
#-

sub	doSql
{
    local( $sql ) = @_;

    &dbcmd( $sql ) || die "Error: in dbcmd.\n" ;
    &dbsqlexec || die "Error: in dbsqlexec.\n" ;
    &dbresults;
}
#
#+
########################################################################
#
#   Subroutine:	doTest
#
#   Purpose:
#	Add rows to the dataset tables for testing the functions of
#	this program.
#
#   Arguments:
#	None.
#
#   Return values:
#	None.
#
########################################################################
#-

sub	doTest
{
         
    $permDataset = "__dhsDataset_test_PERM";
    $tempDataset = "__dhsDataset_test_TEMP";


    #
    #  Add the PERM and TEMP datasets to the data server tables.
    #

    datasetAdd( $permDataset, $permDiskname, "P", $permMountPoint );
    datasetAdd( $tempDataset, $tempDiskname, "T", $tempMountPoint );


    #
    #  Move the datasets to the other lifetime.
    #

    datasetMove( $permDataset );
    datasetMove( $tempDataset );


    #
    #  And finally, delete the datasets.
    #

    datasetRemove( $permDataset );
    datasetRemove( $tempDataset );
}
#
#+
########################################################################
#
#   Subroutine:	printUsage
#
#   Purpose:
#	Prints the usage message.
#
#   Arguments:
#	None.
#
#   Return values:
#	None.
#
########################################################################
#-

sub	printUsage
{
    print "Usage: $appname -rm dataset_name\n";
    print "       $appname -mv dataset_name\n";
    print "       $appname -test\n";
    exit;
}
