#!/bin/sh
#***********************************************************************
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#
# (c) 1997				(c) 1997
# National Research Council		Conseil national de recherches
# Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
# All rights reserved			Tous droits reserves
# 					
# NRC disclaims any warranties,		Le CNRC denie toute garantie
# expressed, implied, or statu-		enoncee, implicite ou legale,
# tory, of any kind with respect	de quelque nature que se soit,
# to the software, including		concernant le logiciel, y com-
# without limitation any war-		pris sans restriction toute
# ranty of merchantability or		garantie de valeur marchande
# fitness for a particular pur-		ou de pertinence pour un usage
# pose.  NRC shall not be liable	particulier.  Le CNRC ne
# in any event for any damages,		pourra en aucun cas etre tenu
# whether direct or indirect,		responsable de tout dommage,
# special or general, consequen-	direct ou indirect, particul-
# tial or incidental, arising		ier ou general, accessoire ou
# from the use of the software.		fortuit, resultant de l'utili-
# 					sation du logiciel.
#
#***********************************************************************
#
# FILENAME
# dhsQlTool/scripts/dhsQlTool
#
# PURPOSE:
# This is the script to start the DHS Quick Look Tool.
#
#INDENT-OFF*
# $Log: not supported by cvs2svn $
# Revision 1.1  2004/08/24 13:57:13  brighton
# Linux port (see PORTING_NOTES, especially the part at the end labeled "Other Changes")
#
# Revision 1.2  2004/08/13 20:18:54  brighton
# Linux test/port
#
# Revision 1.1.1.1  2002/11/24 20:29:56  brighton
# Imported sources
#
# Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
#
#
#INDENT-ON*
#
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#***********************************************************************
#


# The effect of shell code is to set up the QLT_TMP_DIR variable to
# point to the temporary directory for the QLT, to execute the 
# dhsQlTool-backend tcl script, and to remove the temporary directory 
# and its contents after that script exits.
#
# (allan: 2004-08-24: split this code out of dhsQlTool-backend, since it
#  didn't work correctly under Linux)
#
# Usage: dhsQlTool ?DISPLAY? ?CDHSQLTOOL_PLUGIN?

# Figure out the DHS base dir
PRG="$0"

while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '.*/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
DIR=`dirname "$PRG"`/..
DHS_BASE=`(cd $DIR; pwd)`; export DHS_BASE

QLT_TMP_DIR=/tmp/dhsQlTool.$$; export QLT_TMP_DIR
mkdir -p $QLT_TMP_DIR
trap "rm -rf $QLT_TMP_DIR; exit"  0 INT

if [ $# -ge 1 ] ; then
    DISPLAY=$1; export DISPLAY 
fi
if [ $# -ge 2 ] ; then
    CDHSQLTOOL_PLUGIN=$2; export CDHSQLTOOL_PLUGIN 
fi

echo "display is now \"$DISPLAY\""
test -z $CDHSQLTOOL_PLUGIN || echo "QlPlugin is now \"$CDHSQLTOOL_PLUGIN\""

exec ocswish $DHS_BASE/tcl/dhsQlTool-backend.tcl
