.\"/*+
.\"************************************************************************
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"*
.\"*	Name			: mediaQueue.1
.\"*
.\"*	Date			: Jan 28, 1998
.\"*
.\"*	SCCS data		: @(#)
.\"*	    Module Name		: mediaQueue.1
.\"*	    Version Number	: 1.6
.\"*	    Release Number	: 1
.\"*	    Last Updated	: 03/05/99
.\"*
.\"*	Written by		: Shannon Jaeger
.\"*
.\"*	Modification History:
.\"*	    98/01/28 SDJ	: Copied from VLT and remove al 
.\"*				  library dependencies.
.\"*	    98/03/01 SDJ	: updated to reflect cdMake becoming
.\"*				  cdPrep and cdWrite.
.\"*	    98/07/20 SEC	: Bit of a cleanup.
.\"*	    99/02/22 SDJ	: Updated to reflect new queuing algorithm
.\"*				  and interfacing with the new am lib.
.\"*	    99/03/05 NRH	: Added rollback option.
.\"*
.\"****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"************************************************************************
.\"-*/
.TH MEDIAQUEUE 1 07/12/1998 "CADC"

.SH NAME
mediaQueue \- Gathers data into units to be written to physical media.

.SH SYNOPSIS
.B mediaQueue
.B \-i
.I mediaId
[
.B \-force 
] [
.B \-rollback 
] [
.B \-num_units
.I integer
] [
.B \-v 
] [
.B \-V 
]

.SH DESCRIPTION
.B mediaQueue
is a utility that is used to queue units of media. 
It keeps a full log of its activities in the file 
.I mediaQueue.mediaId.log.

When invoked,
.B mediaQueue 
queries the 
.B Archive Media 
database, requesting the list of files currently inhabiting the 
Retrieval Staging Area for the given
.I mediaId. (See 
.B mediaIngest
for information on adding files to the database).
From this list of files,
.B mediaQueue
chooses a group of files which will populate the next queued unit of media.
Each unit will fill a single medium, such as as CD-ROM.
The media unit can be written to the medium by using other 
Archive Media applications such as 
.B mediaPrep
followed by 
.B mediaWrite. 

.B mediaQueue
creates a media unit name for each unit by appending a counter to 
the root media unit name.  The counter is padded zeros to a specific
precision.
The root media unit name and the precision value
are specified in the 
.B Media Archive
database tables.  For example, if the media unit name root is 'USER1_' and
the last media unit created was 'USER1_014' then the new media unit will
be 'USER1_015'.

The file selection algorithm
.B mediaQueue 
gives preference to files which have earlier notification dates, or
are older. If an older file will not fit onto the unit of media,
.B mediaQueue 
may select a more recent file.
Two files are considered to have the same notification date if 
their dates are within 24 hours of each other.

.B mediaQueue
will place the contents of a directory on multiple media if and only
if the contents of the directory is bigger than the meida request's
split size.  The split size is stored in the
.B Archive Media
database.  Typically, this value should be about half the size of the media.

.B mediaQueue
performs some error checking on the files, and ensures they still
exist in the Data Retrieval areas before queuing the media unit(s).

.SH OPERATION
The
.B \-i
.I mediaId
parameter must be specified on the command line. Under normal operation, 
.B mediaQueue
will only queue all full units of media (such as CD-ROM) that are available.
.I mediaId 
is a media ID number for a media request which will be filled..

.SH OPTIONS
.TP
.B \-force
Forces 
.B mediaQueue 
to queue a partial unit of media, if less than a full unit is available. 
.TP
.B \-rollback
Causes 
.B mediaQueue 
to roll back the number of units specified with the 
.B \-num_units 
option.
.TP
.B \-num_units \fIinteger\fR
Specifies the maximum number of units of media to queue.  The integer
value must be a positive integer.
.TP 
.B -v
Verbose.  Print all information and error messages to standard out,
.I stdout
.TP
.B -V
Version.  Print version numbers and quit.
.TP
.B -? -h -help
Help.     Prints the usage message and quit.

.SH USAGE
.B mediaQueue
requires no operator input while it is running.

.SH EXAMPLES
.TP 3
.B 1.
The following is an example showing how to queue a single unit
of media.  It queues enough data to fill a single medium such as
a CD-ROM.
.RS 8n
.sp 1n
.nf
.BR "example% mediaQueue \-i "  1 " \-num_units "  1
.IB "messages from " mediQueue
.sp 1n
.fi
.RE
.RS 3
The data will be queued for media request 
.B 1
in this example and only a single unit of media will be queued.
.RE
.TP 3
.B 2.
The following is an example which queues all 
.BR full
units of media.  All available data is assigned to new media unit
name, or grouped into  `units' of media.  If the last unit of media
is not full then it will not be queued.
.RS 8n
.sp 1n
.nf
.BR "example% mediaQueue \-i " 5 " \-v"
.IB "messages from " mediaQueue
.sp 1n
.fi
.RE
.RS 3
The data to be queued is for media request
.B 5.
Since the 
.B \-v
option is also given the operator will be informed of all 
activities performed by
.B mediaQueue
.RE
.TP 3
.B 3.
The following example forces queuing of data. All available data
is queued regardless, even if the unit of media is not full.
.RS 8n
.sp 1n
.nf
.BR "example% mediaQueue \-i " 2 " \-force"
.IB "messages from " mediaQueue
.sp 1n
.fi
.RE
.RS 3
All  data not already assigned to a media unit is queued for media request
.B 2. 
.RE

.SH FILES
.SS ~/.dbrc
The
.I ~/.dbrc
file contains information about each database that a user may 
reference with executables such as 
.BR mediaQueue .
More specifically it contains information about SYBASE servers, 
databases, user names and associated passwords. 

A database reference must contain a server/database pair followed
by the user's name and password. Each line of the 
.I ~/.dbrc
file must contain a complete server/database reference for every 
database which may be accessed through this file. Each line of
this file must be arranged in the following order:
 
.I server database username password

Each item should be separated by whitespace (spaces and/or tabs).
If a required database is not included in the 
.I ~/.dbrc 
file, 
.B mediaQueue
will prompt for a user's name and password.

.SS libAm.config
.B mediaQueue 
uses the CADC 
.B Archive Media
.RB ( am )
library which requires its own configuration file.  Refer
to the 
.B am 
man page for more information on this file.

.SH SECURITY
In order to ensure a secure
.I ~/.dbrc
file,
.B mediaQueue
requires that the
file resides in the directory specified by the 
.B HOME 
environment variable, and the file protection must restrict read and write 
access to the file owner.

.SH TABLES
.B mediaQueue
gets the information necessary to queue each file from the 
.B Archive Media
.RB ( am )
database tables.  The location of the 
.B am 
database, and the name of the
tables are specified in the configuration file for the 
.RB ( am )
library. These tables must exist for 
.B mediaQueue
to run correctly.

The following is a list of SYBASE tables that must be present for 
.B mediaQueue
to run correctly:
.TP
.B mediaArchive..media
.TP
.B mediaArchive..media_files
.TP
.B mediaArchive..media_units
.TP
.B mediaArchive..mediaTypes

.SH ENVIRONMENT VARIABLES
The environment variable 
.B LIBAM_CONFIG_DIR
may be set to the path of the directory where the 
.B am
library configuration file can be found. If
.B LIBAM_CONFIG_DIR
is not set, the environment variable
.B DEFAULT_CONFIG_DIR
should be set to the path where the file can be found.

The environment variable
.B HOME
must be set to the user's home directory.  If this environment variable
is not set correctly,
.B mediaQueue
may not find the correct
.I~/.dbrc
file containing database information.

.SH DIAGNOSTICS
.B mediaQueue
returns a 0 to the calling environment upon successful completion.
Otherwise a non-zero number is returned.

.SH SEE ALSO
.BR mediaIngest(1),
.BR cdPrep (1),
.BR cdWrite (1),
.BR am (3), 
and
.BR db (3).

.SH BUGS
None known.

.SH AUTHOR
Steve Cockayne
.br
Shannon Jaeger
.br


National Research Council of Canada 
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
