#!/bin/sh
#***********************************************************************
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#
# (c) 1997                              (c) 1997
# National Research Council             Conseil national de recherches
# Ottawa, Canada, K1A 0R6               Ottawa, Canada, K1A 0R6
# All rights reserved                   Tous droits reserves
#                                       
# NRC disclaims any warranties,         Le CNRC denie toute garantie
# expressed, implied, or statu-         enoncee, implicite ou legale,
# tory, of any kind with respect        de quelque nature que se soit,
# to the software, including            concernant le logiciel, y com-
# without limitation any war-           pris sans restriction toute
# ranty of merchantability or           garantie de valeur marchande
# fitness for a particular pur-         ou de pertinence pour un usage
# pose.  NRC shall not be liable        particulier.  Le CNRC ne
# in any event for any damages,         pourra en aucun cas etre tenu
# whether direct or indirect,           responsable de tout dommage,
# special or general, consequen-        direct ou indirect, particul-
# tial or incidental, arising           ier ou general, accessoire ou
# from the use of the software.         fortuit, resultant de l'utili-
#                                       sation du logiciel.
#
#***********************************************************************
#
# FILENAME
# dhsTestCmdr/scripts/dhsTestCmdr
#
# PURPOSE:
# This is a script that will start the DHS test commander.
#
# METHOD NAME(S)
# None.
#
#INDENT-OFF*
# $Log: not supported by cvs2svn $
# Revision 1.1.1.1  2002/02/21 20:23:35  tpaz
#
#
# Revision 1.1.1.1  1999/08/23 19:58:38  cvs-tuc
# Initial install into CVS of dhs-0.16
#
#INDENT-ON*
#
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#***********************************************************************
#

#
#  Not sure why I need this, but otherwise the rest doesn't work.
#

set X { "$0" "$@"; shift 2; exec /gemini/ocs/bin/solaris/ocswish "$@"
}; unset X


#
# __source_path is the directory from which this file was loaded. Other
# DHS TestCmdr source files will be loaded from a path relative to
# this directory.
#

set __source $argv0
set __source_path [ file dirname $argv0 ]
if { $__source_path == "." } {
    set __source_path "[ pwd ]"
    set __source "[ pwd ]/$__source"
} elseif { [ string index $__source_path 0 ] != "/" } {
    set __source_path "[ pwd ]/$__source_path"
    set __source "[ pwd ]/$__source"
}

#
# Create the long version information.
#

set _dhgLongVersion ""
set _dhgLongVersion [ format "%21s      %s\n" "dhsTestCmdr"		\
    "0.11 (c) 1998 NRC/CNRC" ]
append _dhgLongVersion [ format "%21s      %s\n" "Tcl/Tk" "[ info patchlevel ]" ]

#
# Source the tcl/tk code specific to the dhsTestCmdr, find the location
# of the help files and parse the command line arguments.
#

source $__source_path/../tcl/dhsTestCmdr.tcll

#
# fire up the main test commander
#

#dhsTestCmdr $argv $argc

