#!/bin/csh -f
#***********************************************************************
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#
# (c) 1998				(c) 1998
# National Research Council		Conseil national de recherches
# Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
# All rights reserved			Tous droits reserves
# 					
# NRC disclaims any warranties,		Le CNRC denie toute garantie
# expressed, implied, or statu-		enoncee, implicite ou legale,
# tory, of any kind with respect	de quelque nature que se soit,
# to the software, including		concernant le logiciel, y com-
# without limitation any war-		pris sans restriction toute
# ranty of merchantability or		garantie de valeur marchande
# fitness for a particular pur-		ou de pertinence pour un usage
# pose.  NRC shall not be liable	particulier.  Le CNRC ne
# in any event for any damages,		pourra en aucun cas etre tenu
# whether direct or indirect,		responsable de tout dommage,
# special or general, consequen-	direct ou indirect, particul-
# tial or incidental, arising		ier ou general, accessoire ou
# from the use of the software.		fortuit, resultant de l'utili-
# 					sation du logiciel.
#
#***********************************************************************
#
# FILENAME
# dhs/scripts/dhsCleanup
#
# PURPOSE:
# This file removes the temporary files created by the DHS library
#
# The script runs the imp cleanup routine first, so it has the same
# lethal properties as the imp cleanup routine.
#
#INDENT-OFF*
# $Log: not supported by cvs2svn $
# Revision 1.1.1.1  2002/09/30 20:33:32  brighton
# Imported sources
#
# Revision 1.1.1.1  2002/02/21 20:23:33  tpaz
#
#
# Revision 1.1.1.1  1999/08/23 19:57:59  cvs-tuc
# Initial install into CVS of dhs-0.16
#
#INDENT-ON*
#
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#***********************************************************************
#

cleanup

find /tmp -user $USER -name 'dhsIm*' -exec rm {} \;
