#!/bin/bash
#
# This file is originally /gemini/dhs/scripts/GemBootStart.
# It is copied to the /etc/rc2.d/S98GemDHS on the DHS server machine
# as well as /etc/rc2.d/K98GemDHS.  Only edit the original file and
# then make copies in the system directories.

case `/usr/ucb/whoami` in

'root')
	SU="su - gemdhs -c "
	;;
'gemdhs')
	SU=""
	;;
*)
	echo "Must be gemdhs to run GemBootStart"
	exit 1
	;;
esac

# Set up the environment for this script and all spawned off processes
DHS_LOG_DIR=/var/dhs
[ ! -d $DHS_LOG_DIR ] && ( mkdir $DHS_LOG_DIR ; chown gemdhs:staff $DHS_LOG_DIR ; chmod g+w $DHS_LOG_DIR )
[ ! -d $IMP_SCRATCH ] && ( mkdir $IMP_SCRATCH )

# Set DHS_BASE if not already set
DHS_BASE=${DHS_BASE:=/gemini/dhs-0.19};
echo "\$DHS_BASE is now \"$DHS_BASE\""

# Set OCS_BASE if not already set
OCS_BASE=${OCS_BASE:=$DHS_BASE/external/ocs};
echo "\$OCS_BASE is now \"$OCS_BASE\""

# Set GEMINI_BASE if not already set
GEMINI_BASE=${GEMINI_BASE:=$DHS_BASE/..};
echo "\$GEMINI_BASE is now \"$GEMINI_BASE\""

# Set IMP_STARTUP if not already set
IMP_STARTUP=${IMP_STARTUP:=$DHS_BASE/imp_startup}

# Change LD_LIBRARY_PATH order so that /usr/lib comes after DHS libs
# so that it gets correct version of libgen.so

#
#  Removed LD_LIBRARY_PATH. The executables in dhs-0.19 are built against
#  the /gemini/dhs-0.19 libraries, and so LD_LIBRARY_PATH is not
#  needed to find the libraries.

# LD_LIBRARY_PATH=$DHS_BASE/lib/solaris:$DHS_BASE/external/lib/solaris:$DHS_BASE/sybase/lib:$OCS_BASE/lib/solaris:$OCS_BASE/external/lib/itcl:$OCS_BASE/external/lib/tclX7.6.0:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH

# echo "Using LD_LIBRARY_PATH = \"$LD_LIBRARY_PATH\""

dhs_start() {
	PROG=$1
	BASE=`basename $PROG`
	if [ $# -ge 2 ]
	then
		shift
		ARGS=" $*"
	else
		ARGS=""
	fi

	echo "dhs_start: Starting $PROG$ARGS"
	#$SU$PROG$ARGS >> $LOG 2>&1 < /dev/null &
        BASEPROG=`basename $PROG`
       	$SU$PROG$ARGS < /dev/null | 2>&1 logger -p local0.debug -t $BASEPROG &
	sleep 1
}

case $1 in

start)
	case `hostname` in
	archie)
	      $0 stop

              DEFAULT_CONFIG_DIR=$DHS_BASE/conf/archie
              export DEFAULT_CONFIG_DIR
              echo "Using config files in \"$DEFAULT_CONFIG_DIR\""

	      dhs_start $DHS_BASE/external/bin/solaris/master
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsStatus
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsSim4Data
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsData -debug MIN NO_DHS
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsQlServer -master
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsCommand
	      ;;
	aladfar)
	      $0 stop

              DEFAULT_CONFIG_DIR=$DHS_BASE/conf/aladfar
              export DEFAULT_CONFIG_DIR
              echo "Using config files in \"$DEFAULT_CONFIG_DIR\""

	      dhs_start $DHS_BASE/external/bin/solaris/master
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsStatus
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsSim4Data
	      sleep 20
	      dhs_start $DHS_BASE/bin/solaris/dhsData -debug MIN NO_DHS -noDb -temp /staging/temp -perm /staging/perm
	      sleep 10
		# This is a slave QLS connected to the master at the summit.
	      dhs_start $DHS_BASE/bin/solaris/dhsQlServer -master
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsCommand
	      ;;
	draco)
	      $0 stop

              DEFAULT_CONFIG_DIR=$DHS_BASE/conf/draco
              export DEFAULT_CONFIG_DIR
              echo "Using config files in \"$DEFAULT_CONFIG_DIR\""

	      dhs_start $DHS_BASE/external/bin/solaris/master
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsQlServer
	      ;;
	sabrina)
	      $0 stop

              DEFAULT_CONFIG_DIR=$DHS_BASE/conf/sabrina
              export DEFAULT_CONFIG_DIR
              echo "Using config files in \"$DEFAULT_CONFIG_DIR\""
              cd /var/dhs 
	      dhs_start $DHS_BASE/external/bin/solaris/master
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsStatus
	      sleep 20
	      dhs_start $DHS_BASE/bin/solaris/dhsData -debug MIN NO_DHS
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsStorage
	      sleep 10
	      dhs_start $DHS_BASE/bin/solaris/dhsCommand
	      ;;
	*)
	      echo "DHS does not run on `hostname`"
	      ;;
	esac
	;;
stop)
        $SU $DHS_BASE/scripts/dhsCleanup
        ;;
*)
	echo "Usage: GemBootStart [ start | stop ]"
	exit 1
	;;
esac

