#!/bin/tcsh
if ( $#argv != 1 ) then
	echo "usage: MakeUserMedia <program>"
	exit
endif
set program = $1

#
# Copy the readme file.
#

dhsStoPut -copies 2 -prefix ${program}- -user $program 			\
		-f GNreadme.txt $program/GNreadme.txt
dhsStoPut -archive Gemini -comp NONE 					\
		-f GNreadme.txt $program/GNreadme.txt

#
# Copy the processed files.
#

foreach file (proc_logs/*)
	dhsStoPut -copies 2 -prefix ${program}- -user $program 		\
		-f $file $program/$file
	dhsStoPut -archive Gemini -comp NONE 				\
		-f $file $program/$file
end

#
# Copy the raw files.
#

foreach file (raw/*)
	dhsStoPut -copies 2 -prefix ${program} -user $program 		\
		-f $file $program/$file
	dhsStoPut -archive Gemini -comp NONE 				\
		-f $file $program/$file
end
