.\"/*+ $Id: dhsStoPut.1,v 1.1.1.1 2002-11-24 20:31:15 brighton Exp $
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) 2000				(c) 2000
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-	ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME:
.\" dhsStoPut/doc/dhsStoPut.1
.\"
.\" PURPOSE:
.\" Describe the Storage Server Client 'dhsStoPut' which pushes data
.\" at the DHS Storage Server.
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/02/21 20:23:35  tpaz
.\"
.\"
.\" Revision 1.2  2001/01/12 23:30:56  jaeger
.\" Fixed typos and added a copy of the configuration file.
.\"
.\" Revision 1.1  2000/12/04 22:04:01  jaeger
.\" Initial revision
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.\"
.                       \" Ty macro to start an indent for each type def.
.de Ty
.ie n .TP 14n
.el .TP 16n
..
./"
.TH dhsData  1 27/11/00 "CADC"

.SH NAME

dhsStoPut \- Pushes data, files, to a DHS Storage Server. 


.SH SYNOPSIS

.B dhsStoPut
.B \-archive <archiveStream>
.B \-f <srcFilePath\fI1\fB>
[ 
.B <destFilePath\fI1\fB> 
]
.B \-f <srcFilePath\fI2\fB>
[
.B <destFilePath\fI2\fB> 
] ... 
.B \-f <srcFilePath\fIn\fB>
[
.B <destFilePath\fIn\fB> 
] [
.B \-s StorageServerIdentity
] [
.B \-id dhsStoPutIdentity
] [
.B \-ip StorageServerIpAddress
] [
.B \-comp ASIS|GZIP|NONE
] [
.B \-debug NONE|MIN|FULL
] [
.B \-simulate
] [
.B \-V
]

.B dhsStoPut
.B \-user <userStream>
.B \-f <srcFilePath\fI1\fB>
[ 
.B <destFilePath\fI1\fR> 
]
.B \-f <srcFilePath\fI2\fB>
[
.B <destFilePath\fI2\fB>
] ... 
.B \-f <srcFilePath\fIn\fB>
[
.B <destFilePath\fI2\fB> 
] [
.B \-s StorageServerIdentity
] [
.B \-id dhsStoPutIdentity
] [
.B \-ip StorageServerIpAddress
] [
.B \-comp ASIS|GZIP|NONE
] [
.B \-copies <numCopies>
] [
.B \-debug NONE|MIN|FULL
] [
.B \-media CD|DVD|DAT|EXABYTE
] [
.B \-prefix <unitNamePrefix>
] [
.B \-simulate
] [
.B \-V
]

.SH DESCRIPTION

.B dhsStoPut 
pushes one or more files to the DHS Storage Server.
The files are added to data streams and written to media.
Usually the data is being added to existing data streams but
in some cases a new data stream may be created.

.SH OPERATION

.B dhsStoPut
uses the Interprocess Message Passing (IMP) system to send 
information and data to the Storage Server.  The Storage Server
that the data is sent to is identified by an IP Address and
and IMP identity string read either from the \-s and \-ip
command-line options. If the \-s and/or \-ip are not specified then 
this information is gathered from the \fBdhsStoPut\fR configuration
file, \fIdhsStoput.config\fR.

Only "authorized" clients may connect to the Storage Server.
The Storage Server uses the clients IMP identity string and
the machine the client is running to determine if it is 
authorized.  For the \fBdhsStoPut\fR client the IMP identity
is obtained from the \-id command-line option or if it is not
specified from its configuration file, \fIdhsStoPut.config\fR.

.SS Data Streams
Files, data, are routed to streams (groups) of data.  Each
data stream represents a different set of media
being created by the Storage Server.  The media created contain
the data collected by the Storage Server, 
There are two types of data streams: archive and user.

\fBArchive Streams\fR
Archive data streams contain data that is destined for a data
archive, such as the Gemini or CFHT data archive.  There may be
more then one data stream for a given archive depending on how
the archive centre wishes to segregate the data.  

To "push" data
to an archive stream use the \fB\-archive\fR command-line argument.
The archive stream specified by the \fB\-archive\fR argument must
exist before any data can be pushed to the Storage Server.

Normally archive streams are "open" indefinitely since there will
always be new data coming from the telescope for the archive.

\fBUser Streams\fR
User data streams contain data that a particular user has requested.
The data will be written on some sort of transportable medium and
at some point will be distributed to the user.  

To "push" data to a user stream use the \fB\-user\fR command-line
argument.  The user data stream specified by the \fB\-user\fR 
argument need not exist prior to the data being pushed.  If the stream
does not already exist a new stream will be created for the user.

Since users do not typically request data continuously, user data
streams are "closed" once all of the data has been written to the
specified media. User data streams may be re-opened at a later date
if the same user requests more data.

.SS Specifying Files
At least one file must be specified on the command\-line with the
.B \-f
argument. More than one file can be sent to the Storage Server 
by using multiple
.B \-f 
arguments.  The \fB\-f\fR argument takes the arguments: source
file path and the destination file path (destination file path is
optional).

\fBSource File Path\fR
The \fBsrcFilePath\fR specifies the file path to the file that 
is to be sent. This path is on the local machine where
\fBdhsStoPut\fR is executed. 

\fBDestination File Path\fR
Since the desired location of the file on the media may be different
than its source file path, a destination file path may be given.
The \fBdestFilePath\fR specifies where the file
is to reside on the media that is to be written.  If the  
\fBdestFilePath\fR is not given then root name ( everything following
the last / ) of the source file path is used as the \fBdestFilePath\fR.

.SS Media Units
Once the Storage Server has received the data for an archive or
for a user request it will break the data into what is known
as media units.  Each media unit contains a number of files, 
data that have been grouped together in order to be written to a single CD,
DVD, Mammoth Tape, or some other form of media. 

.SH OPTIONS
Many of the command-line options for \fBdhsStoPut\fR are dependent
on whether the \fB\-archive\fR (archive mode) or the \fB-user\fR 
(user mode) command-line argument
was given.  Please be careful when selecting the options.  The
options are:
.TP
.B \-comp ASIS | GZIP | NONE
Compression. Determines whether the file is to be compressed 
with \fBgzip\fR, not
compressed at all, or the file should be left as is when it is written
to the media.  This option may be used in either user or archive
mode.
.TP
.B \-copies <numCopies>
Number of Copies. Specifies the number of copies 
of each media unit that is
to be written.  \fB<numCopies>\fR must be an integer value. 
This option
can be used only when in user mode.
If this option is not specified then the value from the 
\fBdhsStoPut\fR configuration file, \fI dhsStoPut.config\fR, is used.
.TP
.B -debug NONE | MIN | FULL
Debug mode.  Set the debug mode for \fBdhStoPut\fR.
\fBNONE\fR is the default. \fBMIN\fR and \fBFULL\fR print a varying 
level of debug messages to standard-out. This option can be used
in both user and archive mode.
.TP
.B \-id <dhsStoPutId>
dhsStoPut Identity. Specifies the IMP identity for the \fBdhsStoPut\fR client.
This identity string must match one of the entries in the DHS Storage
Server's configuration file, \fIdhsStorage.config\fR.  If this value
is not specified then the value in the \fBdhsStoPut's\fR configuration
file, \fIdhsStoPut.config\fR, is used. This option can be used
in both user and archive mode.
.TP
.B \-ip <storageServerIpAddr>
Storage Server IP Address.  Specifies the IP Address of the DHS
Storage Server, the machine where the Storage Server is running.
If this value
is not specified then the value in the \fBdhsStoPut's\fR configuration
file, \fIdhsStoPut.config\fR, is used. This option can be used
in both user and archive mode.
.TP 
.B \-media CD | DVD | EXA
Media Type.  Specifies the type of media that the data is to be
written to.  This option can be used in user mode only.
If this option is not specified then the value specified in the 
\fBdhsStoPut\fR configuration file, \fI dhsStoPut.config\fR, is used.
.TP 
.B \-prefix <unitNamePrefix>
Unit Name Prefix.  Specifies the prefix to be used when constructing
the names for each of the media units created.  
This option can be used in user mode only.
If no value is specified then the default value,
"<organization>_<userStream>_", is used, where <organization> 
is specified in the configuration file, and <userStream> is the
string provided with the \fB-user\fR argument.
.TP
.B \-s <storageServerIdentity>
Storage Server.  Specifies the IMP identity string for the DHS Storage
Server that \fBdhsStoPut\fR will connect to.  This server must already
be running.  If this option is not specified then the value in
the \fBdhsStoPut\fR configuration file, \fIdhsStoPut.config\fR, is
used. This option can be used
in both user and archive mode.
.TP
.B \-simulate
Simulate mode. Set the simulate mode for \fBdhStoPut\fR.
When this flag is set, \fBdhsStoPut\fR operates in simulate mode,
pretending to send files to the \fBStorage Server\fR.
.TP
.B -V     
Version. Print version numbers and quit.


.SH EXAMPLES


.SH DIAGNOSTICS

Returns 0 upon successful completion, otherwise a non-zero value is
returned.

Also displayed is the status of the commands sent, 
any messages returned by the Storage 
Server.

.SH FILES
.SS dhsStoConfig.config
.B dhsStoPut
requires a configuration file which contains information needed
to send data to the Storage Server.  The file should be named
\fI dhsStoConfig.config\fR and located
in a directory 
specified by a \fBDEFAULT_CONFIG_DIR\fR environment variable (see the
\fB ENVIRONMENT VARIABLES \fR section ).  The configuration file
format is as follows:

.nf
.na
#
#  Application Identification.
#
#
# Keyword       Host Address	Identity
# -------       ------------
#

identity	siska		dhsStoPut1
identity	salish		dhsStoPut2


#
# Storage Server to connect to and IP Address.
#
# Keyword       Identity         Host Address
# -------       --------         ------------
#

storageServer    storageServer    siska


#
# Organization creating the media.
#
# Keyword       organization
# -------       -------------
#

organization	CADC


#
# Default command-line argument values.
#
# Keyword	compression	mediaType	numCopies
# -------	-----------     ---------	---------

defaults	ASIS		CD		1


#
# MediaType Mapping
#
#
# Keyword	retrieve type	DHS (storage) type
# -------	-------------   ------------------
#

mediaType	FTP		MD
mediaType	EXABYTE		EXABYTE
mediaType	CD		CD
mediaType	DVD		DVD

.ad
.fi

.SS dhsStorage.config
The authorized Storage Server clients are listed in the
Storage Server's configuration file.  The \fBdhsStoPut\fR
client must connect as one of these authorized clients or else the
Storage Server will refuse the connection.  Refer to
the \fB dhsStorage\fR man page for more information on this
file.
 
.SH ENVIRONMENT VARIABLES
The environment variable 
.B DHSSTOPUT_CONFIG_DIR
can be set to the path of a directory containing the configuration file.  If 
.B DHSSTOPUT_CONFIG_DIR
is not set, the environment variable 
.B DEFAULT_CONFIG_DIR
should be set to a path where the configuration file can be found.

.SH SEE ALSO

.BR dhsStorage (1).


.SH DOCUMENTS

.TP
.B DHS User Manual
.TP
.B ICD 3 - Bulk Data Transfer
.TP
.B ICD 3.2 - The DHS Command Interface
.TP
.B Interprocess Message Passing (IMP) System


.SH BUGS
None known.


.SH AUTHORS
Shannon Jaeger
.br

National Research Council
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre
