#!/bin/tcsh
if ( $#argv != 1 ) then
	echo "usage: MakeClassicalMedia <program>"
	exit
endif
set program = $1

#
# Copy the processed files.
#

foreach file (`find . -type f | sort `)
	if ( -f $file ) then
		dhsStoPut -copies 2 -prefix ${program}- -user $program 		\
			-f $file $file
		dhsStoPut -archive Gemini -f $file $file -comp NONE
	endif
end
