# Makefile

NAME = press
SOURCES = digitize.c gzip.c gzip_inflate.c gzip_util.c hcomp.c h_decomp.c hinv.c h_press.c hsmooth.c htrans.c local_press.c none.c press.c pr_msg.c ulda.c undigitize.c ux_press.c

include ../conf/cc_lib.mk
