#!/bin/sh
#***********************************************************************
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#
# (c) 1997                              (c) 1997
# National Research Council             Conseil national de recherches
# Ottawa, Canada, K1A 0R6               Ottawa, Canada, K1A 0R6
# All rights reserved                   Tous droits reserves
#                                       
# NRC disclaims any warranties,         Le CNRC denie toute garantie
# expressed, implied, or statu-         enoncee, implicite ou legale,
# tory, of any kind with respect        de quelque nature que se soit,
# to the software, including            concernant le logiciel, y com-
# without limitation any war-           pris sans restriction toute
# ranty of merchantability or           garantie de valeur marchande
# fitness for a particular pur-         ou de pertinence pour un usage
# pose.  NRC shall not be liable        particulier.  Le CNRC ne
# in any event for any damages,         pourra en aucun cas etre tenu
# whether direct or indirect,           responsable de tout dommage,
# special or general, consequen-        direct ou indirect, particul-
# tial or incidental, arising           ier ou general, accessoire ou
# from the use of the software.         fortuit, resultant de l'utili-
#                                       sation du logiciel.
#
#***********************************************************************
#
# FILENAME
# dhsConsole/scripts/dhsConsole
#
# PURPOSE:
# This is a script that will start the DHS Console.
#
# METHOD NAME(S)
# None.
#
#INDENT-OFF*
# $Log: dhsConsole,v $
# Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
#
#
# Revision 1.1.1.1  1999/08/23 19:58:13  cvs-tuc
# Initial install into CVS of dhs-0.16
#
#INDENT-ON*
#
#***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#***********************************************************************
#

# Figure out the DHS base dir
PRG="$0"

while [ -h "$PRG" ]; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '.*/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
DIR=`dirname "$PRG"`/..
DHS_BASE=`(cd $DIR; pwd)`; export DHS_BASE

exec ocswish $DHS_BASE/lib/dhsConsole/dhsConsole.tcl ${1+"$@"}

