# Makefile

NAME = dhsStorage
SOURCES = arg.C config.C main.C msg.C stoAction.C stoActionCmd.C stoCleanup.C stoConnection.C stoDbm.C stoDevice.C stoDhs.C stoFile.C stoFiveState.C stoGet.C stoInfoCmd.C stoMedia.C stoNode.C stoNotify.C stoPrepare.C stoPut.C stoQueue.C stoRefreshCmd.C stoRequestCmd.C stoRetrieve.C stoSeqCmd.C stoStage.C stoUnit.C stoWrite.C
LIBS = -ldhs++ -ldhs -ldhsSta -ldhsGen -lgen -lam -ldb -lpress $(TCLTK_LDLIBS)

include ../conf/cxx_bin.mk
