#!/bin/csh -f
#/*+
#************************************************************************
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#*
#* (c) 1998.				(c) 1998.
#* National Research Council		Conseil national de recherches
#* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
#* All rights reserved			Tous droits reserves
#* 					
#* NRC disclaims any warranties,	Le CNRC denie toute garantie
#* expressed, implied, or statu-	enoncee, implicite ou legale,
#* tory, of any kind with respect	de quelque nature que se soit,
#* to the software, including		concernant le logiciel, y com-
#* without limitation any war-		pris sans restriction toute
#* ranty of merchantability or		garantie de valeur marchande
#* fitness for a particular pur-	ou de pertinence pour un usage
#* pose.  NRC shall not be liable	particulier.  Le CNRC ne
#* in any event for any damages,	pourra en aucun cas etre tenu
#* whether direct or indirect,		responsable de tout dommage,
#* special or general, consequen-	direct ou indirect, particul-
#* tial or incidental, arising		ier ou general, accessoire ou
#* from the use of the software.	fortuit, resultant de l'utili-
#* 					sation du logiciel.
#*
#************************************************************************
#*
#*   Script Name:	addMedia
#*
#*   Purpose:
#*	To add a User or Archive to the Storage Media tables.  Also
#*	creates a directory for the data in the appropriate place.
#*
#*   Date		: Aug 26, 1998
#*
#*   SCCS data		: @(#)
#*	Module Name	: addMedia
#*	Version Number	: 1.8
#*	Release Number	: 1
#*	Last Updated	: 04/28/99
#*
#*   Programmer		: Shannon Jaeger
#*
#*   Modification History:
#*	1999/01/24 SDJ	: Changed the logic a bit, more gotos!
#*			  Also changed all sql commands to use input and
#*			  output files.
#*	1999/04/15 NRH	: Changed to use a configuration file to get table
#*			  and database names.
#*	1999/04/22 NRH  : Removed option to update an existing reqeust.
#*			  Removed mediaHost.
#*	1999/04/27 SDJ	: Now errors if the largest media request id was
#*			  not found.  Fixed spelling.
#*
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#************************************************************************
#-*/

#
# Initialization
# Note that the staging directory is the DHS Storage Servers retrival
# area and the mediHost is the name of the machine containing this
# directory.
#

#
#  Get required information from the am library configuration file. 
#

set env_line = `printenv | grep LIBAM_CONFIG_DIR`
set config_dir_path1 = `echo $env_line |sed 's/LIBAM_CONFIG_DIR=//'`
set config_file_path = "$config_dir_path1/libAm.config"

if ( -e $config_file_path ) then
    echo "    Configuration file '$config_file_path' has been opened"
else
    set env_line = `printenv | grep DEFAULT_CONFIG_DIR`
    set config_dir_path2 = `echo $env_line |sed 's/DEFAULT_CONFIG_DIR=//'`
    set config_file_path = "$config_dir_path2/libAm.config"

    if ( -e $config_file_path ) then
	echo "    Configuration file '$config_file_path' has been opened"
    else
	set config_file_path = "./libAm.config"

	if (  -e $config_file_path ) then
	    echo "    Configuration file '$config_file_path' has been opened"
	else
	    echo -n "Error - am library config file not found in the "
	    echo "following directories : "
	    echo "        ., $config_dir_path1, $config_dir_path2"
	    goto EXECERR
	endif
    endif
endif


set line = `cat $config_file_path | grep dataStage | grep -v \#`
set user_data_stage = $line[2]
set arch_data_stage = $line[3]

set line = `cat $config_file_path | grep amDb | grep -v \#`
set sybase_server = 	$line[2]
set sybase_database =	$line[3]
set media_table = 	$line[4]

set line = `cat $config_file_path | grep deviceTables | grep -v \#`
set media_types_table = $line[5]

set output_file = "/tmp/addMedia.output.$$"
set input_file = "/tmp/addMedia.input.$$"


#
#************************************************************************
# Get Command line args and determine there correctness.
#************************************************************************
#

if ( $#argv != 6 ) then
    echo "addMedia <name> <type> <medium_type> <prefix> <precision> <num_copies>"
    echo "    <name>            : Media name. (eg. login id)"
    echo "    <type>            : 'ARCH' for archive and 'USER' for user media."
    echo "    <medium_type>     : Type of medium data is to be stored on."  
    echo "                      : An example is CD."
    echo "    <prefix>          : Prefix for media (CD) names."
    echo "    <precision>       : Precision of the numerical number appended"
    echo "                        to the media (CD) names."
    echo "    <num_copies>      : Number of copies to make of each unit."
    exit 1
endif

set request_name = $1
set request_type = $2
set medium_type = $3
set request_prefix = $4
set unit_name_precision = $5
set num_copies = $6

if ( $request_type != "ARCH" && $request_type != "USER" ) then
   echo "Error: request type must be one of: 'ARCH'ive or USER"
   exit 1
endif

set nonNumerics = `echo $num_copies | sed -e 's/[0-9]//g'`
if ( $nonNumerics != "" || $num_copies < 1 ) then
   echo "Error: number of copies must be a positive numberical value"
   exit 1
endif

set nonCaps = `echo $request_prefix | sed -e 's/[A-Z1-9_-.]//g'`
if ($nonCaps != "") then
   echo "Error: prefix consist of upper case letters, digits, underscore, or "dot" (.)."
   exit 1
endif


onintr -


set sybase_info = `dbrc_get $sybase_server $sybase_database`


#
#************************************************************************
# Make sure the media type given is known by the database.
#************************************************************************
#

cat > $input_file << _EOF_
use $sybase_database
go
select media_type, count(*)
from $media_types_table
where media_type='$medium_type'
go
_EOF_

isql -S $sybase_server -U $sybase_info[1] -P $sybase_info[2]\
    -o $output_file -i $input_file
if ( $status ) then
    echo "Error: Unable to verify uniqueness."
    goto SYBERR
endif

set mediaTypeFound = `cat $output_file | awk 'BEGIN { found=0 ; } NF==2 && $2 ~ /^[0-9]$/ && $2 > 0 { found = 1 ; } END { print found ; }'`

if ( $mediaTypeFound == 0 ) then
    echo "Error: Invalid media type $medium_type"
    exit 1
endif


#
#************************************************************************
# Determine whether this is an old use or a new one.
#************************************************************************
#


cat > $input_file << _EOF_
use $sybase_database
go
select media_request_name, media_request_type, media_type, unit_name_root,
      unit_name_precision, num_copies, media_request_id
from $media_table
where media_request_type="$request_type" and media_request_name="$request_name"
go
_EOF_

isql -w 2000 -S $sybase_server -U $sybase_info[1] -P $sybase_info[2] -o $output_file -i $input_file
if ( $status < 0 ) then
    echo "Error: Unable to verify uniqueness."
    goto SYBERR
endif
if ( $status ) then
    echo "Error: Unable to verify media uniqueness."
    goto SYBERR
endif

set results = `cat $output_file | awk '$1 == rn { $1=$1; print$0}' rn=$request_name`
if ( "$results" != "" ) then

    #
    # old media request.  Prompt user to see if they wish to update
    # with new information.
    #
     
    echo $results
    set request_id=$results[7]
    if ( "$results[1]" == "$request_name" &&\
	"$results[2]" == "$request_type" ) then
	echo "Warning: Media already exists with request name $request_name "
	echo "and type $request_type"
	awk 'BEGIN {printf( "%10s %12s %12s %10s\n", "Request Id", "Request Name", "Request Type", "Media Type" ); printf( "%10s %12s %12s %10s\n", "----------", "------------", "------------", "----------" ); } $1 == rn { printf ("%10s %12s %12s %10s\n", $7, $1, $2, $3 ) }' rn=$request_name $output_file

	echo -n "Do you wish to create a new request with the same name and media type (y/n):"
	set answer = $<
	if ( "$answer" == "n" | "$answer" == "N" ) then
	    echo "The media request has not been created"
	    exit( 0 )
	else if ( "$answer" != "y" && "$answer" != "Y" ) then
	    echo "Error: incorrect answer, $answer"
	    exit 1
	endif
    endif 
endif

	 
#
#************************************************************************
# Get the largest request id from the database
#************************************************************************
#


#
# Try and use stored procedure get_mediId
#

cat > $input_file << _EOF_
use $sybase_database
go
declare @result int
exec get_medId @result output
select @result
go
_EOF_

isql -S $sybase_server -U $sybase_info[1] -P $sybase_info[2] -o $output_file -i $input_file
if ( $status ) then
    echo "Error: Unable to get the largest request id from sybase"
    goto SYBERR
endif

set request_id = `grep -- '[0-9]' $output_file | grep -v '(' | awk '$1 ~ /^[0-9]+/ { max = $1; } END { print max }'`

if ( "$request_id" == "" ) then
    echo "Error: Unable to get a new request id from SYBASE."
    goto SYBERR
endif


#
# Verify correctness of the database.
# 

cat > $input_file << _EOF_
use $sybase_database
go
select media_request_id
from $media_table
where media_request_id=$request_id
go
_EOF_

isql -S $sybase_server -U $sybase_info[1] -P $sybase_info[2] -o $output_file -i $input_file
if ( $status ) then
    echo "Error: Unable to get the largest request id from sybase"
    goto SYBERR
endif
set mediaIdFound = `grep -- '[0-9]' $output_file | grep -v '(' | awk 'BEGIN { found = 0; } $1 ~ /^[0-9]+/ { found = 1; } END { print found }'`


if ( $mediaIdFound != 0 ) then

  #
  # keys table is invalid so need to search media table entries.
  #

    cat > $input_file << _EOF_
use $sybase_database
go
update $media_table
select max(media_request_id) from media
go
_EOF_

    isql -S $sybase_server -U $sybase_info[1] -P $sybase_info[2] -o $output_file -i $input_file
    if ( $status ) then
	echo "Error: Unable to get the largest request id from sybase"
	goto SYBERR
    endif

    set last_id = `grep '[0-9]+*' $output_file| grep -v '(*)'`
    set request_id = `expr $last_id + 1`


    cat > $input_file << _EOF_
use $sybase_database
go
update keys
set keyValue=$request_id
go
_EOF_
    isql -S $sybase_server -U $sybase_info[1] -P $sybase_info[2] -o $output_file -i $input_file
    if ( $status ) then
	echo "Error: Unable to get the largest request id from sybase"
	goto SYBERR
    endif
endif



#
#************************************************************************
# Add the new use to the database
#************************************************************************
#

cat > $input_file << _EOF_
use $sybase_database
go
insert $media_table
(
    media_request_id,
    source_id,
    date_requested,
    date_completed,
    media_request_type,
    media_type,
    num_copies,
    unit_name_root,
    media_request_name,
    status,
    unit_name_precision
)
values(
 	$request_id,
	"dataServer",
	getdate(),
	NULL, 
	"$request_type", 
	"$medium_type", 
	$num_copies, 
	"$request_prefix", 
	"$request_name", 
	"I",
	$unit_name_precision
)
go
_EOF_

isql -S $sybase_server -U $sybase_info[1] -P $sybase_info[2] -o $output_file -i $input_file
if ( $status ) then
    echo "Error: Unable to insert into $media_table table."
    goto SYBERR
endif


#
#************************************************************************
# Create the user's directory after verify that the media was added.
#************************************************************************
#

cat > $input_file << _EOF_
use $sybase_database
go
select * from $media_table
where
  media_request_id=$request_id and
  media_request_name="$request_name" and
  media_request_type="$request_type" and
  media_type="$medium_type" and
  unit_name_root="$request_prefix" and
  unit_name_precision=$unit_name_precision and
  num_copies=$num_copies
go
_EOF_

isql -w 2000 -S $sybase_server -U $sybase_info[1] -P $sybase_info[2] -o $output_file -i $input_file
if ( $status ) then
    echo "Error: Unable to change the old media entry"
    goto SYBERR
endif

set mediaFound = `grep "$request_name" $output_file | awk 'BEGIN { out=0; } $1==id { out=1;} END { print out;}' id=$request_id`

if ( $mediaFound != 1 ) then
    echo "Error: New media was not found in the database."
    goto SYBERR
endif

if ( "$request_type" == "USER" ) then
    set newDir = "$user_data_stage/$request_id.$request_name"
else
    set newDir = "$arch_data_stage/$request_id.$request_name"
endif

mkdir $newDir >& /dev/null
if( $status ) then
    echo "Unable to create directory:"
    echo "     $newDir"
    exit 1
endif

echo ""
echo "The media ID for the altered/new media is: $request_id"
echo "You may start moving data to $newDir"
echo "Once all data is in this directory run 'mediaIngest -v -i $request_id'"
rm -f $output_file
exit 0


SYBERR:
    echo "  ********************   Input File  *************************"
    echo " "
    cat $input_file
    echo " "
    echo "  ********************   Output File *************************"
    echo " "
    cat $output_file
    echo " "
    rm -f $input_file $output_file
    exit 1



