#!/bin/csh -f
#/*+
#************************************************************************
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#*
#* (c) 1999.				(c) 1999.
#* National Research Council		Conseil national de recherches
#* Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
#* All rights reserved			Tous droits reserves
#* 					
#* NRC disclaims any warranties,	Le CNRC denie toute garantie
#* expressed, implied, or statu-	enoncee, implicite ou legale,
#* tory, of any kind with respect	de quelque nature que se soit,
#* to the software, including		concernant le logiciel, y com-
#* without limitation any war-		pris sans restriction toute
#* ranty of merchantability or		garantie de valeur marchande
#* fitness for a particular pur-	ou de pertinence pour un usage
#* pose.  NRC shall not be liable	particulier.  Le CNRC ne
#* in any event for any damages,	pourra en aucun cas etre tenu
#* whether direct or indirect,		responsable de tout dommage,
#* special or general, consequen-	direct ou indirect, particul-
#* tial or incidental, arising		ier ou general, accessoire ou
#* from the use of the software.	fortuit, resultant de l'utili-
#* 					sation du logiciel.
#*
#************************************************************************
#*
#*   Script Name:	dvd/scripts/dvdWrite
#*
#*   Purpose:
#*	To burn a DVD from a physical image on magnetice disk
#*
#*   Date		: Mar 9, 1999
#*
#*   SCCS data          : @(#)
#*      Module Name     : dvdWrite
#*      Version Number  : 1.4
#*      Release Number  : 1
#*      Last Updated    : 04/01/99
#*
#*   Programmer		: Shannon Jaeger
#*
#*   Modification History:
#*	99/03/09 SDJ	: Copied from cdWriteRunCdrecord-16
#*
#****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
#************************************************************************
#-*/

umask 002

set exec_name = $0
set exec_name = $exec_name:t


#
# Parse command line.
#


if ( $#argv != 8 ) then
   goto usage
endif


#
# Parse the arguments.
#

set volume_name = $1
set config_file_path = $2
set log_file_path = $3
set work_path = $4
set device_info = $5
set num_copies = $6
set num_files = $7  # note: this arg. is not used by this script.
set data_path = $8  # note: this arg. is not used by this script.


#
#  Go to the dvdrecord work path.
#
 
dvd $work_path
if ( $status ) then
    echo Error: Unable to change to directory \'$work_path\'
    sleep 10
    exit 1
endif


#
#  Remove any log files if present.
#
 
if ( -e $log_file_path ) then
    rm -f $log_file_path
    if ( $status ) then
	echo Error: Unable to remove log file \`$log_file_path\'
	sleep 10
        exit 1
    endif
endif

 
#
# Parse the device information to get the SCSI bus and target, the
# read speed, and write speed.
#

set dev_info=`echo $device_info | awk 'BEGIN { FS="," ; } { printf( "%d,%d,%d", $2, $3, $4 ); }'`
if ( $status ) then
    echo "Error: Unable to parse device information" >> $log_file_path
    exit 1
endif
set speed = `echo $device_info | awk 'BEGIN { FS="," ; } { print $6 }'`
if ( $status ) then
    echo "Error: Unable to parse device information" >> $log_file_path
    exit 1
endif
set driver = `echo $device_info | awk 'BEGIN { FS="," ; } { print $7 }'`
if ( $status ) then
    echo "Error: Unable to parse device information" >> $log_file_path
    exit 1
endif
if ( "$driver" != "none" ) then
    set command_line_args="dev=$dev_info speed=$speed timeout=60"
else
    set command_line_args="dev=$dev_info speed=$speed driver=$driver timeout=60"
endif
set noglob


#
# Verify the existence of the physical volume
#

if ( ! -e "$volume_name.vol" )  then
    echo "Error: Unable to find physical volume `$volume_name.vol`"
    exit 1
endif


#
#  Disable interrupts.
#
 
onintr -


#
#  Run dvd software
#  

echo "Starting ???: `date`" >> $log_file_path
set exit_status = 0
set num_verify = 0
set i = 0

while ( $i < $num_copies )
    #
    # Prompt user.
    #

    /usr/5bin/echo "\007"
    if ( $i > 0 ) then
        echo "Please remove copy number $i from the DVD recorder and insert a."
        echo "blank DVD into the recorder."
        echo -n "Press return when you are reading to record the next copy. "
        set input = $<
    else
        echo "Please put a blank DVD into the recorder"
        echo -n "and press return when you are reading to start recording "
        set input = $<
    endif


    #
    # Check the drive to make sure it is okay.
    #

    ???
    set exit_status = $status
    if ( $exit_status ) then
       echo "Error: There are problems with the DVD writer on device $dev_info"
       goto STATS
    endif


    #
    # Start burning the DVD
    #

    echo "***              Writing Copy $i               ***"


    #
    # Uncomment the next line when using cdrecord in no write mode and
    # comment out the one after it.
    #

    ???
    set exit_status = $status

    if ( $exit_status ) then
        echo " " >>$log_file_path
        echo "(dvdWrite) Error: Copy $i was NOT written." >>$log_file_path
    else
	echo " " >>$log_file_path
        echo "(dvdWrite) Success: Copy $i completed." >>$log_file_path

	#
	# Do verification - Not implemented.
	#

	echo "***             Verifying Copy $i              ***"
    
	@ num_verify += 1
    endif  
 

    echo "***              Copy $i Finished              ***"
    echo " " >>$log_file_path
    @ i += 1
end


#
#  Parse the log file and add to it the number of copies, number of 
#  of errors, number of files copied..
#

if ( -e $log_file_path ) then
    set num_copies = `grep '(dvdWrite) Success:' $log_file_path | wc -l`
    set num_errors = `grep '(dvdWrite) Error:' $log_file_path | wc -l`
    set num_verify_errors = `expr $num_copies - $num_verify`
    @ num_copies -= $num_verify_errors
else
    set num_copies = 0
    set num_errors = 0
    set num_verify = 0
endif


echo "$exec_name - Number of copies:           $num_copies" >> $log_file_path
echo "$exec_name - Number verified:            $num_verify" >> $log_file_path
echo "$exec_name - Number of errors:           $num_errors" >> $log_file_path
echo "$exec_name - Number of verify:    $num_verify_errors" >> $log_file_path


echo "$exec_name - Number of copies:    $num_copies" 
echo "$exec_name - Number verified:    $num_verify" 
echo "$exec_name - Number of errors:    $num_errors" 
echo "$exec_name - Number of verify errors:    $num_verify_errors"

 

echo "***                dvdWrite done                 ***"
sleep 2
if ( $exit_status ) then
   exit 1
else
   exit 0
endif


#
# Display usage Information.
#

usage:
    echo "USAGE: dvdWrite <volume_name> <config_file_path> <log_file_path> <work_path> <device_info> <num_copies> <num_files> <data_path>"
    echo ""	
    echo "              volume name:      Name of disk in upper-case"
    echo "              config_file:      Fully specified path and name of the"
    echo "                                configuration file."
    echo "              log_file_path:    Fully specified path and name of the"
    echo "                                log file."
    echo "              work_path:        Fully specified path to the work directory."
    echo "              device_info:      deviceName, SCSI Bus, Target, Logical Unit Number."
    echo "              num_copies:       Number of copies to make."
    echo "              num_files:        Number of files to put on the DVD."
    echo "              data_path:        Fully specified path to the directory which"
    echo "                                contains the data to be written."

 exit 1
