# Makefile

NAME = dhsQlToolDS9
SOURCES = configGen.tcl config.tcl dhsOcsWish.tcl dhsQltCtl.tcl dhsQlTool.tcl dhsQlTool-backend.tcl \
	help.tcl misc.tcl qltFrame.tcl utils.tcl pkgIndex.tcl

include ../conf/tcl.mk
