.\"/*+ $Id: dhsConsole.1,v 1.1.1.1 2002-11-24 20:26:09 brighton Exp $
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) 1997				(c) 1997
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-	ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME:
.\" dhsConsole/doc/dhsConsole.1
.\"
.\" PURPOSE:
.\" Describe the dhsConsole
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
.\"
.\"
.\" Revision 1.1.1.1  1999/08/23 19:58:13  cvs-tuc
.\" Initial install into CVS of dhs-0.16
.\"
.\" Revision 1.3  1998/08/05 06:10:42  jaeger
.\" Fixed grammatical and syntactical errors.  Also added more recent
.\" version of the configuration file.
.\"
.\" Revision 1.2  1998/05/25 22:25:32  jaeger
.\" Updated to reflect changes in the dhsConsole.
.\"
.\" Revision 1.1  1997/12/04 20:10:24  jaeger
.\" Initial revision
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.\"
.\" Ty macro to start an indent for each type def.
.de Ty
.ie n .TP 14n
.el .TP 16n
..
.\"
.\"
.\"**********************************************************************
.\"				End of Macros!!!
.\"**********************************************************************
.TH dhsConsole  1 28/07/98 "CADC"

.SH NAME
dhsConsole
\- User interface for DHS.

.SH SYNOPSIS
.B dhsConsole
[
.B -debug NONE | MIN | FULL ]
]
[
.B -epics
]
[
.B -help
]
[
.B -simulate NONE | FAST | VSM | FULL
]
[
.B -V
]

.SH DESCRIPTION
.B dhsConsole
is an 
.B OCSWish 
script.  It
has two main functions: manipulating of and displaying DHS status
information.  

.SH OPERATION
The
.B dhsConsole
will continuously monitor the status information provided by the
.B DHS Status server 
if it is not in simulate mode. Under normal operation the values
of the status records are obtained from the 
.B DHS Status Server,
via the DHS status acceptor in 
.B OCSWish.
If the
.B \-epics
command-line arguement is given the the status record values are
obtained from EPICS, via the EPICS status accpeptor in 
.B OCSWish.
The status records for the entire DHS is monitored,
which includes those for all of its subsystems.  
If any changes are made in this information it is changed on the Console.

Commands are requested by the 
.B dhsConsole
and are sent to the
.B DHS Command Server
for nearly all commands.  The only exception is
.I dhsGet
is used to obtain the primary FITS header of a dataset.
General DHS control commands
and sequence command requests can be issued on the entire DHS or for a 
single subsystem of DHS.  Other commands requested are made on the particular
subsystem they apply to. The actual commands that can be issued depends
on the subsystem.

For more information on the
.B dhsConsole's
operation see the
.B DHS User Manual.


.SH OPTIONS
.TP
.B -debug NONE | MIN | FULL 
Debug mode.  Depending on the mode set, it will print off various degrees of 
error messages.  
.TP
.B -epics
Epics mode.  Normally the 
.B dhsConsole 
gets all of the DHS status information
from the 
.B DHS Status Server.  
However, if the
.B -epics
flag is given then the 
.B dhsConsole
gets all of the status information from EPICS.
.TP
.B -help
Help.  Print help information and quit.
.TP
.B -simulate NONE | FAST | VSM | FULL
Simulate mode.  
If
.B NONE
or
.B FAST
are specified then the
.B dhsConsole
is 
.B not 
in simulate mode.
If
.B VSM
or
.B FULL
are specified then the
.B dhsConsole 
is in simulate mode.  When in simulate mode the status information is
not monitored but commands can be requested.
.TP
.B -V
Version.  Print version information and quit.
 


.SH FILES

.SS

.B CA_CONFIG
The
.I CA_CONFIG
file contains information on the EPICS values being monitored. This
file is required by 
.B OCSWish.  
Please see the 
.B OCSWish 
references for
more details. Also note that this file is needed only if the 
.B -epics
flag is given.

.B dhsConsole.config
.B dhsConsole
also requires a configuration file to set the subsystems and storage
resources that are to be monitored and manipulated.  The configuration
file also contains the version information and the identities of 
various DHS subsystem.  The
.B dhsConsole 
uses the
.B configGen.tcl 
widget for reading, writing and changing configuration
options.  See the 
.I configGen.tcl (n)
man page for more details.
.PP
The following is an example configuration file.
(Text followed by a '#' is treated as a comment and ignored by the
.B dhsConsole

.in -3
.sp
.nf

#
#  Application identification
#
# Keyword       application 
#
# -------       -----------
#
 
identity        dhsConsole


#
#  Version information
#
# Keyword       description    
#
# -------       ----------------
#
 
version        "dhsConsole 0.15 (c) 1998 NRC/CNRC"


#
# Command server identification information.
#
# Server        Server's IMP    Host
# Keyword       Identity        Address
# -------       ------------    -------
#
 
commandServer    commandServer      daxka


#
# Data Sserver identification information.
#
# Server        Server's IMP    Host
# Keyword       Identity        Address
# -------       ------------    -------
#
 
dataServer       dataServer      daxka


#
# Command server identification information.
#
# Server        Server's IMP    Host    Gemini Location        Gemini Site
# Keyword       Identity        Address    ("N"orth or
#                                           "S"outth)       ("S"ummit, "B"ase)
# -------       ------------    -------    ---------------  ------------------
#
 
statusRouter    statusServer      daxka         S                   S    



#
#  EPICS channel/Status Record information.
#
# keyword    system     channel name        alias          max
#
# -------    -------    ------------        -----          -----
#

channel        -        logMessage          dhsLog           -

channel        -        resourceArraySize   resNumRes        -
channel        -        resource%d:fullname res%dfullname    12
channel        -        resource%d:inUse    res%dinUse       12
channel        -        resource%d:max      res%dmax         12
channel        -        resource%d:name     res%dname        12
channel        -        resource%d:type     res%dtype        12
channel        -        resource%d:used     res%dused        12
channel        -        resource%d:units    res%dunits       12

channel        *        health              Health            -
channel        *        healthDesc          Desc              -
channel        *        state               State             -
channel        *        debug               Debug             -
channel        *        simulate            Sim               -

channel        -        health              dhsHealth         -
channel        -        healthDesc          dhsDesc           -
channel        -        state               dhsState          -
channel        -        debug               dhsDebug          -
channel        -        simulate            dhsSim            -

channel        DTS      numIncomplete        Inc              -


#
#  DHS subsystem information.
#
# keyword   subsystem
#
# -------   ---------
#
 
subsystem     STA
subsystem     QLS
subsystem     HIS
subsystem     DTS
subsystem     CMD
subsystem     STO


#
#  List of resources to be monitored.
#
# keyword  resource
#
# -------   ---------
#
 
resource    "Temp Store"
resource    "Perm Store"
resource    "daxka /tmp"
resource    "DHS DB"
resource    "History Store"

.fi

.SH ENVIRONMENT

Upon startup,
.B dhsConsole
looks for its configuration file in the directory specified by the
environment variable
.B DHSCONSOLE_CONFIG_DIR.
If this is not defined, it looks in the
.B DEFAULT_CONFIG_DIR.
Finally, if this is not defined it looks in the current directory.

.SH DIAGNOSTICS

Returns 0 upon successful completion, otherwise -1.

.SH SEE ALSO
.BR dhsCommand (1), 
and
.sp 0
.BR dhsStatus (1)


.SH DOCUMENTS
.B DHS User Manual,
.sp 0
.B ICD 3.2 - The DHS Command Interface,
.sp 0
.B OCSWish User's Manual, 
and 
.sp 0
.B OCSWish Technical Manual

.SH BUGS
If a command that disables a window is issued and the
.B dhsConsole 
never receives an "error" or
"idle" response from the
.B DHS Command Server
then the disabled window will never be enabled.


.SH AUTHORS
Shannon Jaeger

.br
National Research Council
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre



