# Makefile

NAME = dhs
SOURCES = av.c avList.c avListUtil.c bulkTransfer.c cadcMsg.c cmd.c cmdClient.c cmdServer.c connect.c connectClient.c crc.c dataset.c datasetClient.c datasetServer.c dhs.c dhsLocal.c dhsLocalServer.c eventLoop.c msg.c mutex.c systemEvent.c thread.c tsd.c userEvent.c vxpthread.c

include ../conf/cc_lib.mk
