static char rcsid[] = "$Id: msg.c,v 1.1.1.1 2002-11-24 20:20:38 brighton Exp $";
/*
 ************************************************************************
 ****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
 *
 * (c) 1997				(c) 1997
 * National Research Council		Conseil national de recherches
 * Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
 * All rights reserved			Tous droits reserves
 * 					
 * NRC disclaims any warranties,	Le CNRC denie toute garantie
 * expressed, implied, or statu-	enoncee, implicite ou legale,
 * tory, of any kind with respect	de quelque nature que se soit,
 * to the software, including		concernant le logiciel, y com-
 * without limitation any war-		pris sans restriction toute
 * ranty of merchantability or		garantie de valeur marchande
 * fitness for a particular pur-	ou de pertinence pour un usage
 * pose.  NRC shall not be liable	particulier.  Le CNRC ne
 * in any event for any damages,	pourra en aucun cas etre tenu
 * whether direct or indirect,		responsable de tout dommage,
 * special or general, consequen-	direct ou indirect, particul-
 * tial or incidental, arising		ier ou general, accessoire ou
 * from the use of the software.	fortuit, resultant de l'utili-
 * 					sation du logiciel.
 *
 ************************************************************************
 *
 * FILENAME
 * dhsLibrary/src/msg.c
 *
 * PURPOSE:
 * Contains routines to manage messages displayed for the DHS library.
 *
 * FUNCTION NAME(S)
 * dhsDebugLevel - Set the debugging level of the DHS library.
 * dhsErsHandler - Set up to catch errors from the DRAMA ERS system.
 * dhsMessage - Return the oldest message in the list of messages.
 * dhsMessageClear - Clear the oldest message in the list of messages.
 * dhsMsgCallback - Send all messages in the list to the error callback.
 * dhsMsgFmt - Format a message string.
 * dhsMsgInit - Initialize a tDhsMsg structure.
 * msgDebug - Handle a debug message.
 * msgNew - Get an unused tDhsMsg structure, re-using an existing one if
 *		possible.
 * msgDelete - Free the memory allocated to a tDhsMsg structure.
 * msgRegular - Copy a message onto the threads message queue.
 *
 *INDENT-OFF*
 * $Log: not supported by cvs2svn $
 * Revision 1.1.1.1  2002/02/21 20:23:33  tpaz
 *
 *
 * Revision 1.30  2001/03/27 20:29:30  nhill
 * Added several new messages.
 *
 * Revision 1.29  1998/06/28 22:18:05  nhill
 * Changed the handling of DHS_EL_INFO messages.
 *
 * Revision 1.28  1998/06/24 23:08:26  nhill
 * Changed the shutdown message to an information message.
 *
 * Revision 1.27  1998/05/27 16:28:40  nhill
 * fixed spelling in a message.
 *
 * Revision 1.26  1998/05/25 19:53:30  nhill
 * Added some missing messages.
 *
 * Revision 1.25  1998/05/11 16:32:08  nhill
 * Added a reconnect message.
 *
 * Revision 1.24  1998/01/20 18:22:57  nhill
 * Changed the error level of the DHS_S_SHUTDOWN message.
 *
 * Revision 1.23  1997/12/22 18:11:15  nhill
 * Added the DHS_S_SHUTDOWN message.
 *
 * Revision 1.22  1997/12/18 22:09:57  nhill
 * Added the DHS_E_CON_LOCKOUT message.
 *
 * Revision 1.21  1997/09/18 20:53:19  nhill
 * Added some new messages.
 *
 * Revision 1.20  1997/09/17 20:36:20  nhill
 * Added some new messages.
 *
 * Revision 1.19  1997/08/28 19:20:48  nhill
 * Cleaned up the documentation.
 *
 * Revision 1.18  1997/08/27 23:00:41  nhill
 * Fixed an uninitialized memory read.
 *
 * Revision 1.17  1997/08/27 22:03:25  nhill
 * Fixed the display of error messages before the thread specific data is
 * initialized.
 *
 * Revision 1.16  1997/08/25 23:10:32  nhill
 * Removed the call to dhsMsgCallback from the ERS error handler. This
 * allows messages not generated by the event loop to be returned in a more
 * conventional manner.
 *
 * Revision 1.15  1997/08/06 16:17:07  nhill
 * Added an ers error handler.
 *
 * Revision 1.14  1997/07/29 22:16:24  nhill
 * Added messages for DHS_E_DISCONNECT and DHS_E_NOT_AVLIST.
 *
 * Revision 1.13  1997/07/24 21:28:10  nhill
 * now makes a copy of the mesage string and clears the message
 * before executing the error callback.
 *
 * Revision 1.12  1997/04/15 19:51:08  nhill
 * Added some new messages.
 *
 * Revision 1.11  1997/02/24 19:17:17  nhill
 * Checkin for install.
 *
 * Revision 1.10  1997/02/17 20:14:32  nhill
 * Added new messages.
 *
 * Revision 1.9  1997/02/04 19:41:34  nhill
 * Checkpoint for install.
 *
 * Revision 1.8  1997/01/30 17:18:54  nhill
 * Checkin for install.
 *
 * Revision 1.7  1997/01/29 18:18:23  nhill
 * Checkin for install.
 *
 * Revision 1.6  1997/01/27 22:35:03  nhill
 * Checkin before install.
 *
 * Revision 1.5  1997/01/22 21:34:52  nhill
 * stable checkin.
 *
 * Revision 1.4  1997/01/20 17:15:11  nhill
 * Checkpoint.
 *
 * Revision 1.3  1997/01/15 20:05:35  nhill
 * Stable develop version.
 *
 * Revision 1.2  1997/01/13 17:58:34  nhill
 * Reasonably stable checkpoint.
 *
 *INDENT-ON*
 *
 ****  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
 ************************************************************************
*/

#include <stdlib.h>


#include "localDhs.h"
#include "cadcMsg.h"
#include "gen_str.h"

static MSG	msgs[] = {
    {	DHS_S_CMD_BULK_SENT, DHS_EL_DEBUG,
	"Message tag %08x type %d sent as bulk data." },
    {	DHS_S_CMD_DELETE, DHS_EL_DEBUG,
	"Deleting command with tag: %08x" },
    {	DHS_S_CMD_MSG_SENT, DHS_EL_DEBUG,
	"Message tag %08x type %d sent as regular message." },
    {	DHS_S_CMD_NEW, DHS_EL_DEBUG,
	"Creating command with tag: %08x" },
    {	DHS_S_CONNECT, DHS_EL_ERROR,
	"Connection request from %s on %x: con: %d" },
    {	DHS_S_DISCONNECT, DHS_EL_ERROR,
	"Disconnect request from %s on %x: con: %d" },
    {	DHS_S_FN_ENTRY, DHS_EL_DEBUG,
	"Entering function `%s'." },
    {	DHS_S_FN_EXIT, DHS_EL_DEBUG,
	"Exiting function `%s'." },
    {	DHS_S_IMP_EVENT, DHS_EL_DEBUG,
	"Imp event type %d" },
    {	DHS_S_MUTEX_LOCK, DHS_EL_DEBUG,
	"Locking mutex '%s' %08x" },
    {	DHS_S_MUTEX_UNLOCK, DHS_EL_DEBUG,
	"Unlocking mutex '%s' %08x" },
    {	DHS_S_RECONNECT, DHS_EL_INFO,
	"Connection to `%s' on system `%s' automatically re-connected." },
    {	DHS_S_SHUTDOWN, DHS_EL_INFO,
	"Server %s on %s is shutting down." },
    {	DHS_S_SYS_EVENT, DHS_EL_DEBUG,
	"System message %d. Tag: %08x." },
    {	DHS_S_USER_EVENT, DHS_EL_DEBUG,
	"User message %d, Tag: %08x." },
    {	DHS_E_AVEDIT_DIMS, DHS_EL_ERROR,
	"Array attributes cannot be edited." },
    {	DHS_E_AVEDIT_INFO, DHS_EL_ERROR,
	"Error reading attribute editing information from SDS Extra data area." },
    {	DHS_E_AVEDIT_TYPE, DHS_EL_ERROR,
	"Data type of new data does not match original data type or \n"
	"unsupported type for editing." },
    {	DHS_E_AVLIST_ARRAY, DHS_EL_ERROR,
	"Attempt to add an array of avlists to an av list." },
    {	DHS_E_BT_FIND, DHS_EL_SEVERE,
	"Invalid search type in function dhsBtFind: %d." },
    {	DHS_E_BT_NOT_FOUND, DHS_EL_SEVERE,
    	"Could not find bulk transfer structure for tag %d." },
    {	DHS_E_CB_NULL, DHS_EL_ERROR,
    	"Required %s callback function is NULL." },
    {	DHS_E_CB_TYPE, DHS_EL_ERROR,
	"Unkown callback function type: %d." },
    {	DHS_E_CMD_DELETED, DHS_EL_ERROR,
	"Attempt to reference tag %08x scheduled to be deleted." },
    {	DHS_E_CMD_LOST, DHS_EL_ERROR,
	"Connection was lost for command." },
    {	DHS_E_CMD_FIND, DHS_EL_SEVERE,
	"Invalid find type in call to dhsCmdFind: %d." },
    {	DHS_E_CMD_NOT_FOUND, DHS_EL_ERROR,
	"Failed to find a command with tag: %08x." },
    {	DHS_E_CON_FIND, DHS_EL_ERROR,
	"Invalid connection search type: %d." },
    {	DHS_E_CON_INVALID, DHS_EL_ERROR,
	"Attempt to send a message to an invalid connection: %d." },
    {	DHS_E_CON_LOCKOUT, DHS_EL_ERROR,
	"Connection from `%s' on system `%s' refused because\n"
	"connections are locked out." },
    {	DHS_E_CON_LOST, DHS_EL_ERROR,
	"Connection lost to `%s' on system `%s'." },
    {	DHS_E_CON_NOT_FOUND, DHS_EL_ERROR, 
	"Connection not found." },
    {	DHS_E_COND, DHS_EL_SEVERE,
	"Error accessing condition variable. Return status was: %d." },
    {	DHS_E_CONNECT, DHS_EL_ERROR,
	"Failed to establish connection to %s on %s." },
    {	DHS_E_CONNECT_REPLY, DHS_EL_ERROR,
	"Unexpected connect reply message from machine %08x task pid %d.\n"
	"This is usually due to incorrect IMP configuration machines with\n"
	"multiple network cards.\n"
	"All incomplete connections will be marked as error state, since I\n"
	"can't identify the actual connection" },
    {	DHS_E_CTL_CMD, DHS_EL_ERROR,
	"CTL command to a server failed.\n%s" },
    {	DHS_E_DISCONNECT, DHS_EL_ERROR,
	"Invalid disconnect message received from %s on %x: con: %d" },
    {	DHS_E_ERS, DHS_EL_ERROR,
	"Error calling DRAMA ERS function. Function return code: %x." },
    {	DHS_E_ERS_MSG, DHS_EL_ERROR,
	"ERS reported message: code %x\n%s" },
    {	DHS_E_IMP, DHS_EL_SEVERE,
	"Failure in an IMP routine:\n %s.\n"
	"Error number is %x\n"
	"Error text is: %s" },
    {	DHS_E_IMP_CONNECT, DHS_EL_ERROR,
	"An IMP connection failed. The IMP error status was %x:\n%s." },
    {	DHS_E_IMP_MSG, DHS_EL_ERROR,
    	"An invaid %s imp message was received." },
    {	DHS_E_IMP_REGISTER, DHS_EL_SEVERE,
	"Failed to register task `%s' with the IMP system." },
    {	DHS_E_IMP_SYS_MSG, DHS_EL_ERROR,
	"Unkown IMP system message: %d" },
    {	DHS_E_IMP_USER_MSG, DHS_EL_ERROR,
	"Unkown IMP user message: %d" },
    {	DHS_E_LOCATE, DHS_EL_ERROR,
	"An IMP locate failed. The IMP error status was %x." },
    {	DHS_E_LOCATE_MSG, DHS_EL_ERROR,
	"IMP locate message received for a connection that wasn't waiting for it." },
    {	DHS_E_LOOP_TYPE, DHS_EL_SEVERE,
	"Invalid event loop type: %d." },
    {	DHS_E_MEMORY, DHS_EL_SEVERE, 
	"Memory allocation failure" },
    {	DHS_E_MSG_LENGTH, DHS_EL_ERROR,
	"Message received with length %d when %s was expected." },
    {	DHS_E_MSG_SENDER, DHS_EL_ERROR,
	"User message type %d received without an identifyable sender connection." },
    {	DHS_E_MUTEX, DHS_EL_SEVERE,
	"Error %d occured while manipulating a mutex." },
    {	DHS_E_NO_ATTRIB, DHS_EL_ERROR,
	"Attribute `%s' not found." },
    {	DHS_E_NOT_AVLIST, DHS_EL_ERROR,
	"Object '%d' is not an attribute value list." },
    {	DHS_E_NULLVALUE, DHS_EL_ERROR,
	"An attribute had a NULL value where a NULL value is not permitted." },
    {	DHS_E_SDS, DHS_EL_SEVERE,
	"Failure in SDS routine %s.\n"
	"Error number is %x" },
    {	DHS_E_TASK_UNKNOWN, DHS_EL_ERROR,
	"Task %s is not known." },
    {	DHS_E_THREAD_CREATE, DHS_EL_SEVERE,
	"Could not create a thread. pThread_create return status is %d." },
    {	DHS_E_TSD, DHS_EL_SEVERE,
	"Failed to get thread specific data pointer." },
    {	DHS_E_TYPE, DHS_EL_ERROR,
	"Unkown attribute type: %d" }
};

static int	numMsgs = sizeof( msgs ) / sizeof( MSG );
static DHS_DEBUG_LEVEL	
		debugLevel = DHS_DEBUG_OFF;

static void	msgRegular( char *, MSG * );
static void	msgDebug( char *, MSG * );
static void	msgDelete( tDhsMsg * );
static tDhsMsg	*msgNew( tDhsTsd * );

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * dhsDebugLevel
 *
 * INVOCATION:
 * oldLevel = dhsDebugLevel( newLevel, &status );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (>) level (DHS_DEBUG_LEVEL) The new debug level.
 * (!) pStatus (DHS_STATUS *) Function return status.
 *
 * FUNCTION VALUE:
 * (DHS_DEBUG_LEVEL) The old debug level.
 *
 * PURPOSE:
 * Set the current debug level of the library
 *
 * DESCRIPTION:
 * Set the debug level variable.
 *
 * EXTERNAL VARIABLES:
 * debugLevel - Stores the DHS library debug level.
 *
 * PRIOR REQUIREMENTS:
 * None.
 *
 * DEFICIENCIES:
 * None.
 *-
 ************************************************************************
 */

DHS_DEBUG_LEVEL	dhsDebugLevel
(
    DHS_DEBUG_LEVEL
    		level,		/* (in)  The new dhs debug level.	*/
    DHS_STATUS	*pStatus	/* (in)  Function return status.	*/
)
{
    DHS_DEBUG_LEVEL
    		oldLevel;


    fnEntry( "dhsDebugLevel" );
    statCheck( *pStatus, DHS_DEBUG_OFF );
    isInit( *pStatus, DHS_DEBUG_OFF );


    oldLevel = debugLevel;
    debugLevel = level;

    fnReturn( oldLevel );
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * dhsErsHandler
 *
 * INVOCATION:
 * n.a. Called automatically by the DRAMA ERS system.
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (>) userData (void *) User data pointer passed to ErsStart.
 * (>) count (unsigned int) Number of messages to be output.
 * (>) messages (const ErsMessageType []) An array of messages to display.
 * (!) pErsStatus (StatusType) Ers inherited function status.
 *
 * FUNCTION VALUE:
 * None.
 *
 * PURPOSE:
 * Called by the DRAMA ERS system to display an error message
 *
 * DESCRIPTION:
 * Use the DHS library error callback routine to display the messages.
 *
 * EXTERNAL VARIABLES:
 * None.
 *
 * PRIOR REQUIREMENTS:
 * None.
 *
 * DEFICIENCIES:
 * None.
 *-
 ************************************************************************
 */

void		dhsErsHandler
(
    void	*userData,	/* (in)  User data pointer passed to 	*/
    				/*	 ErsStart.			*/
    unsigned int		/* (in)  Number of messages to be output.*/
    		count,
    const ErsMessageType	/* (in)  An array of messages to display.*/
		messages[],
    StatusType	*pErsStatus	/* (mod) Ers inherited function status.	*/
)
{
    int		i;


    if ( *pErsStatus != STATUS__OK )
    {
	return;
    }

    for ( i = 0; i < count; i++ )
    {
	dhsMsgFmt( DHS_E_ERS_MSG, DHS_DEBUG_OFF, messages[i].mesStatus, 
		messages[i].message );
    }
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * dhsMessage
 *
 * INVOCATION:
 * msg = dhsMesasge( &errorNum, &errorLev, &status );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (<) errorNum (DHS_STATUS *) The status associated with the messages.
 * (<) errorLev (DHS_ERR_LEVEL *) The error level associated with the messages.
 * (!) pStatus (DHS_STATUS *) Function return status.
 *
 * FUNCTION VALUE:
 * (char *) The error message.
 *
 * PURPOSE:
 * Return the oldest message in the list of messages for this thread
 *
 * DESCRIPTION:
 * - If there is a message in the buffer shared by all threads, return
 *   the information about the shared message.
 * - If there are messages in the thread specific message buffer, return
 *   the oldest message in the list.
 * Note that this routine does not use the fnEntry and fnReturn macros.
 * this is necessary to avoid recursive calls to this function.
 *
 * EXTERNAL VARIABLES:
 * None.
 *
 * PRIOR REQUIREMENTS:
 * None.
 *
 * DEFICIENCIES:
 * None.
 *-
 ************************************************************************
 */

char		*dhsMessage
(
    DHS_STATUS	*errorNum,	/* (out) The error.			*/
    DHS_ERR_LEVEL
    		*errorLev,	/* (out) The error level.		*/
    DHS_STATUS	*pStatus	/* (out) Function return status.	*/
)
{
    char	*string;	/* Message string to return.		*/
    tDhsTsd	*tsd;		/* Thread specific data pointer.	*/
    tDhsMsg	*pDhsMsg;	/* Pointer to message structure.	*/


    statCheck( *pStatus, NULL );


    /*
     *  Make sure the local data structure has been initialized.
     */

    if ( ! dhsLocalIsInit )
    {
	*pStatus = DHS_E_INIT;
	return( NULL );
    }


    /*
     *  Figure out which message structure to use.
     */

    if ( dhsLocal.dlMsg.dmFree )
    {
	/*
	 *  The shared message buffer is empty, look for one in the thread
	 *  specific message buffer.
	 */

	/*
	 *  Get the thread specific data structure.
	 */

	tsd = dhsTsdGet( pStatus );
	if ( *pStatus != DHS_S_SUCCESS )
	{
	    /*
	     *  An error occured while trying to get the thread specific data.
	     */

	    pDhsMsg = NULL;
	} 
	else if ( ! tsd->dtMsg.dmFree )
	{
	    /*
	     *  The message buffer in the thread specific data structure
	     *  is in use, so return that message.
	     */

	    pDhsMsg = &( tsd->dtMsg );
	}
	else if ( tsd->dtMsg.dmFree && tsd->dtMsg.dmNext != NULL )
	{
	    /*
	     *  The message buffer in the tsd structure is not in use, so
	     *  follow the link to the next message buffer.
	     */

	    pDhsMsg = tsd->dtMsg.dmNext;
	}
	else
	{
	    /*
	     *  No message buffer is found, so there is no message to return.
	     */

	    *pStatus = DHS_S_NO_MESSAGE;
	    pDhsMsg = NULL;
	}
    }
    else
    {
	/*
	 *  The shared message buffer is in use, so return that message.
	 */

	pDhsMsg = &( dhsLocal.dlMsg );
    }


    if ( pDhsMsg == NULL )
    {
	/*
	 *  No message was found so return a NULL pointer.
	 */

	string = NULL;
    }
    else
    {
	/*
	 *  A message was found so return the information about the message.
	 */

	string = pDhsMsg->dmMsg;
	if ( errorNum != NULL )
	{
	    *errorNum = pDhsMsg->dmStatus;
	}
	if ( errorLev != NULL )
	{
	    *errorLev = pDhsMsg->dmLevel;
	}
    }


    return( string );
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * dhsMessageClear
 *
 * INVOCATION:
 * dhsMessageClear( &status );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (!) pStatus (DHS_STATUS *) Descripton of the parameter
 *
 * FUNCTION VALUE:
 * None.
 *
 * PURPOSE:
 * Delete the oldest message in the list of messages
 *
 * DESCRIPTION:
 * - If the message buffer shared by all threads is in use, clear it.
 * - If the shared message buffer is not in use, try to clear the oldest
 *   message in the thread specific messages.
 * Note that this routine does not use the fnEntry and fnReturn macros.
 * this is necessary to avoid recursive calls to this function.
 *
 * EXTERNAL VARIABLES:
 * None.
 *
 * PRIOR REQUIREMENTS:
 * None.
 *
 * DEFICIENCIES:
 * It is possible for the shared message buffer to become used after a
 * thread specific message is displayed, and before the dhsMessageClear
 * function is called with the intention of clearing the message just
 * displayed. If this were to happen, the shared message would never be
 * displayed. Since the shared message buffer is only for emergency use,
 * i.e. when the thread specific data cannot be accessed, this shouldn't
 * be a problem. 
 * 
 *-
 ************************************************************************
 */

void		dhsMessageClear
(
    DHS_STATUS	*pStatus	/* (out) The function status.		*/
)
{
    tDhsMsg	*delete;	/* Message to be deleted.		*/
    tDhsTsd	*tsd;		/* Thread specific data pointer.	*/


    statCheck( *pStatus, VOID );
    isInit( *pStatus, VOID );


    /*
     *  Check to see if the shared message buffer is in use.
     */

    if ( dhsLocal.dlMsg.dmFree )
    {
	/*
	 *  There is no message in the shared buffer, so check the thread
	 *  specific message buffers.
	 */

	tsd = dhsTsdGet( pStatus );
	if ( *pStatus == DHS_S_SUCCESS )
	{
	    /*
	     *  Check to see if the first message buffer is in use.
	     */

	    if ( tsd->dtMsg.dmFree )
	    {
		/*
		 *  The first message buffer is not in use, so see if there
		 *  is one in the linked list of buffers.
		 */

		if ( tsd->dtMsg.dmNext != NULL )
		{
		    /*
		     *  There is a message buffer in the linked list, so
		     *  remove the buffer from the linked list.
		     */

		    delete = tsd->dtMsg.dmNext;
		    tsd->dtMsg.dmNext = delete->dmNext;
		    if ( tsd->dtMsgLast == delete )
		    {
			tsd->dtMsgLast = &( tsd->dtMsg );
		    }
		    msgDelete( delete );
		}
		else
		{
		    /*
		     *  There is no message to free.
		     */

		    *pStatus = DHS_S_NO_MESSAGE;
		}
	    }
	    else
	    {
		/*
		 *  The first message buffer is in use, so mark it as free.
		 */

		tsd->dtMsg.dmFree = TRUE;
	    }
	}
    }
    else
    {
	/*
	 *  The shared message buffer is in use, so mark it as free.
	 */

	dhsLocal.dlMsg.dmFree = TRUE;
    }
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * dhsMsgCallback
 *
 * INVOCATION:
 * dhsMsgCallback( connect, tag );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (>) connect (DHS_CONNECT) The connection associated with the messages.
 * (>) tag (DHS_TAG) The DHS_TAG associated with the messages.
 *
 * FUNCTION VALUE:
 * None.
 *
 * PURPOSE:
 * Send all messages currently stored for the thread to the error callback
 *
 * The connection and tag passed in the arguments are passed to the callback
 * as the associated connection and tag. If there is no appropriate connection
 * or tag, DHS_CONNECT_NULL and/or DHS_TAG_NULL can be passed instead.
 *
 * DESCRIPTION:
 * Loop through all available messages and execute the error callback for each.
 *
 * EXTERNAL VARIABLES:
 * None.
 *
 * PRIOR REQUIREMENTS:
 * None.
 *
 * DEFICIENCIES:
 * If there is more than one message to process, and if the error callback
 * does something that generates messages, then the order in which the
 * messages are displayed may not be as desired.
 *-
 ************************************************************************
 */

void		dhsMsgCallback
(
    DHS_CONNECT	connect,	/* (in)  Appropriate connection.	*/
    DHS_TAG 	tag		/* (in)  Appropriate command.		*/
)
{
    DHS_ERR_LEVEL		/* Error level of the error.		*/
    		errorLev;
    DHS_STATUS	errorNum;	/* Number of the error printed.		*/
    char	*msg;		/* The Error message.			*/
    DHS_STATUS	status;		/* Function return status.		*/
    char	tmpMsg[ MSG_MAX_LEN];


    /*
     *  Make sure the error callback has been initialized.
     */

    if ( dhsLocal.dlCBFError != NULL )
    {
	/*
	 *  Process all messages stored for this thread.
	 */

	status = DHS_S_SUCCESS;
	for ( ;; )
	{
	    /*
	     *  Get the information about the message.
	     */

	    msg = dhsMessage( &errorNum, &errorLev, &status );
	    if ( status == DHS_S_SUCCESS )
	    {
		/*
		 *  Make a copy of the message so it can be cleared before
		 *  the error callback is called. This should help to keep
		 *  any messages generated by the error callback in some
		 *  kind of order.
		 */

		(void) strcpy( tmpMsg, msg );
		dhsMessageClear( &status );
		dhsLocal.dlCBFError( connect, errorNum, errorLev, tmpMsg, 
			tag, NULL );
	    }
	    else
	    {
		break;
	    }
	}
    }
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * dhsMsgFmt
 *
 * INVOCATION:
 * dhsMsgFormat( DHS_E_IMP, DHS_DEBUG_FULL, args );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (>) errStatus (DHS_STATUS) The message number to display.
 * (>) level (DHS_DEBUG_LEVEL) The minimum debug level at which to display
 *				the message.
 * (>) ... (?) Optional arguments to be formatted into the message.
 *
 * FUNCTION VALUE:
 * None.
 *
 * PURPOSE:
 * Format a message into a DHS library message buffer
 *
 * DESCRIPTION:
 * - Find the mesage format string.
 * - Format the string.
 *
 * EXTERNAL VARIABLES:
 * None.
 *
 * PRIOR REQUIREMENTS:
 * None.
 *
 * DEFICIENCIES:
 * None.
 *-
 ************************************************************************
 */

void	dhsMsgFmt
(
    DHS_STATUS	errStatus,	/* Message to print.			*/
    DHS_DEBUG_LEVEL
    		level,		/* Minimum debug level for the message.	*/
    ...
)
{
    va_list	args;		/* The optional arguments.		*/
    MSG		*msg;		/* The message structure.		*/
    char	msgString[MSG_MAX_LEN];	
				/* The error message.			*/


    if ( ! dhsLocalIsInit || debugLevel < level )
    {
	return;
    }


    /*
     *  Format the message string.
     */

    msgString[0] = '\0';
    va_start( args, level );
    dhs_msg_format( msgString, "dhs", numMsgs, msgs, errStatus, args );
    va_end( args );


    /*
     *  Find the message structure describing the message.
     */

    msg = dhs_msg_find( errStatus, msgs, numMsgs );

    if ( msg != NULL )
    {
	/*
	 *  Debugging messages are handled differently than error messages.
	 */

	if ( msg->m_severity == DHS_EL_DEBUG )
	{
	    msgDebug( msgString, msg );
	}
	else
	{
	    msgRegular( msgString, msg );
	}
    }
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * dhsMsgInit
 *
 * INVOCATION:
 * dhsMsgInit( &dhsMsg );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (>) pDhsMsg (tDhsMsg *) Message structure to initialize.
 *
 * FUNCTION VALUE:
 * None.
 *
 * PURPOSE:
 * Initialize a tDhsMsg structure.
 *
 * DESCRIPTION:
 * Set all members to initial values.
 *
 * EXTERNAL VARIABLES:
 * None.
 *
 * PRIOR REQUIREMENTS:
 * None.
 *
 * DEFICIENCIES:
 * None.
 *-
 ************************************************************************
 */

void		dhsMsgInit
(
    tDhsMsg	*pDhsMsg	/* (in)  Message structure to init.	*/
)
{
    pDhsMsg->dmStatus = DHS_S_SUCCESS;
    pDhsMsg->dmLevel = DHS_EL_SEVERE;
    pDhsMsg->dmNext = NULL;
    pDhsMsg->dmFree = TRUE;
    pDhsMsg->dmMsg = NULL;
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * msgDebug
 *
 * INVOCATION:
 * msgDebug( msgString, msg );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (>) msgString (char *) The message string.
 * (>) pMsg (MSG *) The message structure.
 *
 * FUNCTION VALUE:
 * None.
 *
 * PURPOSE:
 * Call the error callback function so the application can deal with
 * the message
 *
 * DESCRIPTION:
 * Trivial.
 *
 * EXTERNAL VARIABLES:
 * None.
 *
 * PRIOR REQUIREMENTS:
 * None.
 *
 * DEFICIENCIES:
 * None.
 *-
 ************************************************************************
 */

static void	msgDebug
(
    char	*msgString,	/* (in)  The string for the message.	*/
    MSG		*msg		/* (in)  The message structure.		*/
)
{
    if ( dhsLocal.dlCBFError != NULL )
    {
	dhsLocal.dlCBFError( DHS_CONNECT_NULL, msg->m_status, 
		msg->m_severity, msgString, DHS_TAG_NULL, NULL );
    }
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * msgNew
 *
 * INVOCATION:
 * pDhsMsg = msgNew( pDhsTsd );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (>) pDhsTsd (tDhsTsd *) Pointer to the thread specific data structure.
 *
 * FUNCTION VALUE:
 * (tDhsMsg *) Pointer to a tDhsMsg structure.
 *
 * PURPOSE:
 * Get a new tDhsmsg structure, re-using an old one if possible.
 *
 * DESCRIPTION:
 * If the first message structure which is stored as part of the thread
 * specific data is free, return a pointer to that, otherwise allocate
 * a new structure and add it to the end of the linked list.
 *
 * EXTERNAL VARIABLES:
 * None.
 *
 * PRIOR REQUIREMENTS:
 * Operations that must be performed before calling this function.
 *
 * DEFICIENCIES:
 * None.
 *-
 ************************************************************************
 */

static tDhsMsg	*msgNew
(
    tDhsTsd	*pDhsTsd	/* (in)  Thread specific data structure.*/
)
{
    tDhsMsg	*pDhsMsg;	/* Pointer to the message to return.	*/


    if ( pDhsTsd->dtMsg.dmFree && pDhsTsd->dtMsg.dmNext == NULL )
    {
	pDhsMsg = &( pDhsTsd->dtMsg );
    }
    else
    {
	pDhsMsg = malloc( sizeof( tDhsMsg ) );
	dhsMsgInit( pDhsMsg );
	pDhsTsd->dtMsgLast->dmNext = pDhsMsg;
	pDhsTsd->dtMsgLast = pDhsMsg;
    }

    return( pDhsMsg );
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * msgDelete
 *
 * INVOCATION:
 * msgDelete( pDhsMsg );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (>) pDhsMsg (tDhsMsg) The message to delete.
 *
 * FUNCTION VALUE:
 * None.
 *
 * PURPOSE:
 * Free the memory allocated to a tDhsMsg structure
 *
 * DESCRIPTION:
 * Free the message memory and the structure memory.
 *
 * EXTERNAL VARIABLES:
 * None.
 *
 * PRIOR REQUIREMENTS:
 * The message should have been allocated with msgNew.
 *
 * DEFICIENCIES:
 * None.
 *-
 ************************************************************************
 */

static void	msgDelete
(
    tDhsMsg	*pDhsMsg	/* (in)  The message to delete.		*/
)
{
    if ( pDhsMsg != NULL )
    {
	if ( pDhsMsg->dmMsg != NULL )
	{
	    free( pDhsMsg->dmMsg );
	}

	free( pDhsMsg );
    }
}

/*
 ************************************************************************
 *+
 * FUNCTION NAME:
 * msgRegular
 *
 * INVOCATION:
 * msgRegular( msgString, msg );
 *
 * PARAMETERS: (">" input, "!" modified, "<" output)
 * (>) msgString (char *) The message string.
 * (>) pMsg (MSG *) The message structure.
 *
 * FUNCTION VALUE:
 * None.
 *
 * PURPOSE:
 * Copy a message onto the threads message queue
 *
 * DESCRIPTION:
 * Get a new tDhsMsg struture on the message queue, and then copy the
 * message to the queue.
 *
 * EXTERNAL VARIABLES:
 *
 * PRIOR REQUIREMENTS:
 * None.
 *
 * DEFICIENCIES:
 * None.
 *-
 ************************************************************************
 */

static void	msgRegular
(
    char	*msgString,	/* (in)  The string for the message.	*/
    MSG		*msg		/* (in)  The message structure.		*/
)
{
    tDhsMsg	*pDhsMsg;	/* Pointer to a tDhsMsg structure.	*/
    tDhsTsd	*pDhsTsd;	/* Pointer to thread specific data.	*/
    DHS_STATUS	status;		/* Function status return value.	*/


    /*
     *  Get the thread specific data.
     */

    if ( msg->m_status != DHS_E_TSD )
    {
	status = DHS_S_SUCCESS;
	pDhsTsd = dhsTsdGet( &status );
    }


    /*
     *  Check for errors accessing the thread specific data. It is also
     *  possible this routine could be called recursivly when an error
     *  occurs accessing the thread specific data, in which case the
     *  routine makes no attempt to access the thread specific data again.
     */

    if ( status == DHS_S_SUCCESS && pDhsTsd != NULL && 
	    msg->m_status != DHS_E_TSD )
    {
	/*
	 *  Get a new message structure.
	 */

	pDhsMsg = msgNew( pDhsTsd );
	if ( pDhsMsg == NULL )
	{
	    /*
	     *  Could not allocate memory, so put a message in the shared
	     *  message buffer.
	     */

	    (void) strcpy( dhsLocal.dlMsgString,
		    "Memory allocation failure in message routines" );
	    dhsLocal.dlMsg.dmFree = FALSE;
	}


	/*
	 *  The first message in the thread specific data structure, and
	 *  the shared message buffer have fixed size, statically allocated
	 *  message string buffers associated with them. Everything else
	 *  requires the message be stored on the heap.
	 */

	if ( pDhsMsg != &( pDhsTsd->dtMsg ) && pDhsMsg != &( dhsLocal.dlMsg ) )
	{
	    /*
	     *  If there is already a message string associated with the 
	     *  message, free it.
	     */

	    if ( pDhsMsg->dmMsg != NULL )
	    {
		free( pDhsMsg->dmMsg );
	    }


	    /*
	     *  Store the new message in the heap and set the message
	     *  pointer.
	     */

	    if ( ( pDhsMsg->dmMsg = strsav( msgString )  ) == NULL )
	    {
		(void) strcpy( dhsLocal.dlMsgString, 
			"Memory allocation failure in message routines" );
		dhsLocal.dlMsg.dmFree = FALSE;
	    }
	    pDhsMsg->dmFree = FALSE;
	}
	else
	{
	    /*
	     *  This is one of the staticaly allocated buffers, so copy
	     *  the new message into the messages buffer.
	     */

	    (void) strcpy( pDhsMsg->dmMsg, msgString );
	    pDhsMsg->dmFree = FALSE;
	}
    }
    else
    {
	/*
	 *  An error occured trying to access the thread specific data,
	 *  so display an error message using the shared message buffer.
	 */

	dhs_msg_append( dhsLocal.dlMsgString, msgString );
	dhsLocal.dlMsg.dmFree = FALSE;
    }


    /*
     * Set the message number and severity.
     */

    pDhsMsg->dmStatus = msg->m_status;
    pDhsMsg->dmLevel = msg->m_severity;
}
