.\"/*+
.\"***********************************************************************
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"
.\" (c) <year>				(c) <year>
.\" National Research Council		Conseil national de recherches
.\" Ottawa, Canada, K1A 0R6 		Ottawa, Canada, K1A 0R6
.\" All rights reserved			Tous droits reserves
.\" 					
.\" NRC disclaims any warranties,	Le CNRC denie toute garantie
.\" expressed, implied, or statu-	enoncee, implicite ou legale,
.\" tory, of any kind with respect	de quelque nature que se soit,
.\" to the software, including		concernant le logiciel, y com-
.\" without limitation any war-		pris sans restriction toute
.\" ranty of merchantability or		garantie de valeur marchande
.\" fitness for a particular pur-	ou de pertinence pour un usage
.\" pose.  NRC shall not be liable	particulier.  Le CNRC ne
.\" in any event for any damages,	pourra en aucun cas etre tenu
.\" whether direct or indirect,		responsable de tout dommage,
.\" special or general, consequen-	direct ou indirect, particul-
.\" tial or incidental, arising		ier ou general, accessoire ou
.\" from the use of the software.	fortuit, resultant de l'utili-
.\" 					sation du logiciel.
.\"
.\"***********************************************************************
.\"
.\" FILENAME
.\" fh.3
.\"
.\" PURPOSE:
.\" Describe the fits header library.
.\"
.\"
.\"INDENT-OFF*
.\" $Log: not supported by cvs2svn $
.\" Revision 1.1.1.1  2002/02/21 20:23:34  tpaz
.\"
.\"
.\" Revision 1.1.1.1  1999/08/23 19:58:06  cvs-tuc
.\" Initial install into CVS of dhs-0.16
.\"
.\" Revision 1.2  1999/01/25 23:14:11  dunn
.\" Updated
.\"
.\" Revision 1.1  1997/10/29 21:48:18  jaeger
.\" Initial revision
.\"
.\"INDENT-ON*
.\"
.\"***  C A N A D I A N   A S T R O N O M Y   D A T A   C E N T R E  *****
.\"***********************************************************************
.\"-*/
.\"
.                       \" Ty macro to start an indent for each type def.
.de Ty
.ie n .TP 14n
.el .TP 16n
..
./"
.TH fh 3 29/10/97 "CADC"


.SH NAME

.B fh, checkFitsTable, close, config, init, parseHeader
\- Fits header access routines.


.SH SYNOPSIS
.LP
.nf
#include "gen_types.h"		
#include "gen_eptr.h"
#include "gen_config.h"
#include "gen_str.h"
#include "gen_msg.h"

#include "fh.H
.ft
.fi
.LP
.\".nf
.\".ta 0.8i
.TP 7n
void
checkFitsTable( hStatus &
.IR fhStatus
);
.TP 7n
void
close( hStatus &
.IR fhStatus
);
.TP 7n
void
config( hStatus &
.IR fhStatus
);
.TP 7n
void
init( hStatus &
.IR fhStatus,
char *
.IR datasetName,
char *
.IR serverName
);
.TP 7n
void
parseHeader( hStatus &
.IR fhStatus,
void *
.IR buffPtr,
long
.IR buffSize,
char *
.IR datasetName
);

.SH DESCRIPTION
.B fh
library provides access to FITS header storage routines.  
This library uses the dd library to obtain information about the
data dictionary.

Following is a list of the library's functions:
.Ty
checkFitsTable()
This function is used to check that all columns listed in the data dictionary
exist in the fitsHeader table in the database.
.Ty
close()
This function is used to close the fh library.  This will close the database
connections and free any used memory.
.Ty
config()
This function is used to read a line from a configuration file and store the
data retrieved.  Can be used by incorporated into an applications configuration
file.
.Ty
init()
This function initializes the fh library.  It will initialize the database
connection, initialize the dd library and set any necessary variables.  It
will then check that all columns listed in the data dictionary, under the 
heading Column, exists in the fitsHeader table in the database.
.Ty
parseHeader()
This function parses the FITS file passed in and saves keyword values in the 
database that are indicated in the data dictionary.


.SH FILES

.SS

.B fh
library does not need a separate configuration file.  Rather the information
required can be incorporated into an application's configuration file.  It
requires a single line in a configuration file.  The method 
.B config
can be used to read that line.  

The following is an example of the line required in the configuration file.
(Text followed by a '#' is treated as a comment and ignored)

.sp
.nf

#
# 
#  FITS table name where FITS header information is to be stored. 
# 
# keyword       FITS table name 
# -------       ---------------
#
 
 fitsTable       fitsHeader

.fi

.B fh
also requires the dd configuration file. Please refer to dd's man page
for a description of the configuration file.  In particular, the
columns "Gemini Mandatory" and "Column Name" are particularly relevant
to the 
.B fh
library.  The Gemini Mandatory column indicates which keywords should
be found in a
FITS
file.  Warnings are returned by parseHeader if a Gemini Mandatory
keyword is not found or found to have a null value.

The "Column Name" is the name of the column in the FITS table in the 
database to store the value of a keyword.  If the keyword is not found in 
the 
FITS
file then a warning is returned.  If the keyword is found, but has a null value
then no value is stored in the database for that keyword.


.SH ENVIRONMENT VARIABLES

The environment variable
.B LIBDD_CONFIG_DIR may be set to the path of the 
directory containing the 
configuration file. If
.B LIBDD_CONFIG_DIR
is not set, 
.B DEFAULT_CONFIG_DIR 
should be set to where the configuration file can be found.  If
that is not set the the current directory will be used.


.SH DIAGNOSTICS

none.


.SH SEE ALSO

.BR dd (3).


.SH BUGS
If another library also uses the dd library, then only one of those 
libraries should close the dd library.  This library uses the cfitsio library,
which is not thread safe.  There are locks internally to ensure
that the cfitsio library is not accessed by more than one thread at 
a time.  If any application uses cfitsio and this library 
then a locking mechanism will have to be used to
make sure both are not accessed at the same time in different threads.

.SH AUTHORS
Jennifer Dunn

.br



National Research Council
.br
Herzberg Institute of Astrophysics
.br
Canadian Astronomy Data Centre


